### ISSUE TITLE
[Question]: Unreasonable exeption when sign in with email.

### ISSUE THREAD

**Issue by hieuwu** [supabase-community/supabase-kt#115]
### What is your question?

I'm using GoTrue to build authentication in my app. After signing up, I use goTrue.loginWith(Email) and got an exception. 
Did I miss any configuration?
Here's the message I got:
```
invalid_grant 
URL: https://jzdduyzfelmfniuebkre.supabase.co/auth/v1/token?grant_type=password&redirect_to=supabase%3A%2F%2Flogin
Headers: [apikey=[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZGR1eXpmZWxtZm5pdWVia3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA2OTUwODMsImV4cCI6MTk5NjI3MTA4M30.Eo29b7weMkAOucfGa0eRbb7fZR7Cpw1_Ifde_FV3zGc], Accept=[application/json], Accept-Charset=[UTF-8]]
Http Method: POST
```
How I provide GoTrue:
```kotlin
createSupabaseClient(
            supabaseUrl = BuildConfig.SUPABASE_URL,
            supabaseKey = BuildConfig.API_KEY
        ) {
            install(GoTrue)
        }.gotrue
```
How I call signin (authService has type of GoTrue):
```kotlin
authService.loginWith(Email) {
            this.email = email
            this.password = password
        }
```

**Comment by jan-tennert** [comment]
That looks alright, is that the whole error? And also are the credentials valid?

**Comment by jan-tennert** [comment]
> ### What is your question?
> I'm using GoTrue to build authentication in my app. After signing up, I use goTrue.loginWith(Email) and got an exception. Did I miss any configuration? Here's the message I got:
> 
> ```
> invalid_grant 
> URL: https://jzdduyzfelmfniuebkre.supabase.co/auth/v1/token?grant_type=password&redirect_to=supabase%3A%2F%2Flogin
> Headers: [apikey=[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZGR1eXpmZWxtZm5pdWVia3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA2OTUwODMsImV4cCI6MTk5NjI3MTA4M30.Eo29b7weMkAOucfGa0eRbb7fZR7Cpw1_Ifde_FV3zGc], Accept=[application/json], Accept-Charset=[UTF-8]]
> Http Method: POST
> ```
> 
> How I provide GoTrue:
> 
> ```kotlin
> createSupabaseClient(
>             supabaseUrl = BuildConfig.SUPABASE_URL,
>             supabaseKey = BuildConfig.API_KEY
>         ) {
>             install(GoTrue)
>         }.gotrue
> ```
> 
> How I call signin (authService has type of GoTrue):
> 
> ```kotlin
> authService.loginWith(Email) {
>             this.email = email
>             this.password = password
>         }
> ```

Could also be that the user didn't confirm their email, gonna include that error in the next version

**Comment by jan-tennert** [comment]
If you want to disable that the user has to confirm their email, disable it in supabase. Otherwise you can setup deeplinking so the user can login directly into your app by clicking on the link in the verification (see wiki)

**Comment by hieuwu** [comment]
Strange. 

> > ### What is your question?
> > I'm using GoTrue to build authentication in my app. After signing up, I use goTrue.loginWith(Email) and got an exception. Did I miss any configuration? Here's the message I got:
> > ```
> > invalid_grant 
> > URL: https://jzdduyzfelmfniuebkre.supabase.co/auth/v1/token?grant_type=password&redirect_to=supabase%3A%2F%2Flogin
> > Headers: [apikey=[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZGR1eXpmZWxtZm5pdWVia3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA2OTUwODMsImV4cCI6MTk5NjI3MTA4M30.Eo29b7weMkAOucfGa0eRbb7fZR7Cpw1_Ifde_FV3zGc], Accept=[application/json], Accept-Charset=[UTF-8]]
> > Http Method: POST
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How I provide GoTrue:
> > ```kotlin
> > createSupabaseClient(
> >             supabaseUrl = BuildConfig.SUPABASE_URL,
> >             supabaseKey = BuildConfig.API_KEY
> >         ) {
> >             install(GoTrue)
> >         }.gotrue
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How I call signin (authService has type of GoTrue):
> > ```kotlin
> > authService.loginWith(Email) {
> >             this.email = email
> >             this.password = password
> >         }
> > ```
> 
> Could also be that the user didn't confirm their email, gonna include that error in the next version

Just tried and it works now. This is mostly because of the account is not verified yet and it's not existed. Thanks for the improvement on the exception message. Appreciate that mate ! 🤜🤛
