### ISSUE TITLE
[Bug]: Stately dependency breaks the build

### ISSUE THREAD

**Issue by brezinajn** [supabase-community/supabase-kt#119]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### Version(s)

0.9.2

### Target(s)

Android

### What happened? (include your code)

After updating from `0.9.0` to `0.9.2` builds fail with `Duplicate class co.touchlab.stately.HelpersJVMKt found in modules stately-common-jvm-2.0.0-rc1 (co.touchlab:stately-common-jvm:2.0.0-rc1) and stately-strict-jvm-2.0.0-rc1 (co.touchlab:stately-strict-jvm:2.0.0-rc1)`. Supabase-kt is the only library in my dependencies with transitive dependency to stately.

**Comment by jan-tennert** [comment]
> ### General Info
> * [x]  I checked for similar bug report
> * [x]  I am using the latest version
> * [x]  I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
> 
> ### Version(s)
> 0.9.2
> 
> ### Target(s)
> Android
> 
> ### What happened? (include your code)
> After updating from `0.9.0` to `0.9.2` builds fail with `Duplicate class co.touchlab.stately.HelpersJVMKt found in modules stately-common-jvm-2.0.0-rc1 (co.touchlab:stately-common-jvm:2.0.0-rc1) and stately-strict-jvm-2.0.0-rc1 (co.touchlab:stately-strict-jvm:2.0.0-rc1)`. Supabase-kt is the only library in my dependencies with transitive dependency to stately.
> 
> ### Steps To Reproduce (optional)
> _No response_
> 
> ### Relevant log output (optional)
> _No response_

Should be fixed in 0.9.3

**Comment by brezinajn** [comment]
Works. Thanks for a quick fix, as usual :)
