### ISSUE TITLE
[Bug]: 1.0.0 seems not to be published properly

### ISSUE THREAD

**Issue by brezinajn** [supabase-community/supabase-kt#158]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.0.0

### Target(s)

Android

### What happened? (include your code)

[Here](https://repo.maven.apache.org/maven2/io/github/jan-tennert/supabase/bom/) you can see the 1.0.0 is missing.

**Comment by jan-tennert** [comment]
Seems like there was a problem closing/releasing the repository. Weird that I didn't get an email. Should be there now

**Comment by brezinajn** [comment]
Works fine. Thanks
