### ISSUE TITLE
[Feature request]: Allow access to error fields from RestException class

### ISSUE THREAD

**Issue by aruke** [supabase-community/supabase-kt#180]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

I want to access the error fields coming from Supabase.
Right now RestExecption is a super class for all the error responses, but I cannot access any field from the actual response via RestExecption.
My personal opinion is that it would be better if we could access the response fields, like `error`, to identify the exact error. I tried `toString`, but it contains the concatenation of error messages and response fields.
If an alternate method is available, please let me know. If accepted, I can also try contributing.

### Usecase

One instance that I am dealing with is receiving bad email error from `.gotrue.sendOtpTo` method. The RestException thrown is BadReqestExeption, and the `caught.message` is:
```
io.github.jan.supabase.exceptions.BadRequestRestException: Unable to validate email address: invalid format
URL: http://localhost:54321/auth/v1/otp
Headers: [Authorization=[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0], apikey=[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0], Accept=[application/json], Accept-Charset=[UTF-8]]
Http Method: POST
```
In the case of JS SDK, I can get the error message `Unable to validate the email address: invalid format`, identify the exact error, and show a localized error message to the end user.the

**Comment by jan-tennert** [comment]
You are definitely right, it should be better to be able to access the error fields itself. As this is a pretty easy change, I just made a commit to a different branch, exposing both the error and the optional description in the RestException. You can try it out with the version `1.0.3-dev`
And also we are always open to contributions!

**Comment by jan-tennert** [comment]
Included in the newest version

**Comment by aruke** [comment]
Thanks a lot @jan-tennert! I checked `1.0.3-dev` and can access the fields now.
