### ISSUE TITLE
[Question]: Use Moshi serializer instead of KotlinXSerialization

### ISSUE THREAD

**Issue by yoobi** [supabase-community/supabase-kt#202]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Hello, I'm exploring Supbase and great work with what you did !

I'm wondering if it's possible to use Moshi instead of KotlinXSerialization to serialize objects ? 
My usecase is the following. I'm building an Android app where I use Retrofit+OkHttp+Moshi to make call on my API. I'm also using Supabase Client Realtime to listen to update in a table, in order to convert the raw object to a data class I used `it.decodeRecord<DataClass>` which use KotlinXSerialization in the background.

Why am I asking this ? I'd like to avoid using multiple dependencies to serialize object and have only one serializer in my projects.

**Comment by jan-tennert** [comment]
It is definitely possible, you can access the raw `record` and `oldRecord` in `PostgresAction`. As this is a KotlinX Serialization `JsonObject`, you may need to call `toString` to get the raw json string, but then you should be able to use whatever you want.

**Comment by yoobi** [comment]
Could be a future improvement. As of now I'll use the `record.toString` with my `Moshi` object !

**Comment by jan-tennert** [comment]
See #203

**Comment by jan-tennert** [comment]
Hey @yoobi, I added support for custom serializer in #205. Could you try out `1.1.0-beta-1` and see how it works for you? Syntax is explained in the PR.
