### ISSUE TITLE
Wrong reference link on documentation

### ISSUE THREAD

**Issue by unovil** [supabase-community/supabase-kt#226]
https://github.com/supabase-community/supabase-kt/blob/4069c76ecea570b4d4ac3b0c8a20b65504c17256/demos/android-login/README.md?plain=1#L13

Not a high priority one, I just found it when scrolling through documentation. In the README file of the `android-login` demo folder, the `supabaseModule.kt` text references the wrong file link in the tree structure. It _should_ reference [this](https://github.com/supabase-community/supabase-kt/blob/master/demos/android-login/common/src/commonMain/kotlin/io/github/jan/supabase/common/di/supabaseModule.kt). I don't know if this is intended, or whether it shows in other demo folders, I just pointed it out. Thanks!

**Comment by jan-tennert** [comment]
Thank you, fixed it on the master branch!
