### ISSUE TITLE
[Bug]: Impossible to use Realtime broadcasts

### ISSUE THREAD

**Issue by EBfVince** [supabase-community/supabase-kt#227]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.1.0

### Target(s)

JVM, Android

### What happened? (include your code)

I'm trying to use realtime broadcasts.

I followed the documentation, but at the step `channel.join(blockUntilJoined = true)`, the process looks blocked.

### Steps To Reproduce (optional)

Here is a quick exemple:

```kotlin
val realtime = supabaseClient.realtime
val channel = realtime.createChannel("hey")
val broadcastFlow = channel.broadcastFlow<Message>(event = "test")

Napier.d { "Broadcast flow" }

launch {
     broadcastFlow.collect {
          Napier.d { "Received message: $it" }
     }
}

Napier.d { "Joining channel" }

channel.join(blockUntilJoined = true)

Napier.d { "Broadcasting" }

channel.broadcast(event = "message", Message("Hello world!"))
```

Here are my logs:

```
Broadcast flow
Joining channel
Joining channel realtime:hey
Joining realtime socket with body {"config":{"broadcast":{"ack":false,"self":false},"presence":{"key":""},"postgres_changes":[]}}
```

I have the same behaviors on JVM (desktop Mac M1) and Android.

**Comment by jan-tennert** [comment]
Did you actually call `client.realtime.connect()` before joining the channel? If supabase-kt isn't connected to the websocket, it obviously can't join.

**Comment by EBfVince** [comment]
Wow, you are completely right! Sorry I missed it. It's working fine now. Thank you for your help 🙌

**Comment by jan-tennert** [comment]
> Wow, you are completely right! Sorry I missed it. It's working fine now. Thank you for your help 🙌

No problem, will improve the documentation on that and add a check on joining!
