### ISSUE TITLE
Decode json body into list objects?

### ISSUE THREAD

**Issue by youndon** [supabase-community/supabase-kt#245]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

I've already been check `decodeList<T>()` method and somehow it does not work for me, Yes I get my data by the `select()` method but I couldn't convert it into a `list`.
And the issue isn't in the object template itself, I made sure that data correspond with my data class.

My method.
```kotlin
    override fun getAllData(): Flow<ApiResult<List<Invalid>>> {
        return flow {
            emit(ApiResult.Loading)
            kotlin.runCatching {
                val res = client.postgrest["english"].select()
                val invalids = res.decodeList<Invalid>() // <- the issue here. 
                emit(ApiResult.Success(invalids))
            }.onFailure {
                emit(ApiResult.Error(it.message))
            }
        }
    }
```
My data class.
```kotlin
@Keep
@Serializable
data class Invalid(
    @SerialName("id")
    val id: Int = 0,
    @SerialName("data")
    val data: String = ""
)
```

Any help??

**Comment by jan-tennert** [comment]
You could try to print out `res.body` and check if you are actually receiving a JsonArray

**Comment by youndon** [comment]
Thank you **jan** for responding, I find that I forget to add `kotlin.serialization` plugin to my `module`, And now I get all my data as well.
But this time I can't emit it, And I know it's not the right place for this issue but I hope you may know something about it.

Also my vm.
```kotlin
@HiltViewModel
class ApiViewModel @Inject constructor(
    private val repo: ApiRepositoryImpl
): ViewModel() {

    private val _uiState = MutableStateFlow<ApiResult<*>>(ApiResult.Loading)
    val uiState: StateFlow<ApiResult<*>>
        get() = _uiState
            .stateIn(
                viewModelScope,
                SharingStarted.WhileSubscribed(),
                ApiResult.Loading
            )

    init {
        getAllData()
    }

    fun getAllData() {
        viewModelScope.launch(Dispatchers.IO) {
            repo.getAllData().collectLatest {
                _uiState.update { it }
            }
        }
    }
```
I don't know why but I just get the initializer data from `MutableStateFlow`  (`Loading` in my case).

**Comment by youndon** [comment]
Ah, and you are free to close this issue.

**Comment by jan-tennert** [comment]
Does the `uiState` emit nothing or the `getAllData` method?

**Comment by jan-tennert** [comment]
In any case, you can convert this:
```kotlin
val uiState: StateFlow<ApiResult<*>>
        get() = _uiState
            .stateIn(
                viewModelScope,
                SharingStarted.WhileSubscribed(),
                ApiResult.Loading
            )
```
Into this:
```kotlin
val uiState: StateFlow<ApiResult<*>> = _uiState.asStateFlow()
```

**Comment by youndon** [comment]
Ok well, I think I fix this, It wasn't in `_uiState` object but it was in `getAllData()` method in `_uiState.update { .. }` to be specific, And I don't know why but when I change it to become `_uiState.value = it` it did work fine.
Till now every thing's worked as well thank you **@jan-tennert** for your help.

**Comment by youndon** [comment]
One more question, For your opinion when you know that I have a long list of `English` words (thousands of them) and I guess that @supabase does not support the `List<T>` or `Array` data type which is better (I mean fast in respond)?

1. Create a new row for each word with the primary id.
2. Create one text and put all the words together and separate them later.

Thank you.

**Comment by jan-tennert** [comment]
Supabase does support Array types (which is just a JsonArray):
![image](https://github.com/supabase-community/supabase-kt/assets/26686035/c3b763c9-a210-49ba-a281-20ad0f77ef41)
