### ISSUE TITLE
[Feature request]: Improve rest exceptions or use a more functional pattern

### ISSUE THREAD

**Issue by jan-tennert** [supabase-community/supabase-kt#25]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Currently, there's primarily one exception type: RestException which is hard to catch because you don't know exactly whats causing the Rest Exception without parsing the raw error.
Now the library could either parse the exception and throw corresponding exceptions **(1)** or use a more functional pattern which forces developers to handle the result (maybe using [arrow-kt](https://arrow-kt.io/docs/core/) ?) **(2)**.
Independently of that, results of Postgrest Calls must be improved severely 
**Example for (1)**
```kotlin
try {
   gotrue.getUser("id")
} catch(e: UnauthorizedException) {

}
```

**Example 1 for (2)**
```kotlin
val result = gotrue.getUser("id")
when(result) {
      is Result.Success -> //
      is Result.Unauthorized -> //
}
```

**Example 2 for (2) using arrow-kt (which has the advantage of already being there, and could be implemented easily)**
```kotlin
val result = gotrue.getUser("id")
when(result) {
  is Either.Left -> when (result.value) {
    is UnauthorizedException -> //
    is IllegalArgumentException ->//
    else -> "Unknown error"
  }
  is Either.Right -> println(result.id)
}
```

### Usecase

Error Handling

**Comment by brezinajn** [comment]
Even though I'm a happy arrow user for years and I'm all for specifying sealed error domain wherever possible, I'm not sure if it's very ergonomic to add arrow as a dependency and make error handling harder to understand (although better). Until we (hopefully) get union types providing sealed error domain does not provide ready to use solution for the consumers. Consumers would have to map error domain of this lib to their error domain anyway. Maybe it'd be best just to provide clear sealed hierarchy extending `<some>Exception` and `throw` them. Wrapping library calls in `Either`/`Effect`/`Result` etc. is straightforward (and users are gonna be mapping errors to their own domain anyway). This'd keep the library unopinionated about error handling (and not scaring potential consumers with words like `monad` 😆 ), while retaining clear, easy to use, easy to understand error domain.

**Comment by jan-tennert** [comment]
Yea also thought about that, it might be best to just stick to the standard try catch way. Thought about adding a new **parseException** method to the Main Plugins (as the error responses are always different), and reworking the way the plugins make rest calls, so the library could handle exceptions and authenticated routes automatically

**Comment by brezinajn** [comment]
Regarding the "more functional pattern". There are some very nice things coming in the future. With context receivers we can specify that the function can be called only in a scope that can handle the problem. For example my wrapper looks like this:

``` Kotlin
context (EffectScope<ApplicationError.IO.DatabaseError>)
suspend inline fun <reified RES : HasIdentity<*>> Postgrest.list(
    tableDescriptor: TableDescriptor<RES, *, *>,
    crossinline where: PostgrestFilterBuilder.() -> Unit = {},
): List<RES> =
    attempt {
        catching {
            get(tableDescriptor.tableName)
                .select(filter = where)
                .decodeAs<List<RES>>()
        }
    } mapLeft {
        Napier.d(throwable = it) { "" }
        ApplicationError.IO.DatabaseError(it.message.orEmpty())
    }
```

Unfortunately context receivers are still experimental and available only for JVM.
