### ISSUE TITLE
[Question]: How to handle realtime downtime?

### ISSUE THREAD

**Issue by ferhatwi** [supabase-community/supabase-kt#255]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

When realtime disconnects unexpectedly, e.g. slow / no connection, how do I handle this downtime? 

For example on a chat app, I get the initial messages that are already in the database by a fetch query. Then I listen to the messages by `postgresChangeFlow<PostgresAction.Insert>`. 

While listening to messages, if there is a downtime for a few seconds, should I fetch a query filtered by `created_at > *start of the downtime timestamp*` and then re-establish realtime connectivity, or is there any more convenient way to keep this up to date?

**Comment by jan-tennert** [comment]
I don't know of any built in functionality to receive missed events, you probably have to fetch missed messages yourself.

**Comment by brezinajn** [comment]
I faced this issue before in an app that's being used mainly on spotty connection. There are basically two ways you can go about it.

1. Ignore it - Is small state desync gonna cause any real problems? You can always fetch the data before doing anything critical.
2. Fetch on every connection issue. This in theory should help minimize issues the user sees. In practice, if you're on spotty connection already, forcing a refresh might not be the best approach. And this won't ensure you didn't miss any events anyway.

Personally I fetch data when the app opens/wakes (you have to do that anyway) and start observing everything. Average user interaction time of the app in question is around two minutes. There's not gonna be that many desyncs in that time. Works really well for my use cases. For sure is not a solution that's gonna fit all.

**Comment by ferhatwi** [comment]
Thanks!
