### ISSUE TITLE
[Question]: error: Could not find: io.github.jan-tennert.supabase/postgrest-kt-iossimulatorarm64

### ISSUE THREAD

**Issue by eric-ampire** [supabase-community/supabase-kt#273]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Adding the dependency `io.github.jan-tennert.supabase:postgrest-kt:VERSION` is crashing on ios saying "error: Could not find: io.github.jan-tennert.supabase/postgrest-kt-iossimulatorarm64/1.3.0-rc-2"

Is there any way to fix this ?

**Comment by jan-tennert** [comment]
What do you mean crashing? On import or when running the app? Also how is your project structured? The dependency is not missing on maven central. Can you share your build file?

**Comment by jan-tennert** [comment]
No, ios is supported. There is no ios target in the demos because I cant run ios apps for testing. Is this the full error?

**Comment by eric-ampire** [comment]
I've just fixed the issue, the version 1.2.0 wasn't compatible with kotlin 1.8.21

**Comment by jan-tennert** [comment]
Okay great! Do you need any further help?

**Comment by eric-ampire** [comment]
Right now I'm trying to use gotrue for auth,
```
apiClient.gotrue.signUpWith(Email) {
  email = "sample@gmail.com"
  password = "pass"
}
```

But I'm getting this error "(POST) failed with message: Failed to connect to localhost/127.0.0.1:443", there's any particular reason for that ?

**Comment by jan-tennert** [comment]
Did you add the internet intent?

**Comment by eric-ampire** [comment]
I do also have an error on iOS, I've the internet permission on Android

`NSErrorFailingURLStringKey=https://localhost/auth/v1/token?grant_type=password&redirect_to=https%3A%2F%2Fbe-served.com, NSErrorFailingURLKey=https://localhost/auth/v1/token?grant_type=password&redirect_to=https%3A%2F%2Fbe-served.com, _kCFStreamErrorDomainKey=1}`

**Comment by jan-tennert** [comment]
Okay, I assume you have your correct supabase url in the supabase client? Which Ktor engines are you using?

**Comment by eric-ampire** [comment]
Yeah

**Comment by eric-ampire** [comment]
I've just double check, the supabase url is correct https://<id>.supabase.co

**Comment by eric-ampire** [comment]
Is there anykind of config I need to do in order to make it work

```
createSupabaseClient(
  supabaseKey = BuildConfig.SUPABASE_TEST_API_KEY,
  supabaseUrl = BuildConfig.SUPABASE_TEST_URL,
  builder = {
    install(Postgrest)
    install(GraphQL)
    install(GoTrue)
  }
)
```

**Comment by jan-tennert** [comment]
No that seems right. Localhost is fallback url for internet problems, did you test this on an emulated device?

(Closing issue as this is off-topic)

**Comment by jan-tennert** [comment]
@eric-ampire Do you use the CIO ktor engine? Maybe that's doing some trouble, I also had a similar problem when I used this engine

**Comment by eric-ampire** [comment]
Yeah I've used that engine

**Comment by jan-tennert** [comment]
Try OkHttp for Android and Darwin for IOS, maybe that will help
