### ISSUE TITLE
[Bug]: Native login not working

### ISSUE THREAD

**Issue by brezinajn** [supabase-community/supabase-kt#282]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.3.0

### Target(s)

Android

### What happened? (include your code)

I have
``` Kotlin
install(ComposeAuth){
    googleNativeLogin(serverClientId = "...")
}
```
and 
``` Kotlin
val action = composeAuth.rememberLoginWithGoogle()
OutlinedButton(onClick = { action.startFlow() }) {
     ProviderButtonContent(provider = Google)
}
```
On the button click I get the one tap sign in dialog. After selecting and confirming an account I get:
`NativeSignInResult.Error("error: operation canceled")`

The source of the Error is [here](https://github.com/supabase-community/supabase-kt/blob/master/plugins/ComposeAuth/src/androidMain/kotlin/io/github/jan/supabase/compose/auth/composable/GoogleAuth.kt#L130)

I'm really not sure why the activity for result would end up with RESULT_CANCELED.

The device is Pixel 6 on Android 13.

**Comment by jan-tennert** [comment]
There could be a few things:
1. Did you create two OAuth credentials for both a Web and Android application (with the right data like package id and sha1-certificate)?
2. Do you use the Web OAuth Client Id in the Plugin? (The Android one doesn't work, but still must exist.
