### ISSUE TITLE
[Feature request]: Ability to update phone number via gotrue admin

### ISSUE THREAD

**Issue by azlekov** [supabase-community/supabase-kt#287]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Following this discussion: https://github.com/orgs/supabase/discussions/7265  It looks that is not possible to change the phone number of a user, in order later on to verify it via OTP.

```kotlin
@Serializable
data class AdminUserUpdateBuilder(
    var email: String? = null,
    var password: String? = null,
    @SerialName("app_metadata")
    var appMetadata: JsonObject? = null,
    @SerialName("user_metadata")
    var userMetadata: JsonObject? = null,
    @SerialName("email_confirm")
    var emailConfirm: Boolean? = null,
    @SerialName("phone_confirm")
    var phoneConfirm: Boolean? = null,
    var phone: String? = null
)
```

### Usecase

Ability to change phone number of a user and later on to verify it using OTP.

**Comment by jan-tennert** [comment]
I'm not sure if I'm getting this wrong, so according to the discussion you need to use this to update the phone number:
```kotlin
gotrue.verifyPhoneOtp(OtpType.Phone.PHONE_CHANGE, phoneNumber, token)
```
So, what are you requesting exactly?

**Comment by jan-tennert** [comment]
> Hey @jan-tennert, to be honest I'm still investigating in supabase world how I can add or change phone number of a user logged with email for example.
> 
> Do I need to update the user phone number "phone_change" field manually before call `verifyPhoneOtp`?

You can do that, by using the `modifyUser` method:
1. Modify the user's phone number
```kotlin
//When logged in
gotrue.modifyUser {
    phoneNumber = "12345678912"
}
```
2. The user should get sent a code (assuming you enabled the phone provider)
3. Verify the OTP as shown above

**Comment by azlekov** [comment]
@jan-tennert I thought the same but unfortunately is not working. 

What I did is a DB trigger to set `change_phone` after that from the Kotlin I'm doing the above plus an `resend` which seems to be a workaround in addition of having `change_phone` to send the OTP:

In summary:

1. Set `change_phone` value on the user
2. Modify the user's phone as mentioned above
3. Trigger resend:

```kotlin
client.gotrue.modifyUser {
    this.phoneNumber = phoneNumber
 }

client.gotrue.resendPhone(OtpType.Phone.PHONE_CHANGE, phoneNumber)
```

4. Verify the OTP

**Comment by jan-tennert** [comment]
> 

What do you mean with not working? I was able to use modify user and then was sent an OTP. Did you receive OTP?

**Comment by azlekov** [comment]
Just using modify user is not sending an OTP. It updates the user's 'phone' not 'change_phone'. Is this the proper behaviour?

**Comment by jan-tennert** [comment]
> Just using modify user is not sending an OTP. It updates the user's 'phone' not 'change_phone'. Is this the proper behaviour?

For me, it changed "change_phone" and sent an OTP, not sure what's happening for you. You could try asking in supabase' Github/Discord. If you have any other questions let me know!
