### ISSUE TITLE
[Bug]: 0.7.0-alpha-1 Getting timeout exception on every call

### ISSUE THREAD

**Issue by brezinajn** [supabase-community/supabase-kt#29]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

On [0.7.0-alpha-1](https://github.com/supabase-community/supabase-kt/releases/tag/0.7.0-alpha-1) all network calls (at least from Auth and Postgrest) end up in timeout exception. Changing to 0.6.0 fixes the issue.

### Platform(s)

Android

**Comment by jan-tennert** [comment]
Fixed in alpha-2, supabase-kt was trying to call the 127.0.0.1 because no other url was specified
