### ISSUE TITLE
[Feature request]: Add iOS to demos

### ISSUE THREAD

**Issue by jan-tennert** [supabase-community/supabase-kt#290]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

It would be good if all demos which have android as a target (excluding the android login demo) also target iOS. I don't think that would be too hard as the common modules don't use JVM-related stuff as most of the demos also target JS. I can't do that myself as I don't have a Mac to test it. Help appreciated.

### Usecase

*-*

**Comment by hieuwu** [comment]
Is this issue just to try and run the sample project in iOS emulator to make sure it works Jan?

**Comment by jan-tennert** [comment]
> Is this issue just to try and run the sample project in iOS emulator to make sure it works Jan?

Ideally the `chat-demo`, `file-upload`, `multiplatform-deeplinks`, and `multi-factor-authentication`  demos get a (target) module for iOS. Which should just be adding some expect/actual methods in common code and in the iOS module is an iOS app just using compose like android.

**Comment by hieuwu** [comment]
Thanks for the context. I'll give it a try
