### ISSUE TITLE
[Bug]: I think realtime filters are not working correctly

### ISSUE THREAD

**Issue by aperher** [supabase-community/supabase-kt#291]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.3.1

### Target(s)

JVM and Android

### What happened? (include your code)

Realtime is connecting to postgres correctly but I was not receiving the changes messages, although, two weeks ago the app was running correctly and the messages of realtime subscription was being received. After some time debugging I realized that removing the filters, messages were sending again.

![image](https://github.com/supabase-community/supabase-kt/assets/100694428/db0ba0b8-cd47-4946-801a-e42e770b396c)

### Relevant log output (optional)

```shell
no relevant information on log output
```

**Comment by jan-tennert** [comment]
> ### General Info
> 
>     * [x]  I checked for similar bug report
> 
>     * [x]  I am using the latest version
> 
>     * [x]  I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
> 
>     * [x]  I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs
> 
> 
> ### Version(s)
> 
> 1.3.1
> ### Target(s)
> 
> JVM and Android
> ### What happened? (include your code)
> 
> Realtime is connecting to postgres correctly but I was not receiving the changes messages, although, two weeks ago the app was running correctly and the messages of realtime subscription was being received. After some time debugging I realized that removing the filters, messages were sending again.
> 
> ![image](https://user-images.githubusercontent.com/100694428/268363709-db0ba0b8-cd47-4946-801a-e42e770b396c.png)
> ### Steps To Reproduce (optional)
> 
> _No response_
> ### Relevant log output (optional)
> 
> ```shell
> no relevant information on log output
> ```

I just tested using filter property myself and it works fine. I assume you checked if the row name in the filter is correct?

**Comment by aperher** [comment]
That's it, it was my fault
