### ISSUE TITLE
[Bug]:  Errors when call postgrest.update with Moshi codegen

### ISSUE THREAD

**Issue by fan123199** [supabase-community/supabase-kt#293]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

I make my own MoshiSerializer with below 
```kotlin
defaultSerializer = MoshiSerializer(
                Moshi.Builder()
                    .add(ColorAdapter())
                    .add(LocalDateTimeAdapter())
                    .build()
            )
```
And I am not using the `.addLast(KotlinJsonAdapterFactory())` because I want to use kotlin codegen as descriped in [Moshi - Github](https://github.com/square/moshi#codegen), I add annotations to all my data class that used in supabase. 
```
@JsonClass(generateAdapter = true)
data class Post(
    ...
)
```
 but When I use the `update`, it shows me the error.

```
java.lang.IllegalArgumentException: No JsonAdapter for class kotlinx.serialization.json.JsonObject, you should probably use Map instead of JsonObject (Moshi only supports the collection interfaces by default) or else register a custom JsonAdapter.
     at com.squareup.moshi.ClassJsonAdapter$1.throwIfIsCollectionClass(ClassJsonAdapter.java:125)
     at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:69)
     at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
     at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
     at com.squareup.moshi.Moshi.adapter(Moshi.java:75)
     at com.squareup.moshi._MoshiKotlinExtensionsKt.adapter(-MoshiKotlinExtensions.kt:40)
     at io.github.jan.supabase.serializer.MoshiSerializer.encode(MoshiSerializer.kt:17)
```
How can i write the custom JsonAdapter or any other solutions?

**Comment by fan123199** [comment]
yeah , it is working well with version 1.3.2-dev-1. Waiting for this version to release.

**Comment by jan-tennert** [comment]
> yeah , it is working well with version 1.3.2-dev-1. Waiting for this version to release.

Great! The release should be out pretty soon!
