### ISSUE TITLE
[Question]: deleteSession from SessionManager will not notify sessionStatus

### ISSUE THREAD

**Issue by seankcw** [supabase-community/supabase-kt#305]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Is it a bug or handle intentionally? The reason why I call `deleteSession` directly is because I want to support the self-account deletion on frontend. But after deleted an account, the logout function will not be worked any more as the token is invalided. So I'm checking on how can I support this feature.

**Comment by jan-tennert** [comment]
> ### General info
> 
>     * [x]  I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
> 
> 
> ### What is your question?
> 
> Is it a bug or handle intentionally? The reason why I call `deleteSession` directly is because I want to support the self-account deletion on frontend. But after deleted an account, the logout function will not be worked any more as the token is invalided. So I'm checking on how can I support this feature.

Hey, yes this is intentioally: The SessionManager really only deletes the session from storage and nothing more. The status is getting handled by the GoTrue plugin. But adding a method to clear both the storage & the GoTrue plugin from the session is a good suggestion. I'll add this in the next version!

**Comment by seankcw** [comment]
@jan-tennert great to hear that! Would you mind if tag a rc version first?

**Comment by jan-tennert** [comment]
> @jan-tennert great to hear that! Would you mind if tag a rc version first?

Sure, `1.4.1-rc-1` is currently releasing.

**Comment by seankcw** [comment]
@jan-tennert how long does it take to see the release are available to use?

**Comment by jan-tennert** [comment]
Its already available, just haven't created release notes yet

**Comment by jan-tennert** [comment]
> @jan-tennert Checked the `1.4.1-rc-1`, I got an error while compiling the project on both Android and iOS
> 
> Android
> 
> ```
> Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
>     class io.github.jan.supabase.gotrue.GoTrue, unresolved supertypes: io.github.jan.supabase.plugins.MainPlugin, io.github.jan.supabase.plugins.CustomSerializationPlugin
>     class io.github.jan.supabase.postgrest.Postgrest, unresolved supertypes: io.github.jan.supabase.plugins.MainPlugin, io.github.jan.supabase.plugins.CustomSerializationPlugin
> Adding -Xextended-compiler-checks argument might provide additional information.
> ```
> 
> iOS
> 
> ```
> <user>/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.10/klib/platform/ios_arm64]
> error: Compilation finished with errors
> ```

Seems to work perfectly fine for me, does `1.4.0` work and how are you adding the dependency?

**Comment by seankcw** [comment]
@jan-tennert I don't have this issue on 1.4.0 and my installation is similar with the official guideline

```
implementation(platform("io.github.jan-tennert.supabase:bom:1.4.1-rc-1"))
implementation("io.github.jan-tennert.supabase:postgrest-kt")
implementation("io.github.jan-tennert.supabase:realtime-kt")
```

**Comment by seankcw** [comment]
Any ideas of this when comparing master with 1.4.0? https://github.com/supabase-community/supabase-kt/compare/1.4.0...master

**Comment by jan-tennert** [comment]
Which Kotlin version are you using?

**Comment by jan-tennert** [comment]
> Any ideas of this when comparing master with 1.4.0? [1.4.0...master](https://github.com/supabase-community/supabase-kt/compare/1.4.0...master)
> 
> More information from the error logs:
> 
> ```
> > Task :shared:compileKotlinIosSimulatorArm64 FAILED
> error: Could not find "io.github.jan-tennert.supabase:supabase-kt" in [/Users/<username>/your-app, /Users/<username>/.konan/klib, /Users/<username>/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.20-Beta2/klib/common, /Users/<username>/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.20-Beta2/klib/platform/ios_simulator_arm64]
> error: Compilation finished with errors
> ```

there were only dependency, gradle and agp updates which shouldn't really affect anything

**Comment by seankcw** [comment]
> Which Kotlin version are you using?

I am currently using 1.9.10, also tried 1.9.20-Beta-2 and both working fine on 1.4.0 but failed on 1.4.1-rc-1

**Comment by jan-tennert** [comment]
> > Which Kotlin version are you using?
> 
> I am currently using 1.9.10, also tried 1.9.20-Beta-2 and both working fine on 1.4.0 but failed on 1.4.1-rc-1

Tried it with multiple projects including the [chat-demo](https://github.com/supabase-community/supabase-kt/tree/master/demos/chat-demo-mpp) and all compile perfectly fine, can you try to make a reproducible example?

**Comment by jan-tennert** [comment]
> > Which Kotlin version are you using?
> 
> I am currently using 1.9.10, also tried 1.9.20-Beta-2 and both working fine on 1.4.0 but failed on 1.4.1-rc-1

Which Gradle and AGP versions are you using? Maybe they are too old?

**Comment by seankcw** [comment]
Previously, I used 8.3 and also tried 8.4. Then I changed to using 8.1.1 now after looking at the chat-demo.
What's your suggestion on choosing/upgrading gradle verion?

**Comment by jan-tennert** [comment]
> Previously, I used 8.3 and also tried 8.4. Then I changed to using 8.1.1 now after looking at the chat-demo.
> Finally, I can build it 🔥 BTW, what's your suggestion on choosing/upgrading gradle verion?

Normally I just use the newest version, not sure why it wasn't working for you. But great that it works now!
