### ISSUE TITLE
[Question]: How to get a response body from an rpc function?

### ISSUE THREAD

**Issue by alialbaali** [supabase-community/supabase-kt#308]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

First and foremost, thank you so much for this amazing client library!!!

Basically, I have an rpc function that acts as an endpoint and returns a result as follows:
```sql
create or replace function public.is_email_exist(email text)
returns json
language plpgsql
security definer set search_path = public
as $$
declare
value text;
begin
   select u.email into value from auth.users as u
   WHERE u.email = LOWER($1);

   if found then
      return json_build_object('is_exist', true);
   else
      return json_build_object('is_exist', false);
   end if;
end;
$$;
```

As far as I see, the `postgrest.rpc()` function returns `Unit`. And, I'm wondering if there's a way to get a result from an rpc function. If not possible, what would be the best way to handle the function above? I tried to access the `auth` schema from the client, but it didn't allow me.

Thank you!

**Comment by jan-tennert** [comment]
> ### General info
> 
>     * [x]  I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
> 
> 
> ### What is your question?
> 
> First and foremost, thank you so much for this amazing client library!!!
> 
> Basically, I have an rpc function that acts as an endpoint and returns a result as follows:
> 
> ```sql
> create or replace function public.is_email_exist(email text)
> returns json
> language plpgsql
> security definer set search_path = public
> as $$
> declare
> value text;
> begin
>    select u.email into value from auth.users as u
>    WHERE u.email = LOWER($1);
> 
>    if found then
>       return json_build_object('is_exist', true);
>    else
>       return json_build_object('is_exist', false);
>    end if;
> end;
> $$;
> ```
> 
> As far as I see, the `postgrest.rpc()` function returns `Unit`. And, I'm wondering if there's a way to get a result from an rpc function. If not possible, what would be the best way to handle the function above? I tried to access the `auth` schema from the client, but it didn't allow me.
> 
> Thank you!

Hey, that is a bug, the rpc function should return a `PostgrestResult` like all other DB methods. I'm releasing `1.4.1-rc-2` with this bug fixed, let me know if it works!

**Comment by alialbaali** [comment]
Yes, it works without any issues. Thank you!
