### ISSUE TITLE
[Feature request]: Redirect parameter in gotrue.modifyUser

### ISSUE THREAD

**Issue by alialbaali** [supabase-community/supabase-kt#312]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Hello, is it possible to get a `redirect_to` parameter in `gotrue.modifyUser` method? Thank you!

### Usecase

Useful when updating the user email and you would like to redirect the user to a different endpoint rather than the host, something like `https://example.com/verify`.

**Comment by jan-tennert** [comment]
> ### General Info
> 
>     * [x]  I installed the latest version of Supabase Kt
> 
>     * [x]  I checked for similar feature requests
> 
> 
> ### Feature request
> 
> Hello, is it possible to get a `redirect_to` parameter in `gotrue.modifyUser` method? Thank you!
> ### Usecase
> 
> Useful when updating the user email and you would like to redirect the user to a different endpoint rather than the host, something like `https://example.com/verify`.

Definitely, you can try out `1.4.2-dev-1` and tell me if it works!
