### ISSUE TITLE
[Feature request]: Return UserInfo when using gotrue.loginWith() method

### ISSUE THREAD

**Issue by alialbaali** [supabase-community/supabase-kt#313]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

It would be nice if `gotrue.loginWith` returns `UserInfo` object. Thank you!

### Usecase

Instead of making another request to get the ID or the email, `gotrue.loginWith` could provide that after successful login.

**Comment by jan-tennert** [comment]
> ### General Info
> 
>     * [x]  I installed the latest version of Supabase Kt
> 
>     * [x]  I checked for similar feature requests
> 
> 
> ### Feature request
> 
> It would be nice if `gotrue.loginWith` returns `UserInfo` object. Thank you!
> ### Usecase
> 
> Instead of making another request to get the ID or the email, `gotrue.loginWith` could provide that after successful login.

Hey! You can access the user after logging in using `(gotrue.sessionStatus as SessionStatus.Authenticated).session.user`, or in short `gotrue.currentUserOrNull()`

**Comment by alialbaali** [comment]
I can't believe I missed that. Thank you!
