### ISSUE TITLE
[Feature request]: OkHttp3Client support

### ISSUE THREAD

**Issue by heatcreep** [supabase-community/supabase-kt#322]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

I would like to be able to override/add caching for my calls to my tables and currently there doesn't appear to be any support for doing that. 

### Usecase

As mentioned above, being able to cache table queries when offline would be awesome.

**Comment by brezinajn** [comment]
You can specify `httpEngine` in `SupabaseClientBuilder` there is an `OkHttp` backed `Ktor` client so you could use that one.

**Comment by jan-tennert** [comment]
> ### General Info
> 
>     * [x]  I installed the latest version of Supabase Kt
> 
>     * [x]  I checked for similar feature requests
> 
> 
> ### Feature request
> 
> I would like to be able to override/add caching for my calls to my tables and currently there doesn't appear to be any support for doing that.
> ### Usecase
> 
> As mentioned above, being able to cache table queries when offline would be awesome.

Normally you don't even need to specify the Engine yourself, Ktor will pick one from your dependencies. If you want to add caching, you can either specify a custom Http Engine or call `httpConfig` to install custom plugins.

**Comment by heatcreep** [comment]
This was super helpful! I appreciate it a ton.
