### ISSUE TITLE
[Bug]: Google Auth Error (Code 16)

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [supabase-community/supabase-kt#325]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.4.4

### Target(s)

Android

### What happened? (include your code)

Affected module: `io.github.jan-tennert.supabase:compose-auth`

While using [Native Google Auth on Android](https://github.com/supabase-community/supabase-kt/tree/master/plugins/ComposeAuth#native-google-auth-on-android), I get the following error message:

```
16: Cannot find a matching credential.
```

I know it's not related to Supabase's code, but I have searched a little and found that some other people are facing this same issue, here's the issuetracker ticket for this same error:

https://issuetracker.google.com/issues/302775651

People have mentioned that using an older version for the following dependency helps with this error for now:
Dependency: `com.google.android.gms:play-services-auth`
Working version: `20.4.1`

Therefore, request you to please take a look into this and take appropriate action(s) (maybe downgrade the dependency version until this issue is resolved by Google in a newer version).

> **P.S** - I'm open to making contribution for the same (i.e. downgrade the dependency version for now) if you feel that's the right way to go

**Comment by jan-tennert** [comment]
Sure we could downgrade the dependency, does Native Auth work at all or do you always get this error?

**Comment by jan-tennert** [comment]
In any case, you can make a PR downgrading this version if you want

**Comment by shubhamsinghshubham777** [comment]
> Does Native Auth work at all or do you always get this error

I have just started up with a new project, and for now, I'm getting this error in 100% of attempts (I have been trying it out for a few hours now). 

We can wait and test for a while if you think that would be better.

**Comment by jan-tennert** [comment]
> > Does Native Auth work at all or do you always get this error
> 
> I have just started up with a new project, and for now, I'm getting this error in 100% of attempts (I have been trying it out for a few hours now).
> 
> Will be creating a PR in a short while 👍🏻

Thanks! Merged it and publishing version `1.4.6`! Let me know if you still have problems!
