### ISSUE TITLE
[Question]: How to retrive custom field from user AppMetadata ?

### ISSUE THREAD

**Issue by florian-mlr** [supabase-community/supabase-kt#328]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

In my database i have custom field in the `raw_app_meta_data` field but in kotlin this field is already transformed into  `AppMetadata` object which contains only two values (provider and providers).

**Comment by jan-tennert** [comment]
Hey, this is a bug. I replaced the appMetadata field with a JsonObject, can you try out `1.4.7-dev-1` and tell me if it works?

**Comment by florian-mlr** [comment]
Yes with JsonObject i will be able to decode it into the object I want like it's done with `userMetadata` , thanks

**Comment by jan-tennert** [comment]
Included in `1.4.7`
