### ISSUE TITLE
[Question]: I can't set 'ignoreUnknownKeys = true' in Kotlin Sdk

### ISSUE THREAD

**Issue by MohamedRejeb** [supabase-community/supabase-kt#334]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Hi,
I'm trying to set 'ignoreUnknownKeys = true' so I can get data without specifying all the fields in the Dto.

```kotlin
httpConfig {
    install(ContentNegotiation) {
        json(Json {
            ignoreUnknownKeys = true
        })
    }
}
```

But this doesn't work.

**Comment by jan-tennert** [comment]
Hey, you don't specify a custom Json instance by changing the Ktor Client this will mostly break the SupabaseClient. In your SupabaseClientBuilder you can set the `defaultSerializer` property to `KotlinXSerializer(customJsonConfig)`. This is the serializer used to decode your DTOs

**Comment by jan-tennert** [comment]
So in your case this would be:
```kotlin
createSupabaseClient(url, key) {
    defaultSerializer = KotlinXSerializer(Json {
        ignoreUnknownKeys = true
    })
}
```

**Comment by MohamedRejeb** [comment]
It's working now, thanks!
