### ISSUE TITLE
Deprecate `Returning.MINIMAL` and migrate to a similar syntax to JS library

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/supabase-kt#342]
Currently, inserting and retrieving records looks something like this (from the docs): 

```kotlin
val city = City(name = "The Shire", countryId = 554)
supabase.postgrest["cities"].insert(city, returning = Returning.MINIMAL)
```

It would be better if we could have a syntax that is more similar to the JS client. 

```ts
const { data, error } = await supabase
  .from('countries')
  .insert({ id: 1, name: 'Denmark' })
  .select()
```

JS docs: https://supabase.com/docs/reference/javascript/insert?example=create-a-record-and-return-it

**Comment by jan-tennert** [comment]
Just a small note:
inserting and retrieving would be something like this:
```kotlin
val city = supabase.postgrest["cities"].insert(city).decodeSingle<City>()
```
Using `returning = Returning.MINIMAL` would be the same as not using `select()` in JS

**Comment by dshukertjr** [comment]
Ah, right. Mine was the opposite 😂

**Comment by jan-tennert** [comment]
Drafted the new syntax here: #353
