### ISSUE TITLE
Aligning the public API of realtime methods with JS client library

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/supabase-kt#343]
Currently the public API for interacting with realtime seems quite different from the JS library, so might be nice to have a more consistent API for Kotlin SDK as well.

Similar to how we do it for Typescript: 
```typescript
supabase
  .channel('room1')
  .on('postgres_changes', { event: '*', schema: '*' }, payload => {
    console.log('Change received!', payload)
  })
  .subscribe()
```
Maybe we could aim for something like this:
```kotlin
supabase
  .channel("room1")
  .on("postgres_changes", ChannelFilter(event = "*", schema = "*")) {
    payload -> println(payload) // realtime callback here
  }
  .subscribe()
```

**Comment by jan-tennert** [comment]
Hey, just wanted to clarify what part of the API is meant. Creating channels, listening for events or just everything?

**Comment by dshukertjr** [comment]
@jan-tennert 
Sorry for the lack of details on this issue. I have edited the original post with a rough idea of what I had in my mind. I'm sure there is a reason why the current library is designed this way, so open to hear what you think about it as well!

**Comment by dshukertjr** [comment]
> `Realtime#createChannel` -> `Realtime#channel`
> `Realtime#join` -> `Realtime#subscribe`
> and also add an extension function to the SupabaseClient like in https://github.com/supabase-community/supabase-kt/issues/346 for channel.

This sounds like a great idea that would require minimal code changes! Love it!

In addition to the above changes that you have proposed, could we also include `supabase.realtime.connect()` inside the new `.subscribe()` method?

I noticed that we need to call `supabase.realtime.connect()` and `channel.join()` currently to kick off the realtime subscription like the following:

```kotlin
val channel = supabase.realtime.createChannel("channelId") {
    //optional config
}
val changeFlow = channel.postgresChangeFlow<PostgresAction>(schema = "public")

//in a new coroutine (or use Flow.onEach().launchIn(scope)):
changeFlow.collect {
    when(it) {
        is PostgresAction.Delete -> println("Deleted: ${it.oldRecord}")
        is PostgresAction.Insert -> println("Inserted: ${it.record}")
        is PostgresAction.Select -> println("Selected: ${it.record}")
        is PostgresAction.Update -> println("Updated: ${it.oldRecord} with ${it.record}")
    }
}

supabase.realtime.connect()
channel.join()
```

**Comment by jan-tennert** [comment]
Yes so the plan was to automatically connect to the realtime socket when calling `subscribe` but leave the `connect` and `disconnect` methods and add a config property like `connectOnSubscribe` (which is `true` by default), if you want to do this yourself for some reason.

**Comment by dshukertjr** [comment]
Sounds awesome!

**Comment by jan-tennert** [comment]
Changes merged, let me know if you find anything else!

**Comment by dshukertjr** [comment]
Love the new syntax! Thank you so much for this update!
