### ISSUE TITLE
Provide a `from()` method to access Postgrest methods

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/supabase-kt#346]
Currently, `.postgrest["table_name"]` is used to access the Postgrest methods like the following:

```kotlin
val res = supabase.postgrest["table_name"].select()
```

It would be great if we instead have a `.from()` method to access the Postgrest methods like this:
```kotlin
val res = supabase.from("table_name").select()
```

**Comment by jan-tennert** [comment]
From methods are already available:
https://github.com/supabase-community/supabase-kt/blob/7ea195fa33664cd0091d18854609bb7173b06802/Postgrest/src/commonMain/kotlin/io/github/jan/supabase/postgrest/Postgrest.kt#L35-L46

**Comment by dshukertjr** [comment]
Yeah, but the syntax is different. Currently, you would have to call

```kotlin
supabase.postgrest.from("table")
```

The `from` method should be a member of the SupabaseClient so that it can be called like this:

```kotlin
supabase.from("table")
```

Alternatively, we could maybe rename `postgrest` to `from` to provide something like this:

```kotlin
supabase.from["table_name"].select()
```

**Comment by jan-tennert** [comment]
Right, we can definitly add an extension function to the SupabaseClient, the way its built right now is that the plugin methods (for Postgrest, Auth etc.) are under their respective namespace, but that should be fine

**Comment by dshukertjr** [comment]
Adding an extension method sounds like a great idea! Thanks @jan-tennert 💪
