### ISSUE TITLE
[Feature request]: Order and Limit SQL modifier

### ISSUE THREAD

**Issue by THEAccess** [supabase-community/supabase-kt#35]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Implement feature to [order](https://supabase.com/docs/reference/javascript/order) and [limit](https://supabase.com/docs/reference/javascript/range) SQL queries.

API could look like this:
```
client.postgrest["posts"].select { 
  order("created_at", Order.ASCENDING)
  limit(10)
}
```

### Usecase

For my, and presumably many other, use-cases this is an essential feature.

**Comment by jan-tennert** [comment]
Included in [0.7.0-beta-3](https://github.com/supabase-community/supabase-kt/releases/tag/0.7.0-beta-3). Let me know if there are any issues!
