### ISSUE TITLE
[Bug]: Documentation error -> confirm email

### ISSUE THREAD

**Issue by tschuehly** [supabase-community/supabase-kt#358]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

1.4.7

### Target(s)

JVM

### What happened? (include your code)

I think the documentation here is mixed up: https://supabase.com/docs/reference/kotlin/auth-signup

It says:

> Confirm email determines if users need to confirm their email address after signing up.
If Confirm email is enabled, the return value is null and you will be logged in instead.
If Confirm email is disabled, the return value is the user and you won't be logged in automatically.

I think the enabled and disabled should be switched. I tested it out in my project and when confirm email is enabled I get a user object -> 
![image](https://github.com/supabase-community/supabase-kt/assets/33346637/d3e22b12-7262-4501-8e9f-9b7d16841ec6)

**Comment by jan-tennert** [comment]
You are right, this is definitly wrong. Will fix that in a PR soon, thanks!

**Comment by tschuehly** [comment]
Do you have a timeline already for the 2.0 release? I have a big update for my spring boot starter coming and then I would wait on that!

**Comment by jan-tennert** [comment]
> Do you have a timeline already for the 2.0 release? I have a big update for my spring boot starter coming and then I would wait on that!

2.0 will probably be released before Supabase' Launch Week X so in 1-2 weeks depending on my time. There is already an alpha version available: [2.0.0-alpha-1](https://github.com/supabase-community/supabase-kt/releases/tag/2.0.0-alpha-1) with most of the features & breaking changes. Feel free to try out this alpha (feedback and bug reports welcome!), but I'd wait for a release canidate for anything more than testing.

**Comment by tschuehly** [comment]
Ok awesome, then I will definitely wait as I just switched from gotrue-kt to supabase-kt, and it wouldn't make much sense to release with 1.4.7. I will switch to the alpha and report!
