### ISSUE TITLE
[Feature request]: Easier way to listen to DB tables

### ISSUE THREAD

**Issue by devshubhdroid** [supabase-community/supabase-kt#369]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Just like Supabase Dart Client's `.stream()` method:

<img width="600" alt="Screenshot 2023-12-04 at 3 37 50 PM" src="https://github.com/supabase-community/supabase-kt/assets/145518017/c0b3c851-dcc9-42d7-96ad-0624cc6cb9b1">

The Kotlin client should also have a similar mechanism to easily start observing a table in the DB. Right now, I have to create a `callBackFlow`, manually read and emit the current DB value (using `supabaseClient.postgrest["my-table"].select()`) to initialise the flow, and only then am I able to observe further changes in the DB table.

I would like to be able to start observing the flow with some initial value. That would reduce a lot of boilerplate code for most users.

### Usecase

A very common usecase would be to observe DB tables that I believe all users of this library will do on a frequent basis.

**Comment by jan-tennert** [comment]
I'll make a PR soon, but won't include this in the 2.0.0 coming out this week/next week.

**Comment by shubhamsinghshubham777** [comment]
Hey.. same person here.. the other one is my account only.

> I'll make a PR soon, but won't include this in the 2.0.0 coming out this week/next week.

Sure, no issues, that works for me 👍🏻

**Comment by shubhamsinghshubham777** [comment]
One more request @jan-tennert , please let me know if I should create a separate feature request ticket for this.

Is it possible in the library's current state to do something like this?

```kotlin
fun observeUser(userId: String): Flow<List<User>> {
   return channel.postgresChangeFlow<PostgresAction>("public") {
       table = "users"
       filter("id", FilterOperator.EQ, userId)
   }
}
```

In essence, I want to be able to simply start observing a table without having to deal with all the separate `PostgresAction`s (i.e. DELETE, SELECT, INSERT, UPDATE). I just want a list of items (or a single item) that is kept updated with the latest DB changes. I will then only be concerned with collecting values and handling exceptions.

If it is not possible in the library's current state, do you think it's a good idea to implement it? And what would go into the efforts to make something like this possible?

**Comment by jan-tennert** [comment]
So the Realtime module doesn't save any data itself and I think that is the best solution for now because the general idea is that you just receive events when something changes and nothing more (like the js library).

**Comment by shubhamsinghshubham777** [comment]
> So the Realtime module doesn't save any data itself and I think that is the best solution for now because the general idea is that you just receive events when something changes and nothing more (like the js library).

It's not necessary to make changes in the `realtime` module directly. Maybe we could create an extension module called `extensions` and implement this (and other such experimental features) in that module for people to test out and give feedback on without having to hamper the original modules at all. What do you think?

**Comment by jan-tennert** [comment]
> > So the Realtime module doesn't save any data itself and I think that is the best solution for now because the general idea is that you just receive events when something changes and nothing more (like the js library).
> 
> It's not necessary to make changes in the `realtime` module directly. Maybe we could create an extension module called `extensions` and implement this (and other such experimental features) in that module for people to test out and give feedback on without having to hamper the original modules at all. What do you think?
> 
> Slowly and gradually once the features in the `extensions` module start getting more stable, they can be promoted into the appropriate modules (like `postgrest`, `realtime`, etc).

So what you are describing is essential that the library takes care of caching the data in memory, that may be a good usecase for a new [plugin](https://github.com/supabase-community/supabase-kt/tree/development/plugins).

**Comment by jan-tennert** [comment]
> > So what you are describing is essentially that the library takes care of caching the data in memory, that may be a good usecase for a new [plugin](https://github.com/supabase-community/supabase-kt/tree/development/plugins).
> 
> That is up to you (the library owner) to decide if it's good enough or not. It's totally understandable if it doesn't align with the goals of the library.
> 
> Being a consumer of the library, those were my 2 cents based on my own experiences that might save some time and effort for other consumers as well.
> 
> It's alright even if we decide to not move forward with the approach 👍🏻

The idea is perfect for a plugin, but I'd leave the main modules without these extras. We could have a plugin `Caching` (or some better name), which builds on top of Realtime & Postgrest, providing essentially the same methods but with the features you suggested

**Comment by shubhamsinghshubham777** [comment]
> > > So what you are describing is essentially that the library takes care of caching the data in memory, that may be a good usecase for a new [plugin](https://github.com/supabase-community/supabase-kt/tree/development/plugins).
> > 
> > 
> > That is up to you (the library owner) to decide if it's good enough or not. It's totally understandable if it doesn't align with the goals of the library.
> > Being a consumer of the library, those were my 2 cents based on my own experiences that might save some time and effort for other consumers as well.
> > It's alright even if we decide to not move forward with the approach 👍🏻
> 
> The idea is perfect for a plugin, but I'd leave the main modules without these extras. We could have a plugin `Caching` (or some better name), which builds on top of Realtime & Postgrest, providing essentially the same methods but with the features you suggested

That would be perfect! Thank you @jan-tennert 🙌🏻

**Comment by jan-tennert** [comment]
Hey

> > > > So what you are describing is essentially that the library takes care of caching the data in memory, that may be a good usecase for a new [plugin](https://github.com/supabase-community/supabase-kt/tree/development/plugins).
> > > 
> > > 
> > > That is up to you (the library owner) to decide if it's good enough or not. It's totally understandable if it doesn't align with the goals of the library.
> > > Being a consumer of the library, those were my 2 cents based on my own experiences that might save some time and effort for other consumers as well.
> > > It's alright even if we decide to not move forward with the approach 👍🏻
> > 
> > 
> > The idea is perfect for a plugin, but I'd leave the main modules without these extras. We could have a plugin `Caching` (or some better name), which builds on top of Realtime & Postgrest, providing essentially the same methods but with the features you suggested
> 
> That would be perfect! Thank you @jan-tennert 🙌🏻

Hey, so I'm going to scrap the idea of emitting the initial data in the `Realtime` module and include this functionality in the plugin instead. I got a preview working, currently looking like this (method & property names subject to change):
```kotlin
val table = client.postgrestCaching.from<Message>("messages")
val dataFlow: Flow<List<Message>> = table.listFlow(filter = "channel_id=eq.5") { it.id.toString() } //provide the primary key
dataFlow.collect {
    println(it)
}
//or for a single item
val dataFlow: Flow<Message> = table.dataFlow("id=eq.12") //provide a filter
dataFlow.collect { //Note that the flow closes when the item is deleted
    println(it)
}
```
What do you think about that?

**Comment by shubhamsinghshubham777** [comment]
> Hey
> 
> > > > > So what you are describing is essentially that the library takes care of caching the data in memory, that may be a good usecase for a new [plugin](https://github.com/supabase-community/supabase-kt/tree/development/plugins).
> > > > 
> > > > 
> > > > That is up to you (the library owner) to decide if it's good enough or not. It's totally understandable if it doesn't align with the goals of the library.
> > > > Being a consumer of the library, those were my 2 cents based on my own experiences that might save some time and effort for other consumers as well.
> > > > It's alright even if we decide to not move forward with the approach 👍🏻
> > > 
> > > 
> > > The idea is perfect for a plugin, but I'd leave the main modules without these extras. We could have a plugin `Caching` (or some better name), which builds on top of Realtime & Postgrest, providing essentially the same methods but with the features you suggested
> > 
> > That would be perfect! Thank you @jan-tennert 🙌🏻
> 
> Hey, so I'm going to scrap the idea of emitting the initial data in the `Realtime` module and include this functionality in the plugin instead. I got a preview working, currently looking like this (method & property names subject to change):
> ```kotlin
> val table = client.postgrestCaching.from<Message>("messages")
> val dataFlow: Flow<List<Message>> = table.listFlow(filter = "channel_id=eq.5") { it.id.toString() } //provide the primary key
> dataFlow.collect {
>     println(it)
> }
> //or for a single item
> val dataFlow: Flow<Message> = table.dataFlow("id=eq.12") //provide a filter
> dataFlow.collect { //Note that the flow closes when the item is deleted
>     println(it)
> }
> ```
> What do you think about that?

This looks very promising 🙌🏻 and very similar to Flutter's approach 👏🏻 and one concern I saw about this approach by the community was that there's no way to implement a more complex filter with 2 or more items. It only accepts a single filter.

Here's that issue:
https://github.com/supabase/realtime/issues/303

If this is somehow worked around in the Kotlin library, that would be very exciting!!

I also do accept that this is ideally an issue for the realtime module itself and not for us to fix. So it's perfectly fine if we're not able to work on it 👍🏻

**Comment by jan-tennert** [comment]
@shubhamsinghshubham777 Moving this thread to https://github.com/supabase-community/supabase-kt/discussions/379

**Comment by jan-tennert** [comment]
Drafted the syntax: #386. Let me know what you think!

**Comment by shubhamsinghshubham777** [comment]
> Drafted the syntax: #386. Let me know what you think!

Sure! Super excited to try it out.. thanks for the quick implementation 🌟

**Comment by shubhamsinghshubham777** [comment]
> Drafted the syntax: #386. Let me know what you think!

This looks very good to me @jan-tennert 🚀 

Although it's definitely not important for now, but If I were to nitpick, I would take a look at the syntax of `listFlow`:
```kotlin
inline fun listFlow(
        filter: String = "",
        crossinline primaryKey: (Data) -> String,
    )
```

Maybe instead of just asking for a `String` as filter, we can make the API a little easier for the users by writing it as follows:
```kotlin
inline fun listFlow(
        column: String,
        filterOperator: FilterOperator,
        filterValue: Any,
        crossinline primaryKey: (Data) -> String,
    )
```
or maybe even shorten it down to:
```kotlin
inline fun listFlow(
        filterOperation: FilterOperation,
        crossinline primaryKey: (Data) -> String,
    )
```
like you've already done before.

We can internally handle a few common usecases (like List `filterValue`(s)). For example, it's very common for people to use the `IN` filter operator and pass a List/Array of items. The new syntax would make it as simple as:

```kotlin
val messageFlow: Flow<List<Message>> = table.listFlow(
    filterOperation = FilterOperation(
        column = "id", 
        filterOperator = FilterOperator.IN, 
        filterValue = listOf("1", "2", "3"),
    ),
    primaryKey = Message::id
)
```

There's an `isIn` filter block in PostgrestFilterBuilder that we can reuse in `listFlow` implementation when we detect that `filterValue is List`:
https://github.com/supabase-community/supabase-kt/blob/dd66f129f50f6e5c9263a26e9f3ebb5652d3c043/Postgrest/src/commonMain/kotlin/io/github/jan/supabase/postgrest/query/filter/PostgrestFilterBuilder.kt#L133-L136

**Comment by jan-tennert** [comment]
@shubhamsinghshubham777 Good idea, I'm probably integrating this simpler filter syntax for the base Realtime module too. Besides that I also plan to provide the same caching for Realtime Presence data, so you don't have to care about presence joins & leaves and just get a list of connected users.

**Comment by shubhamsinghshubham777** [comment]
> @shubhamsinghshubham777 Good idea, I'm probably integrating this simpler filter syntax for the base Realtime module too. Besides that I also plan to provide the same caching for Realtime Presence data, so you don't have to care about presence joins & leaves and just get a list of connected users.

That's awesome @jan-tennert! I'm excited about it 🙌

**Comment by jollygreenegiant** [comment]
Also very excited about this - would make using and filtering realtime data so much easier!

**Comment by jan-tennert** [comment]
> Also very excited about this - would make using and filtering realtime data so much easier!

Great to hear that! I'm currently still thinking about the syntax. @shubhamsinghshubham777 I updated the PR again, but now these new methods are integrated within realtime because of some design issues with a completely new plugin. Let me know what you both think!

**Comment by shubhamsinghshubham777** [comment]
> > Also very excited about this - would make using and filtering realtime data so much easier!
> 
> Great to hear that! I'm currently still thinking about the syntax. @shubhamsinghshubham777 I updated the PR again, but now these new methods are integrated within realtime because of some design issues with a completely new plugin. Let me know what you both think!

Just skimmed through it and the current API seems good to me @jan-tennert ✅

**Comment by jollygreenegiant** [comment]
Also looks good to me, looking forward to using it!
