### ISSUE TITLE
[Question]: How to fetch a foreign table residing in a different schema

### ISSUE THREAD

**Issue by kibitheM** [supabase-community/supabase-kt#378]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

the example i found in the docs looks something like this; `
val country = supabase.postgrest["countries"]
            .select(
                columns = Columns.raw(
                                """
                                id,
                                name,
                                cities (
                                    id,
                                    name
                                )
                                """)
            )
            .decodeSingle<Country>()`

  cities here I assume is located in the same schema as the calling table... what changes do i make to this code if cities did not exixt in the same schema as the calling table. Any help will be greately appreciated. 

But i guese my biggest challenge is coming from the fact that i have still not yet figured out how to get a foreign table from the code example above found in the docs. 

This is the structure of my code;

I have saved this table as technicians in my database in a different schema called users
 `@Serializable
data class Technician(
    @SerialName("tech_id")
    val id: String,
    @SerialName("name")
    val name: String,
    @SerialName("phone")
    val phone: String,
    @SerialName("email")
    val email: String,)` 

I have an items table in the database with the `from `  column containing an id that i use as a foreign key that points to my technicians table in this form,

`@Serializable
data class Motherboard(
    @SerialName("brand") val brand: String,
    @SerialName("model") val model: String,
    @SerialName("from") val from: String,` )

Now i want to simply fetch the item together with the technician table and save it in something like the following data class;

`@Serializable
data class MyItem(
    @SerialName("id")
    val id: String,
    @SerialName("brand")
    val brand: String,
    @SerialName("model")
    val model: String,
    @SerialName("from")
    val from: Technician
)`

Everything i have done just doesn't seem to work. I have been on this for days. Please anyhelp/suggestions on how i can go about this will be highly appreciated. 

this is the code iam running to try and fetch the result

`
val myItem = supabase.postgrest["motherboard"]
            .select(
                columns = Columns.raw(
                                """
                                id,
                                brand,
                                model,
                                technicians (
                                    id,
                                    name,
                                    phone
                                )
                                """)
            )
            .decodeSingle<MyItem>()`

**Comment by jan-tennert** [comment]
I don't think the PostgREST/Supabase API even supports that. You might have to create a database function for that.

**Comment by kibitheM** [comment]
> I don't think the PostgREST/Supabase API even supports that. You might have to create a database function for that.

Thank you for the quick response. Looks like it might not be as straight  forward as I had imagined in kotlin. 

Just so that maybe my explanation wasn't  too ambiguous and not clear and before I close this...I was led to this by this tutorial video here  [https://www.youtube.com/watch?v=dU7GwCOgvNY&t=6300s&pp=ygVFTGVhcm4gU3VwYWJhc2UgKEZpcmViYXNlIEFsdGVybmF0aXZlKSDigJMgRnVsbCBUdXRvcmlhbCBmb3IgQmVnaW5uZXJz](url).

 At 1:40:15  where he explains relations in supabase and gives an example, with just a few lines of code and using less that 5 minutes, he achieves exactly what I wanted here, but he was using Javascript so I was not able to follow in my android project,  I figured maybe there was a similar approach in Kotlin. If maybe you can find time you might watch that part of the video, its just less than 5 minutes and maybe tell me if there is a way to achieve a similar result in Kotlin. Otherwise thank you for the continuous support.

**Comment by jan-tennert** [comment]
> > I don't think the PostgREST/Supabase API even supports that. You might have to create a database function for that.
> 
> Thank you for the quick response. Looks like it might not be as straight forward as I had imagined in kotlin.
> 
> Just so that maybe my explanation wasn't too ambiguous and not clear and before I close this...I was led to this by this tutorial video here https://youtu.be/dU7GwCOgvNY?t=6017
> 
> At 1:40:15 where he explains relations in supabase and gives an example, with just a few lines of code and using less that 5 minutes, he achieves exactly what I wanted here, but he was using Javascript so I was not able to follow in my android project, I figured maybe there was a similar approach in Kotlin. If maybe you can find time you might watch that part of the video, its just less than 5 minutes and maybe tell me if there is a way to achieve a similar result in Kotlin. Otherwise thank you for the continuous support.

Maybe I misunderstood your question but in the video he shows how to query table relations which are in the same schema and not how to query table relations with different schemas. The solution in the video can be translated to Kotlin as is:
```kotlin
val columns = Columns.raw("""
    *,
    clients (
        *
    )
""".trimIndent())
supabase.postgrest.from("orders").select(columns)

**Comment by kibitheM** [comment]
> In the video both tables are in the schema `public`

yes they are. I realize that that was the only way to fetch my foreign table alongside my referencing table. Also I figured from the video that he was querrying the json element directly without decoding it to any data class which is what worked for me. Thanks for the help.

**Comment by kibitheM** [comment]
> > > I don't think the PostgREST/Supabase API even supports that. You might have to create a database function for that.
> > 
> > 
> > Thank you for the quick response. Looks like it might not be as straight forward as I had imagined in kotlin.
> > Just so that maybe my explanation wasn't too ambiguous and not clear and before I close this...I was led to this by this tutorial video here https://youtu.be/dU7GwCOgvNY?t=6017
> > At 1:40:15 where he explains relations in supabase and gives an example, with just a few lines of code and using less that 5 minutes, he achieves exactly what I wanted here, but he was using Javascript so I was not able to follow in my android project, I figured maybe there was a similar approach in Kotlin. If maybe you can find time you might watch that part of the video, its just less than 5 minutes and maybe tell me if there is a way to achieve a similar result in Kotlin. Otherwise thank you for the continuous support.
> 
> Maybe I misunderstood your question but in the video he shows how to query table relations which are in the same schema and not how to query table relations with different schemas. The solution in the video can be translated to Kotlin as is:
> 
> ```kotlin
> val columns = Columns.raw("""
>     *,
>     clients (
>         *
>     )
> """.trimIndent())
> supabase.postgrest.from("orders").select(columns)
> ```

I also noticed this about this code which is what probably took the most of my time trying to figure out why it does not work; this wont work as it is without actually providing some indentations,
 > 
> ```kotlin
> val columns = Columns.raw("""
>     *,
>     clients (
>         *
>     )
> """.trimIndent())
> supabase.postgrest.from("orders").select(columns)
if i run it this way;  
> ```kotlin
> val columns = Columns.raw("""
>     *,
>     clients (
>         *
>     )
> """.trimIndent())
> supabase.postgrest.from("orders").select(columns)
> ```

I also noticed this about this code which is what probably took the most of my time trying to figure out why it does not work; this wont work as it is without actually providing some indentations,
but if i write with some indentation like below or use the regular string expression or if i remove the `.trimIndent()`  function  altogether (even if i included some indentation) it works.. so am so sure if the `.trimIndent()` function is necessarily as it wont work unless there are some actual indentations.
 > 
> ```kotlin
> val columns = Columns.raw("""


>     *,
>     clients (
>         *
>     )


> """.trimIndent())
> supabase.postgrest.from("orders").select(columns)

**Comment by kibitheM** [comment]
val columns = Columns.raw("""
    *,
    clients (
        *
    )
""".trimIndent())
supabase.postgrest.from("orders").select(columns)

I also noticed this about the above code, which probably took the most of my time trying to figure out what i was doing wrong. The code wont run unless you provide some actuall indentation. The code runs well if i use the regular double quotations, provided some actual indentation or even ommitted the <.trimIndent()> functions altogether (even if there are indentation in the code) so am not so sure if the `.trimIndent()` function here is necessary as it will throw some parsing errors unless you actually provide indentation. But that is from my side.
