### ISSUE TITLE
[Question]: How to disable logger for release build ?

### ISSUE THREAD

**Issue by florian-mlr** [supabase-community/supabase-kt#382]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Hello, is there a way to disable the logger for a release build ?

**Comment by jan-tennert** [comment]
Yes, see this [issue](https://github.com/supabase-community/supabase-kt/issues/242#issuecomment-1653955691).

**Comment by florian-mlr** [comment]
Thank you ! :)
