### ISSUE TITLE
[Bug]: Documentation update for retrieving data as CSV

### ISSUE THREAD

**Issue by cameron-greene-telus** [supabase-community/supabase-kt#391]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.0.0-rc-1

### Target(s)

All

### What happened? (include your code)

Supabase site just needs a documentation update - I looked for a way to make a PR against that but couldn't find if the docs are hosted publicly on Github.  Apologies if this isn't the right place to raise the issue - if the docs are hosted publicly I'm happy to make a PR if you could point me in the right direction.

In the below screenshot, from the Kotlin docs on the Supabase site, it shows that to retrieve CSV data, you need to use `explain()` when in fact it should say `csv()`

<img width="1277" alt="Screenshot 2023-12-19 at 1 30 40 PM" src="https://github.com/supabase-community/supabase-kt/assets/129769445/066136b8-6e77-4abe-82fb-87afdfd4432c">

### Steps To Reproduce (optional)

Link to docs: https://supabase.com/docs/reference/kotlin/db-csv

**Comment by jan-tennert** [comment]
Thank you for reporting this! The affected documentation part is here:
https://github.com/supabase/supabase/blob/52fbddb5f497e45628a1510b17423c65daac11f3/spec/supabase_kt_v2.yml#L2267C31-L2274

**Comment by cameron-greene-telus** [comment]
Thank you, I'll make a PR there!
