### ISSUE TITLE
[Bug]: ComposeAuth Google Sign In is triggering automatically on Android

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [supabase-community/supabase-kt#394]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.0.1

### Target(s)

Android

### What happened? (include your code)

I'm building a Compose Mobile app (Android & iOS) and on Android only using `composeAuth.rememberSignInWithGoogle` gets triggered automatically even without the user tapping on the button.

## Demo (Android)
The issue occurs on Android ❌ 

https://github.com/supabase-community/supabase-kt/assets/46640516/9e139a94-b6eb-4d28-b4c9-f2466430df93

## Demo (iOS)
The same code works absolutely fine on iOS ✅ 

https://github.com/supabase-community/supabase-kt/assets/46640516/a929a428-47f5-4b93-b83a-527a13cf4ab5

## Code
Here's my code for the auth screen
```kotlin
@Composable
fun AuthScreen(
    viewModel: AuthViewModel = koinViewModel(AuthViewModel::class),
    composeAuth: ComposeAuth = koinInject(),
    navigateToDashboard: () -> Unit,
) {
    val coroutineScope = rememberCoroutineScope()
    var googleLoginState by rememberSaveable(saver = GoogleLoginStateSaver) {
        mutableStateOf(UIState.Empty)
    }

    val googleAuthAction = composeAuth.rememberSignInWithGoogle(
        onResult = { result ->
            Logger.d { "Google auth result: $result" }
            when (result) {
                is NativeSignInResult.Success -> {
                    coroutineScope.launch {
                        // This code internally just calls supabaseClient.auth.signInWith(Google)
                        viewModel.loginWithGoogle()
                            .onFailure { tr -> googleLoginState = UIState.Error(tr) }
                            .onSuccess { googleLoginState = UIState.Data(Unit) }
                    }
                }

                is NativeSignInResult.ClosedByUser -> {
                    googleLoginState = UIState.Empty
                }

                is NativeSignInResult.NetworkError -> {
                    googleLoginState = UIState.Error(Exception(result.message))
                }

                is NativeSignInResult.Error -> {
                    googleLoginState = UIState.Error(Exception(result.message))
                }
            }
        },
    )

    AuthScreenContent(
        loginState = viewModel.loginState.collectAsStateWithLifecycle().value,
        onLogin = viewModel::login,
        signUpState = viewModel.signUpState.collectAsStateWithLifecycle().value,
        onSignUp = viewModel::signUp,
        googleLoginState = googleLoginState,
        onLoginWithGoogle = {
            // I tried commenting out both these lines of code as well, but the result was the same
            // suggesting that the issue has nothing to do with these lines of code
            googleLoginState = UIState.Loading
            googleAuthAction.startFlow()
        },
        navigateToDashboard = navigateToDashboard,
    )
}

@Composable
fun AuthScreenContent(
    loginState: UIState<Unit>,
    onLogin: (email: String, password: String) -> Unit,
    signUpState: UIState<Unit>,
    onSignUp: (email: String, password: String) -> Unit,
    googleLoginState: UIState<Unit>,
    onLoginWithGoogle: () -> Unit,
    isLoading: Boolean = loginState is UIState.Loading ||
            signUpState is UIState.Loading ||
            googleLoginState is UIState.Loading,
    navigateToDashboard: () -> Unit,
) {
    var email by rememberSaveable { mutableStateOf("") }
    var password by rememberSaveable { mutableStateOf("") }
    var repeatPassword by rememberSaveable { mutableStateOf("") }
    var isRegistering by rememberSaveable { mutableStateOf(false) }
    val snackbarState = remember { SnackbarHostState() }

    LaunchedEffect(loginState, signUpState) {
        if (loginState is UIState.Data || signUpState is UIState.Data) {
            navigateToDashboard()
        }

        if (loginState is UIState.Error || signUpState is UIState.Error) {
            snackbarState.showSnackbar(
                message = ((loginState as? UIState.Error) ?: (signUpState as? UIState.Error))
                    ?.throwable
                    ?.message
                    ?: "Unexpected error occurred!",
                duration = SnackbarDuration.Long,
            )
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text("Authentication")
                }
            )
        },
        snackbarHost = {
            SnackbarHost(hostState = snackbarState) { data -> Snackbar(data) }
        }
    ) { contentPadding ->
        Column(
            modifier = Modifier
                .padding(contentPadding)
                .padding(horizontal = 24.dp)
        ) {
            TextField(
                modifier = Modifier
                    .padding(top = 16.dp)
                    .fillMaxWidth(),
                value = email,
                enabled = !isLoading,
                onValueChange = { newValue -> email = newValue },
                placeholder = {
                    Text("E-mail")
                }
            )
            TextField(
                modifier = Modifier
                    .padding(top = 16.dp)
                    .fillMaxWidth(),
                value = password,
                enabled = !isLoading,
                onValueChange = { newValue -> password = newValue },
                placeholder = {
                    Text("Password")
                }
            )
            AnimatedVisibility(isRegistering) {
                TextField(
                    modifier = Modifier
                        .padding(top = 16.dp)
                        .fillMaxWidth(),
                    value = repeatPassword,
                    enabled = !isLoading,
                    onValueChange = { newValue -> repeatPassword = newValue },
                    placeholder = {
                        Text("Repeat Password")
                    }
                )
            }
            Button(
                modifier = Modifier
                    .align(Alignment.End)
                    .padding(top = 16.dp),
                enabled = !isLoading,
                onClick = {
                    if (isRegistering) {
                        onSignUp(email, password)
                    } else {
                        onLogin(email, password)
                    }
                }
            ) {
                Text(
                    when {
                        loginState is UIState.Loading -> "Loading..."
                        isRegistering -> "Sign up"
                        else -> "Sign in"
                    }
                )
            }
            TextButton(
                modifier = Modifier
                    .align(Alignment.End)
                    .padding(top = 8.dp),
                enabled = !isLoading,
                onClick = {
                    isRegistering = !isRegistering
                }
            ) {
                Text(
                    if (isRegistering) "Already have an account? Sign in"
                    else "Don't have an account? Sign up"
                )
            }
            Row(
                modifier = Modifier.padding(vertical = 16.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Divider(modifier = Modifier.weight(1f))
                Text(
                    modifier = Modifier.padding(horizontal = 16.dp),
                    text = "or"
                )
                Divider(modifier = Modifier.weight(1f))
            }
            Button(
                modifier = Modifier.align(Alignment.CenterHorizontally),
                onClick = onLoginWithGoogle
            ) {
                Text(
                    when (googleLoginState) {
                        is UIState.Loading -> "Loading..."
                        else -> "Sign in with Google"
                    }
                )
            }
        }
    }
}

private val GoogleLoginStateSaver
    get(): Saver<MutableState<UIState<Unit>>, Pair<String, String?>> =
        Saver(
            save = { state ->
                when (state.value) {
                    is UIState.Empty -> "empty" to ""
                    is UIState.Loading -> "loading" to ""
                    is UIState.Error -> "error" to (state.value as UIState.Error).throwable.message
                    is UIState.Data -> "data" to ""
                }
            },
            restore = { statePair ->
                mutableStateOf(
                    when (statePair.first) {
                        "empty" -> UIState.Empty
                        "loading" -> UIState.Loading
                        "error" -> UIState.Error(Exception(statePair.second))
                        "data" -> UIState.Data(Unit)
                        else -> UIState.Empty
                    }
                )
            }
        )

```

### Steps To Reproduce (optional)

On Android, simply put `composeAuth.rememberSignInWithGoogle()` in your Composable, no need to call `startFlow()` as well.

### Relevant log output (optional)

Sometimes I also get this output in my logs:
```
2023-12-23 12:32:38.632 17666-17706 CredManProvService      app.playtogether.android             I  GetCredentialResponse error returned from framework
```

And when I move forward with the Google Sign In, the app launches Google Chrome and the website shows me the following message:
```
{"code":400,"msg":"OAuth state is invalid: signature is invalid"}
```

**Comment by jan-tennert** [comment]
Thank you for reporting this! I'm publishing `2.0.2-dev` with a possible fix (~30min). Let me know if that works!

**Comment by shubhamsinghshubham777** [comment]
> Thank you for reporting this! I'm publishing `2.0.2-dev` with a possible fix (~30min). Let me know if that works!

Thank you @jan-tennert, it's working perfectly fine now ✅ 

https://github.com/supabase-community/supabase-kt/assets/46640516/b97a4159-de19-4a6b-bd17-6cb9dc5036d0

**Comment by jan-tennert** [comment]
Great! One question: Is there a reason you call `supabase.auth.signInWith(Google)` on these lines:
```kotlin
                is NativeSignInResult.Success -> {
                    coroutineScope.launch {
                        // This code internally just calls supabaseClient.auth.signInWith(Google)
                        viewModel.loginWithGoogle()
                            .onFailure { tr -> googleLoginState = UIState.Error(tr) }
                            .onSuccess { googleLoginState = UIState.Data(Unit) }
                    }
                }
```
You already get logged in before the success result is emitted to the callback.

**Comment by shubhamsinghshubham777** [comment]
> Great! One question: Is there a reason you call `supabase.auth.signInWith(Google)` in these lines:
> 
> ```kotlin
>                 is NativeSignInResult.Success -> {
>                     coroutineScope.launch {
>                         // This code internally just calls supabaseClient.auth.signInWith(Google)
>                         viewModel.loginWithGoogle()
>                             .onFailure { tr -> googleLoginState = UIState.Error(tr) }
>                             .onSuccess { googleLoginState = UIState.Data(Unit) }
>                     }
>                 }
> ```
> 
> You already get logged in before the success result is emitted to the callback.

Oh okay, I believe I didn't read the documentation carefully. In that case, even better, I can remove that line of code 👍🏻

**Comment by jan-tennert** [comment]
> > Great! One question: Is there a reason you call `supabase.auth.signInWith(Google)` in these lines:
> > ```kotlin
> >                 is NativeSignInResult.Success -> {
> >                     coroutineScope.launch {
> >                         // This code internally just calls supabaseClient.auth.signInWith(Google)
> >                         viewModel.loginWithGoogle()
> >                             .onFailure { tr -> googleLoginState = UIState.Error(tr) }
> >                             .onSuccess { googleLoginState = UIState.Data(Unit) }
> >                     }
> >                 }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You already get logged in before the success result is emitted to the callback.
> 
> Oh okay, I believe I didn't read the documentation carefully. In that case, even better, I can remove that line of code 👍🏻

Yes, so Compose Auth automatically signs in with the ID Token received in the Native Auth flow. (So you don't have to do anything) This result is just to let you know that it worked.

**Comment by shubhamsinghshubham777** [comment]
> > > Great! One question: Is there a reason you call `supabase.auth.signInWith(Google)` in these lines:
> > > ```kotlin
> > >                 is NativeSignInResult.Success -> {
> > >                     coroutineScope.launch {
> > >                         // This code internally just calls supabaseClient.auth.signInWith(Google)
> > >                         viewModel.loginWithGoogle()
> > >                             .onFailure { tr -> googleLoginState = UIState.Error(tr) }
> > >                             .onSuccess { googleLoginState = UIState.Data(Unit) }
> > >                     }
> > >                 }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You already get logged in before the success result is emitted to the callback.
> > 
> > Oh okay, I believe I didn't read the documentation carefully. In that case, even better, I can remove that line of code 👍🏻
> 
> Yes, so Compose Auth automatically signs in with the ID Token received in the Native Auth flow. (So you don't have to do anything) This result is just to let you know that it worked.

That's awesome!! The library under the hood is doing a lot more than I thought 😂 Many thanks for your hard work 🙌

**Comment by Deorigami** [comment]
hi @shubhamsinghshubham777 .. would you mind sharing your project shown here? i have difficulties Login with Google on ios

https://github.com/supabase-community/supabase-kt/assets/70903634/b18519bf-f6bf-4729-83a5-192845e76f5e

**Comment by shubhamsinghshubham777** [comment]
> hi @shubhamsinghshubham777 .. would you mind sharing your project shown here? i have difficulties Login with Google on ios
> 
>  Screen.Recording.2024-05-08.at.11.22.40.mov

Apologies @Deorigami, but that was just a sample project I worked on quite a while ago. I don't have it anymore :(

**Comment by Deorigami** [comment]
Im using KMPAuth library, pretty easy to set up,
Then after that you can use supabase.auth.signInWith TokenID

**Comment by Deorigami** [comment]
I think your bug has been resolved .. try to upgrade you supabase version to newer, i was having this issue too

**Comment by Deorigami** [comment]
Ahh thank you

**Comment by Frozair** [comment]
> ```kotlin
> ComposeAuth
> ```

👋🏾 hey @Deorigami did you ever figured out the fix to login with Google on iOS? I'm currently experiencing this exact issue. Thanks!

**Comment by Frozair** [comment]
> hi @shubhamsinghshubham777 .. would you mind sharing your project shown here? i have difficulties Login with Google on ios
> 
>  Screen.Recording.2024-05-08.at.11.22.40.mov

👋🏾 hey @Deorigami did you ever figured out the fix to login with Google on iOS? I'm currently experiencing this exact issue. Thanks!
