### ISSUE TITLE
[Bug]: Full text search returns error when following docs

### ISSUE THREAD

**Issue by jollygreenegiant** [supabase-community/supabase-kt#407]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.0.2

### Target(s)

Android

### What happened? (include your code)

I'm attempting full text search on my database, and I'm getting the following error:

`io.github.jan.supabase.exceptions.BadRequestRestException: Unexpected param or filter missing operator (Failed to parse [("display_name","phraseto(english).Cameron")])`

Here is the Kotlin code:
```
supabaseClient.from("users")
    .select(columns = Columns.list("display_name")) {
        filter {
            textSearch(
                column = "display_name",
                query = query,
                config = "english",
                textSearchType = TextSearchType.PHRASETO
            )
        }
        limit(50)
    }
```

and the generated URL:
`https://<project-id>.supabase.co/rest/v1/users?display_name=phraseto%28english%29.Cameron&limit=50&select=display_name`

I also tried without the `limit()` call, and got the same error.  Not sure what might be going on here, if there's a bug or if [the documentation](https://supabase.com/docs/reference/kotlin/textsearch) is just incorrect

**Comment by kibitheM** [comment]
I have this exact problem right now. I have just opened an issue prior to seeing this. Waiting any help on this.

**Comment by jan-tennert** [comment]
Thank you for reporting this! Seems like there was a problem internally. Publishing `2.0.3-dev` (~30min) with the fix. Let me know if both of your issues have been fixed!

**Comment by jollygreenegiant** [comment]
I won't be able to check until tomorrow but I will let you know, thank you for looking into it so quickly!

**Comment by kibitheM** [comment]
> Thank you for reporting this! Seems like there was a problem internally. Publishing `2.0.3-dev` (~30min) with the fix. Let me know if both of your issues have been fixed!

Thank you. Iam currently figuring out how to adapt the new changes in the PR to my project, specifically how to get the `2.0.3-dev` . As soon as i try this i will let you know.

**Comment by kibitheM** [comment]
> 2.0.3-dev



> Thank you for reporting this! Seems like there was a problem internally. Publishing `2.0.3-dev` (~30min) with the fix. Let me know if both of your issues have been fixed!

Works like a charm!! Problem fixed for me. Thank you very much.

**Comment by jollygreenegiant** [comment]
Also fixed my issue, thank you!
