### ISSUE TITLE
The correct way to perform a full Text Search in Kotlin[Question]: 

### ISSUE THREAD

**Issue by kibitheM** [supabase-community/supabase-kt#408]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

The example in the docs reads something like this;  
>supabase.from("quotes").select(columns = Columns.list("catchphrase")) {
    >filter {
       >textSearch(column = "catchphrase", query = "'fat' & 'cat'", config = "english", type = TextSearchType.WEBSEARCH)
    >}
>}

After implementing it in kotlin this way ;
 >client.postgrest[myTable]
            >.select(
>columns = Columns.list("brand"
>){
                >textSearch(
                    >column = "brand",
                    >query = "Tecno",
                    >textSearchType = TextSearchType.WEBSEARCH
                >)
            >} ,

iam getting this error;  `failed to parse filter (websearch.Tecno)" (line 1, column 1)`

**Comment by jan-tennert** [comment]
Closing this issue, seems to be the same problem as #407
