### ISSUE TITLE
[Bug]: Serializer for class 'Config' is not found

### ISSUE THREAD

**Issue by burntcookie90** [supabase-community/supabase-kt#42]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

Attempting to use email signup in a kotlin/js module with the following code: 

```kotlin
		val result = supabaseClient.gotrue.signUpWith(Email) {
			this.email = username
			this.password = password
		}

		console.log(result)
```

which i expect to trigger an email signup on supabase. However it fails in the browser.

### Platform(s)

Web

### Relevant log output

```shell
Object { message: "Serializer for class 'Config' is not found.\nMark the class as @Serializable or provide the serializer explicitly.\nOn Kotlin/JS explicitly declared serializer should be used for interfaces and enums without @Serializable annotation", cause: undefined, name: "si", stack: "Bl@http://127.0.0.1:8080/static/frontend.js:75:490599\nai@http://127.0.0.1:8080/static/frontend.js:75:592296\n3645/i</_i/i<@http://127.0.0.1:8080/static/frontend.js:75:594117\n_i@http://127.0.0.1:8080/static/frontend.js:75:594360\n158/r/mr.prototype.j4t@http://127.0.0.1:8080/static/frontend.js:75:1270651\n158/r/mr.prototype.z4s@http://127.0.0.1:8080/static/frontend.js:75:1270752\n158/r/lr.prototype.ui@http://127.0.0.1:8080/static/frontend.js:75:1267732\n158/r/mr.prototype.u4n@http://127.0.0.1:8080/static/frontend.js:75:1285661\n158/r/Sn.prototype.b4i@http://127.0.0.1:8080/static/frontend.js:75:1260018\n158/r/Sn.prototype.c4i@http://127.0.0.1:8080/static/frontend.js:75:1284963\n1060/r/$r.prototype.ui@http://127.0.0.1:8080/static/frontend.js:75:1203331\n1060/r/gr.prototype.y4u@http://127.0.0.1:8080/static/frontend.js:75:1203714\n1060/r/yi.prototype.ui@http://127.0.0.1:8080/static/frontend.js:75:1213873\n1060/r/yi.prototype.h1i@http://127.0.0.1:8080/static/frontend.js:75:1213596\ni@http://127.0.0.1:8080/static/frontend.js:75:1187330\n8744/n/wp.prototype.ui@http://127.0.0.1:8080/static/frontend.js:75:563546\n8744/n/mp.prototype.ti@http://127.0.0.1:8080/static/frontend.js:75:562805\n8744/n/mp.prototype.c4@http://127.0.0.1:8080/static/frontend.js:75:563063\n7646/r/oa.prototype.tp@http://127.0.0.1:8080/static/frontend.js:75:820984\n7646/r/Wa.prototype.f19@http://127.0.0.1:8080/static/frontend.js:75:825087\n7646/r/Ga.prototype.g19/<@http://127.0.0.1:8080/static/frontend.js:75:825853\npromise callback*7646/r/Ga.prototype.g19@http://127.0.0.1:8080/static/frontend.js:75:825819\n7646/r/Wa.prototype.i19@http://127.0.0.1:8080/static/frontend.js:75:824967\n7646/r/Ka.prototype.uq@http://127.0.0.1:8080/static/frontend.js:75:825556\n7646/r/za.prototype.uq@http://127.0.0.1:8080/static/frontend.js:75:823335\nta@http://127.0.0.1:8080/static/frontend.js:75:760901\n7646/r/ma/<@http://127.0.0.1:8080/static/frontend.js:75:762646\nma@http://127.0.0.1:8080/static/frontend.js:75:762736\n7646/r/Gn.prototype.bl@http://127.0.0.1:8080/static/frontend.js:75:783241\n7646/r/He.prototype.yk@http://127.0.0.1:8080/static/frontend.js:75:772459\n7646/r/t.$_$.m/<@http://127.0.0.1:8080/static/frontend.js:75:831141\n7646/r/t.$_$.m@http://127.0.0.1:8080/static/frontend.js:75:831153\n1060/r/di/</</n.onClick@http://127.0.0.1:8080/static/frontend.js:75:1187256\nPt@http://127.0.0.1:8080/static/frontend.js:75:281161\nFt@http://127.0.0.1:8080/static/frontend.js:75:281315\n3936/Mr/<@http://127.0.0.1:8080/static/frontend.js:75:301175\nMr@http://127.0.0.1:8080/static/frontend.js:75:301269\nzr@http://127.0.0.1:8080/static/frontend.js:75:301685\n3936/Zr/<@http://127.0.0.1:8080/static/frontend.js:75:307113\nll@http://127.0.0.1:8080/static/frontend.js:75:370407\nIt@http://127.0.0.1:8080/static/frontend.js:75:280294\nZr@http://127.0.0.1:8080/static/frontend.js:75:302977\nVe@http://127.0.0.1:8080/static/frontend.js:75:287394\nBe@http://127.0.0.1:8080/static/frontend.js:75:287176\nEventListener.handleEvent*Hr@http://127.0.0.1:8080/static/frontend.js:75:302482\nLr@http://127.0.0.1:8080/static/frontend.js:75:301881\n3936/Ur/<@http://127.0.0.1:8080/static/frontend.js:75:302047\nUr@http://127.0.0.1:8080/static/frontend.js:75:301991\n3936/e.createRoot@http://127.0.0.1:8080/static/frontend.js:75:391896\n1060/r/<@http://127.0.0.1:8080/static/frontend.js:75:1232697\nr@http://127.0.0.1:8080/static/frontend.js:75:1232843\n1060@http://127.0.0.1:8080/static/frontend.js:75:1232852\n__webpack_require__@http://127.0.0.1:8080/static/frontend.js:75:1295711\n@http://127.0.0.1:8080/static/frontend.js:75:1296908\n@http://127.0.0.1:8080/static/frontend.js:75:1296943\n@http://127.0.0.1:8080/static/frontend.js:2:193\n@http://127.0.0.1:8080/static/frontend.js:2:197\n" }
CoroutineExceptionHandlerImpl.kt:11:4
```

**Comment by jan-tennert** [comment]
But you are using the latest version right? Just created a small K/JS browser application with supabase-kt and signing up works

**Comment by burntcookie90** [comment]
Yes, I am using 0.7.3 and verified that the `kotlinx-serialization` plugin and runtime dependency were both on the project, but its still occurring. 

```kts
kotlin("multiplatform") version "1.7.21"
kotlin("plugin.serialization") version "1.7.21"
```

```kts
implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1")
implementation("io.github.jan-tennert.supabase:gotrue-kt:0.7.3")
```

**Comment by jan-tennert** [comment]
I have an idea what could cause this, but can't test it, as I'm not getting this error. Do you have like a minimal repository for me to reproduce this problem?

**Comment by burntcookie90** [comment]
I dont at the moment, I could fork and use the project locally if we wanted to test stuff. Or i could try and put together a minimal repro project.

**Comment by jan-tennert** [comment]
Just published 0.7.4-alpha with some changes, let me know if that fixed it!

**Comment by burntcookie90** [comment]
No luck, same error. I dont see the changes in repo, could you share what you're attempting?

**Comment by jan-tennert** [comment]
Just pushed the changes. The 'Config' class in this context should have the corresponding Serializable annotation. Are you sure the exception is not from somewhere else? The only thing you could try is to make a small repo reproducing the problem

**Comment by burntcookie90** [comment]
Yeah, I commented out the callsite to `supabaseClient.goTrue.signUpWith(Email)` and there's no error. I'll try and get some useful pared down version of this project to see if I can repro, this is quite odd.

**Comment by jan-tennert** [comment]
Hmm, yea that is weird. You can also try to call `Email.encodeCredentials { }` just to see if that's the problem, as this is responsible for serializing the config class

**Comment by burntcookie90** [comment]
Yeah, that also errors with the same message.

**Comment by burntcookie90** [comment]
It happens when using `signUpWith(Phone)` as well, so there's just something odd with the way the serializer setup works I think. Ill try and follow up later.

**Comment by jan-tennert** [comment]
> Hmm, yea that is weird. You can also try to call `Email.encodeCredentials { }` just to see if that's the problem, as this is responsible for serializing the config class

encodeCredentials just calls [supabaseJson.encodeToString(Config())](https://github.com/supabase-community/supabase-kt/blob/b4bd01a033b027b98fb40e8c7fdd29e7945c47b7/GoTrue/src/commonMain/kotlin/io/github/jan/supabase/gotrue/providers/builtin/Email.kt#L33)

and supabaseJson is just
```kotlin
val supabaseJson = Json {
    ignoreUnknownKeys = true
    encodeDefaults = false
}
```

**Comment by burntcookie90** [comment]
```
val supabaseJson = Json {
			ignoreUnknownKeys = true
			encodeDefaults = false
		}
		val config = Email.Config().apply {
			email = username
			this.password = password
		}

		supabaseJson.encodeToString(config)
```

fails with the same error. I wonder if there's something stripping the serializer somehow?

**Comment by jan-tennert** [comment]
looks like it. Can you call `Email.Config.serializer()`? I mean I have no idea, do you have something which minimizes the target bundle or something like that?

**Comment by burntcookie90** [comment]
```kotlin
val supabaseJson = Json {
	ignoreUnknownKeys = true
	encodeDefaults = false
}
val config = Email.Config().apply {
	email = username
	this.password = password
}

val serializer = Email.Config.
console.log(supabaseJson.encodeToString(serializer, config))
```

works to serialize the `config` so thats even more odd.

**Comment by burntcookie90** [comment]
And, sorry, no I do not have any minimization occurring. This is effectively a default kotlin multiplatform project using react/webpack/ktor

**Comment by jan-tennert** [comment]
Tthe only workaround which might work is to specify the Serializer in these methods manually, but it still would be good to know what's causing this. Maybe it's really a gradle/compilation problem, but can't reproduce this error

**Comment by burntcookie90** [comment]
Yeah, I wish I could quickly make a repro project. I’ll see what I can do this weekend.

**Comment by burntcookie90** [comment]
Ok, I realized i should start super minimal and went ahead and tried and repro'd with this project: https://github.com/burntcookie90/supabase-kt-repro

You should be able to `run` and click the "Sign Up" button and see the error in the console logs (I am on Firefox 108).

**Comment by jan-tennert** [comment]
yep receiving the same error, but it's for all classes. Just added a simple serializable class:
```kotlin
@Serializable
data class Test(val name: String = "test")
```
In Welcome.kt and added it to the onClick listener
```kotlin
Json.encodeToString(Test())
```
And same error.

**Comment by jan-tennert** [comment]
Okay I just changed the Kotlin version in the plugins to 1.8.0 and everything works now

**Comment by burntcookie90** [comment]
Wow, well thats the easiest way to fix something! Can confirm that this is no longer an issue, thank you for debugging.
