### ISSUE TITLE
[Feature request]: Expand Coil support to multiplatform

### ISSUE THREAD

**Issue by devshubhdroid** [supabase-community/supabase-kt#425]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Now that [Coil supports Compose Multiplatform](https://github.com/coil-kt/coil/blob/3.x/docs/upgrading_to_coil3.md), it would be exciting to see [Supabase-kt's Coil Integration](https://github.com/supabase-community/supabase-kt/tree/master/plugins/CoilIntegration) expand its platform support from just Android to Multiplatform 👍🏼 

Here's the new coil dependency:
```gradle
implementation("io.coil-kt.coil3:coil-compose:3.0.0-alpha01")
```

### Usecase

Supporting more platforms should attract more users to use [Supabase-kt's Coil Integration module](https://github.com/supabase-community/supabase-kt/tree/master/plugins/CoilIntegration) 👍🏼

**Comment by jan-tennert** [comment]
Thank you for this request! I already planned to support Coil 3, but will wait until it's in a more stable state!

**Comment by jan-tennert** [comment]
I've decided to add Coil 3 in a separate module and leave the Coil 2 module as is.
It will be introduced in version 2.7.0 alongside WASM/Ktor 3 support.
