### ISSUE TITLE
[Bug]: Getting data is not working on safari 16 or lower

### ISSUE THREAD

**Issue by MohamedRejeb** [supabase-community/supabase-kt#441]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.0.4

### Target(s)

Web

### What happened? (include your code)

Getting data is failing and I'm getting this error in the logs:
```
SyntaxError: Invalid regular expression: invalid group specifier name
RegExp@[native code]
Regex@
Regex_init_$Init$_0@
_init_properties_Utils_kt__jo07cx@
mapToFirstValue@
@
@
@
@
@
@
@
@
promiseReactionJob@[native code]
```

When I remove the `select` method call the error is no longer printing and also I see that this `mapToFirstValue` function is used inside the `select` method.

The error is happening only on safari 16.x or lower I guess (tested on safari 16.1 and 16.2)
It's not happening on safari 17.x

**Comment by jan-tennert** [comment]
I think it might be this regex:
https://github.com/supabase-community/supabase-kt/blob/705dba27cc88bd591bc7f02fa49b9403648a513a/Postgrest/src/commonMain/kotlin/io/github/jan/supabase/postgrest/Utils.kt#L10-L18
Which is used to convert property names to column names in your filter when using the property syntax: `User::createdAt eq value` -> `eq("created_at", value)`.
Can you try to change the property `propertyConversionMethod` in the Postgrest config to `PropertyConversionMethod.NONE`, to check if it is this regex? (By this default the regex approach is used)

**Comment by MohamedRejeb** [comment]
I changed the property `propertyConversionMethod` in the Postgrest config to `PropertyConversionMethod.NONE` but I'm still getting the same error.

**Comment by MohamedRejeb** [comment]
I tied the above function `camelToSnakeCase` in Safari 16.X and it's causing the issue.
