### ISSUE TITLE
[Question]: How to build the sdk locally and test with my Kotlin Multiplatform app

### ISSUE THREAD

**Issue by Vaibhav-214** [supabase-community/supabase-kt#446]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

I am facing some issue with apple native sign in in my kotlin/compose multplatform app. I am using modules auth and compose-auth for that (there are other modules too like postgres).I want to insert some log statements to see where the issue is occuring before raising an issue here, since problem could be on my side.

**I need to know how can I use the supabase-sdk locally in my project, what would I need to do?**

what I tried?

1.Gpt told me to build a .aar file, I did that using "gradle assemble", I got the aar file and put that in "RootFolder/composeApp/src/androidmain/libs/supbase-kt-debug.aar"

2.put this in androidMain in build.gradle.kts -implementation(files("libs/supabase-kt-debug.aar"))

It obviously gave error, and it should have I guess, because this is not an android project and the dependency should be something I should be able to put on common section

Please help me , I am asking this instead of just raising an issue because I would like to contribute to this sdk in future, so this would be a good knowledge for me to test it locally on my Kotlin Multiplatform project

**Comment by jan-tennert** [comment]
You can just publish the library to maven local, and then use it as a normal library. In order to do that, 
- Comment out this line:
https://github.com/supabase-community/supabase-kt/blob/74cb87538cc51e6b13977f1b58908248c9261e5d/build.gradle.kts#L44
- Change the version to something different like `2.1.0-local-1` (change this as you want):
https://github.com/supabase-community/supabase-kt/blob/74cb87538cc51e6b13977f1b58908248c9261e5d/gradle.properties#L13
- Run `gradlew publishToMavenLocal`, wait for it to finish
- Use the locally published library exactly like you'd add the "real" library, just with your defined version. Also make sure to add the `mavenLocal()` repository for your dependencies (within your app)

If you just have a small change which doesn't require a full app to test, you can create a "test" module within the cloned supabase-kt project and just make a small jvm module or something like that and run it. You can add the modules (e.g. realtime) via `implementation(project(":realtime-kt"))`. 

Remember to reverse such changes when making a PR, the "test" module is in the gitignore file and always added in the settings.gradle.kts file, so you can always have that there.

**Comment by Vaibhav-214** [comment]
thanks a lot @jan-tennert , I was able to run it locally, I have found where exactly is the issue(still not sure if something wrong on my side though).
I will raise a seperate issue now that  i have more idea and you can close this

**Comment by Vaibhav-214** [comment]
thanks @jan-tennert , I was able to run it locally and have found out where the issue is happening, still not sure if it is something on my end but here is what I found

and Should I create a new issue with these details?

I have added the code and the logs output below

I put some logs in  the method "rememberSignInWithApple" and here are my obervations

1.The method runs as soon as the app opens, without user doing anything, although the code inside launched effect doesnt runs and directly the last log is printed

2. Then when I click on the sign in button all the statments that are marked "executed" run in an instant without me doing anything

3.Nothing is executed after I click on signIn in the apple native signin ui

4."nonce" and the "user" properties are showing null

5.All properties inside the config.loginConfig["apple"] object are null, even though object is not null

6.IMPORTANT -looks like authorizationController() method  is never executed, I had put some logs in that method too but nothing was printed and also the print statement "I am here 10" was not printed


```kotlin
@Composable
actual fun ComposeAuth.rememberSignInWithApple(
    onResult: (NativeSignInResult) -> Unit,
    fallback: suspend () -> Unit
): NativeSignInState {

    val state = remember { NativeSignInState() }
    val scope = rememberCoroutineScope()

    LaunchedEffect(key1 = state.started) {
        println("I am inside launched effect")//executed
        if (state.started) {
            println("I am inside first if block , which means state is set to started")//executed

            println("${config.loginConfig["apple"]}")
            if (config.loginConfig["apple"] == null) {
                println("I am inside 2nd if block , which shouldn't happen")// NOT EXECUTED
                fallback.invoke()
                state.reset()
                return@LaunchedEffect
            }

            val appleIDProvider = ASAuthorizationAppleIDProvider()
            val request = appleIDProvider.createRequest().apply {
                requestedScopes = listOf(ASAuthorizationScopeFullName, ASAuthorizationScopeEmail)
                nonce = (config.loginConfig["apple"] as? AppleLoginConfig)?.nonce
                println("loginConfig - ${config.loginConfig["apple"]}  server client id - ${config.loginConfig["apple"]?.serverClientId}")//executed
                println("requested scopes - $requestedScopes , nounce - $nonce  ")//executed
            }
            println("request - $request - user - ${request.user}")//executed


            val controller = ASAuthorizationController(listOf(request)).apply {
                println("i m inside controller ${this.delegate}")//executed
                delegate = authorizationController(scope) {
                    println(" I m here 10")// **** NOT EXECUTED ****
                    onResult.invoke(it)
                    state.reset()
                }

                println("I am here in the controller") // EXECUTED

                presentationContextProvider = presentationAnchor()


            }
            println("controller - $controller - delegate ${controller.delegate}") // EXECUTED
            println(" i am on my way further 3") // EXECUTED
            controller.performRequests()

            println("I am after the perfrom Reuest function")

        }
    }
    println("I am outside launched effect and state is $state.") //Executed first

    return state
}
```

##output

`
I am outside launched effect and state is io.github.jan.supabase.compose.auth.composable.NativeSignInState@8a32be0.
I am inside launched effect
starting apple auth
I am outside launched effect and state is io.github.jan.supabase.compose.auth.composable.NativeSignInState@8a32be0.
I am inside launched effect
I am inside first if block , which means state is set to started
AppleLoginConfig(serverClientId=, nonce=null, extraData=null)
loginConfig - AppleLoginConfig(serverClientId=, nonce=null, extraData=null)  server client id - 
requested scopes - [full_name, email] , nounce - null  
request - <ASAuthorizationAppleIDRequest: 0x60000213c820> - user - null
i m inside controller null
I am here in the controller
controller - <ASAuthorizationController: 0x60000390a2f0> - delegate <ComposeApp_kobjc5: 0x600000260740>
 i am on my way further 3
I am after the perfrom Reuest function
`

**Comment by jan-tennert** [comment]
Yes, I created a new issue for you: #447
