### ISSUE TITLE
[Bug]: Create User parameter is not working in signInWith(OTP)/signUpWith(OTP)

### ISSUE THREAD

**Issue by Vaibhav-214** [supabase-community/supabase-kt#450]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.1.1

### Target(s)

cheked only for ios, but its common code

### What happened? (include your code)

I am trying to login/signUp user using email and otp

NOTE - Since there is a parameter to createUser if user doesn't exists , creating two methods signInWith and signUpWith when both of them take same parameters is confusing, only difference is signUpWith returns user.

 The code I used for getting an otp by providing email
 ##  Case 1
Using type INVITE
 ```kotlin
supabaseClient.auth.signInWith(OTP) {
                this.email = email
                this.createUser = true //same result even if I keep this to false in this case
            }
            
//The method I used to provide otp and login/signIn 
            supabaseClient.auth.verifyEmailOtp(
                    type = OtpType.Email.INVITE,
                    email = it,
                    token = otp
                )
```

I soon as I call the verifyEmailAnOtp method I get the exception

```
UnauthorizedRestException: Token has expired or is invalid
```

## Case 2
 - where I change the method with signUpWith, and tried with both createUser = true and createuser = false
 
```kotlin
supabaseClient.auth.signUpWith(OTP) {
                this.email = email
                this.createUser = false // same with true too
            }

supabaseClient.auth.verifyEmailOtp(
                    type = OtpType.Email.INVITE,
                    email = it,
                    token = otp
                )
```

In above case too I get same exception

In all the above scenario's I tried 2 types of emails 
- 1.Already exists in auth table- DOESN'T Works
-  2.Fresh email - DOESN'T WORKS

## Case 3
- I changed the type in verifyEmailOtp to OtpType.Email.MAGICLINK

```kotlin
supabaseClient.auth.signUpWith(OTP) {
                this.email = email
                this.createUser = true
            }

//for verification
supabaseClient.auth.verifyEmailOtp(
                    type = OtpType.Email.MAGIC_LINK,
                    email = it,
                    token = otp
                )

```

In above case when
- I use already authenticated user email - WORKS
- When I use fresh email  - DOESN't WORKS

## Case 4
- I change the type to OtpType.Email.SIGNUP

```kotlin
supabaseClient.auth.signUpWith(OTP) { //same with signInWith
                this.email = email
                this.createUser = true
            }

//for verification
supabaseClient.auth.verifyEmailOtp(
                    type = OtpType.Email.SIGNUP,
                    email = it,
                    token = otp
                )

```
In above case when
- User already exists - DOESN'T WORKS-- same exception
- User doesnt exists - WORKS

**Now I haven't tried some cases yet, but the idea is the createUser parameter seems to be not effective
I need just one method which will authenticate user if it already exists and if doesn't exists it will create one**

Right now it seems I will have to use a combination of case 3 and case 4 somehow, maybe try one way if exception occurs try another way (i.e. 2 calls)

**Comment by jan-tennert** [comment]
Thank you for reporting this. `signUpWith(OTP)` and `signInWith(OTP)` do the exact same thing, doesn't matter which one you call. The type you verify the OTP with is the problem, it seems like there is a type missing. The `SIGNUP` and `MAGIC_LINK` types are deprecated and `EMAIL` should be used instead (but this one doesn't exist), so I'm publishing a fix including this new type and deprecating the other types.
Note that the `INVITE` type is for sending invites via the admin interface.
