### ISSUE TITLE
[Bug]: On upload file mime-type always application/octet-stream

### ISSUE THREAD

**Issue by denchic45** [supabase-community/supabase-kt#46]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

```kotlin
storage["main"].upload(
    "Folder/data.txt",
    File("data.txt").apply { writeText("Example text") }.readBytes()
)
```
![image](https://user-images.githubusercontent.com/80104523/212630783-0ce344ec-70e1-4957-aadb-762f52ec741d.png)

I think the optimal solution is to use ContentType.defaultForFilePath(String)
```kotlin
append(HttpHeaders.ContentType, ContentType.defaultForFilePath(path))
```

### Platform(s)

Desktop

**Comment by jan-tennert** [comment]
Included in 0.7.5. Let me know if there are any issues!
