### ISSUE TITLE
[Question]: Does Supabase Postgrest-kt support embedding entire Kotlin data objects as foreign keys?

### ISSUE THREAD

**Issue by Premjit-Developer** [supabase-community/supabase-kt#461]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

I created two tables: one for food data and another for restaurant data. I established a foreign key relationship using the `restaurant_id` in the `foods_table`. However, when I try to retrieve the restaurant name based on its ID, the query isn't working as expected. I've also tried using an inner join, but it's still not producing the desired results.

**Foods Table**
```
create table
  public.foods_table (
    id bigint generated by default as identity,
    name text not null,
    "imageUrl" text not null,
    price bigint not null,
    tagline text not null,
    rating double precision not null,
    restaurant_id uuid not null,
    constraint foods_table_pkey primary key (id),
    constraint foods_table_restaurant_id_fkey foreign key (restaurant_id) references restaurants (id) on delete cascade
  ) tablespace pg_default;

```
**Restaurants Table**
```
create table
  public.restaurants (
    id uuid not null default gen_random_uuid (),
    name character varying not null,
    email character varying null,
    address character varying null,
    constraint restaurants_pkey primary key (id)
  ) tablespace pg_default;
```
**Kotlin classes**
```
@Immutable
@Serializable
data class Food(
    val id: Long,
    val name: String,
    val imageUrl: String,
    val price: Long,
    val tagline: String,
    val rating: Double,
    val restaurantId: Restaurant
)

@Immutable
@Serializable
data class FoodDto(
    val id: Long,
    val name: String,
    val imageUrl: String,
    val price: Long,
    val tagline: String,
    val rating: Double,
    @SerialName("restaurant_id")
    val restaurantId: Restaurant
)

@Immutable
@Serializable
data class Restaurant(
    val id: String,
    val name: String,
    val email: String,
    val address: String,
)

fun FoodDto.asDomainModel(): Food = Food(
    id = this.id,
    name = this.name,
    imageUrl = this.imageUrl,
    price = this.price,
    tagline = this.tagline,
    rating = this.rating,
    restaurantId = this.restaurantId
)

```
**Database query**
```
 override fun getAllSuperFoods(): Flow<ResultState<List<Food>>> = flow {

        emit(ResultState.Loading)
        try {


            val columns = Columns.raw(
                "* , restaurants(*)"
            )

            val data = postgrest.from("foods_table").select(columns = columns)
                .decodeList<FoodDto>()
                .map { it.asDomainModel() }

            emit(ResultState.Success(data))

        } catch (e: Exception) {
            emit(ResultState.Error(e))
        }

    }
```

When I remove the `Restaurant` object from my `Food` classes and replace it with a string representing the restaurant ID, I only retrieve the ID itself. However, adding the Restaurant object as a field results in no data being returned from the Supabase database.

I'm looking for guidance on how to properly retrieve and include the full Restaurant object associated with the foreign key in Kotlin within Supabase, as I've been able to directly embed data objects in other databases like Room, Realm. Unfortunately, I haven't been able to find relevant tutorials for this specific scenario.

**Comment by jan-tennert** [comment]
So you don't get any data at all? No error? Looking at your code I can say that you are using the wrong serial name for your `Restaurant` property. So your columns are `"* , restaurants(*)"` and you have this `FoodDto`:
```kotlin
@Immutable
@Serializable
data class FoodDto(
    val id: Long,
    val name: String,
    val imageUrl: String,
    val price: Long,
    val tagline: String,
    val rating: Double,
    @SerialName("restaurant_id")
    val restaurantId: Restaurant
)
```
The serial name should be `restaurants`, because that's the name you request the extra data with. So it would be like this:
```kotlin
@Immutable
@Serializable
data class FoodDto(
    val id: Long,
    val name: String,
    val imageUrl: String,
    val price: Long,
    val tagline: String,
    val rating: Double,
    @SerialName("restaurants")
    val restaurant: Restaurant
)
```
**Note:** The `restaurant_id` key also exists, but that's literally just the id as you'd expect
You can also rename the columns you receive by using a `:`: `Columns.raw(`"* , restaurant:restaurants(*)"`)`, then the key would be `restaurant`

**Comment by jan-tennert** [comment]
And you really have no error? Can you try printing `postgrest.from("foods_table").select(columns = columns).data` (this will give you the raw json string). If this is empty, there must be something wrong with the table relationship. For me it works perfectly fine when trying it on my db:
```kotlin
val result = supabase.postgrest["products"].select(Columns.raw("*, shop:shops(*)"))
     .decodeList<Product>()
```

**Comment by Premjit-Developer** [comment]
`postgrest.from("foods_table").select(columns = columns).data`

Yes This is returning JSON data.

![Screenshot from 2024-02-09 21-09-41](https://github.com/supabase-community/supabase-kt/assets/72644801/da2608b1-bbe0-420f-8ef8-74ac0d6bfd14)


I don't know what's wrong with it. But when I replace the Restaurant data object with string everything works well, with the Restaurant data object Supabase returning no data. If you can show your two-tables relationship, then I can match my tables with it and see what's wrong.

**Comment by jan-tennert** [comment]
That looks alright. I might have confused you, you don't actually rename the column of your `foods_table` from `restaurant_id` to `restaurant`. You only do that in the request. So you have your column `restaurant_id`, but your requested columns are:
```kotlin
val columns = Columns.raw("* , restaurant:restaurants(*)")
```
Then you should have your data under the key `restaurant` and this code should work:
```kotlin
@Immutable
@Serializable
data class FoodDto(
    val id: Long,
    val name: String,
    val imageUrl: String,
    val price: Long,
    val tagline: String,
    val rating: Double,

    @SerialName("restaurant")
    val restaurant: Restaurant
)
```

**Comment by Premjit-Developer** [comment]
I forgot to tell you that when printing data the `restaurant_id` is only returning the `id`, which is referenced in `foods_table`, not the whole `restaurants` table column data. After renaming and doing everything you told result is the same.
Maybe that's why when I set String instead of the whole Restaurant data class it is working.

![Screenshot from 2024-02-10 13-46-14](https://github.com/supabase-community/supabase-kt/assets/72644801/06e9febd-fceb-4e97-adf6-f4356946420c)


Am I missing something to establish a one-to-one or one-to-many relationship between tables?

**Comment by jan-tennert** [comment]
Not sure, I don't know SQL that much. For reference that are my two tables which work:
```sql
create table
  public.products (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    user_id uuid null,
    content text null,
    shop_id bigint null,
    done_since timestamp with time zone null,
    done_by uuid null,
    constraint products_pkey primary key (id),
    constraint products_done_by_fkey foreign key (done_by) references auth.users (id),
    constraint products_shop_id_fkey foreign key (shop_id) references shops (id) on delete cascade,
    constraint products_user_id_fkey foreign key (user_id) references auth.users (id)
) tablespace pg_default;
```
```sql
create table
  public.products (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    user_id uuid null,
    content text null,
    shop_id bigint null,
    done_since timestamp with time zone null,
    done_by uuid null,
    constraint products_pkey primary key (id),
    constraint products_done_by_fkey foreign key (done_by) references auth.users (id),
    constraint products_shop_id_fkey foreign key (shop_id) references shops (id) on delete cascade,
    constraint products_user_id_fkey foreign key (user_id) references auth.users (id)
) tablespace pg_default;
```
Can you try these columns:
```kotlin
val columns = Columns.raw("* , restaurant:restaurant_id(*)")
```

**Comment by Premjit-Developer** [comment]
I finally found the issue. The problem was with the `foods_table`. Initially, I thought it was due to the `created_at` attribute, but after creating multiple tables with and without `created_at`, I realized that it was not the main problem. So, I tried creating a new table with the same attributes as `foods_table`, and to my surprise, the server returned the whole `restaurants` table's row with that new table.

![Screenshot from 2024-02-11 13-44-10](https://github.com/supabase-community/supabase-kt/assets/72644801/6f4591a6-242e-48cc-b1e5-900d7ee80376)

**However, when I try to display the data with the embedded Restaurant object in the data class, my app shows no data and it doesn't print anything either. I'm assuming that it is a library issue does it happen with you?**

**Comment by jan-tennert** [comment]
No it does not, also what do you mean "shows no data"? Something must be happening, either a serialization error or something else

**Comment by jan-tennert** [comment]
I see you catch the error there and emit it in the flow. Can you print that?

**Comment by Premjit-Developer** [comment]
Yes, there is a serialization issue. Due to a small mistake, the issue should have been solved yesterday.

Can I retrieve necessary table data without using `ignoreUnknownKeys = true` and without sending whole table row names in the Kotlin class?
I do not want to include an extra `restaurant_id` variable in my data class because the `restaurants` table has that id.

**Comment by jan-tennert** [comment]
I don't think its possible to exclude certain columns while still requesting all others with (`*`). I'd just make this serialization change on the library level by changing the default serializer:
```kotlin
val client = createSupabaseClient(url, key) {
    defaultSerializer = KotlinXSerializer(Json {
         ignoreUnknownKeys = true
    })
}
```
This also prevents future errors when you add or modify columns

**Comment by Premjit-Developer** [comment]
Thank you for your continuous replies.
