### ISSUE TITLE
[Question]: supabase-kt and android java

### ISSUE THREAD

**Issue by dkati** [supabase-community/supabase-kt#462]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Can i use supabase-kt from an Android mobile app which is built with java?

**Comment by jan-tennert** [comment]
Sadly no, because this library uses Kotlin features which would require creating a wrapper around almost every function. (DSLs, Coroutines)

**Comment by jan-tennert** [comment]
You can try to use Kotlin to call supabase-kt functions and then call your own functions in Java

**Comment by dkati** [comment]
the main problem is that i cant use 
...{
install (Auth)
}
in java

But ok. thanks . So you think that the only solution will be to use REST ?
