### ISSUE TITLE
UnknownRestException when using signInWith(OTP) { email = ... }

### ISSUE THREAD

**Issue by samidaik00** [supabase-community/supabase-kt#463]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.1.1

### Target(s)

JVM

### What happened? (include your code)

UnknownRestException
UncaughtExceptionHandler

io.github.jan.supabase.gotrue.AuthImpl in parseErrorResponse at line 501

signinWithOTP using the email of a manually created user. First the email sent is a magic link email and not an OTP, so i cannot verify the user.

I tried creating the user manually after receiving the error:
**BadRequestRestException
Signups not allowed for otp**

![CleanShot 2024-02-09 at 23 13 56](https://github.com/supabase-community/supabase-kt/assets/9599849/281a8483-ca3f-4216-b467-4ec58fd897a0)

I understood from the docs that i should be able to signup a user with OTP email :

_If the user doesn't exist, signInWith(OTP) will signup the user instead. To restrict this behavior, you can set createUser to false.
The method signUpWith(OTP) does the exact same thing as signInWith(OTP), so it doesn't matter which one you use._

from https://supabase.com/docs/reference/kotlin/auth-signinwithotp

But i cannot seem to get it working

### Steps To Reproduce (optional)

testing signinWithOTP with the following code: 

```
override suspend fun auth() {
        supabase.supabaseClient.auth.signInWith(OTP) {
            email = "s@.....me"
        }
    }
```
    
    I pressed ny button twice to test and received this exception in Sentry, stack traced attached.
    
    **Also the email send was not an OTP but a magic link email.** 
    
![CleanShot 2024-02-09 at 22 44 30](https://github.com/supabase-community/supabase-kt/assets/9599849/a7886d72-7a4a-465b-9358-7d1c4ea89160)

**Comment by jan-tennert** [comment]
For your first problem: You have to edit your E-Mail template to show the OTP Token rather than a confirmation link. (Under https://supabase.com/dashboard/project/<your project id>/auth/templates):
![image](https://github.com/supabase-community/supabase-kt/assets/26686035/cece617c-2da9-4cea-85a1-6835a65de365)
For your second problem, you have to set `createUser` to true:
```kotlin
supabase.supabaseClient.auth.signInWith(OTP) {
      email = "s@.....me"
      createUser = true
}
```
The documentation seems wrong, this isn't enabled by default.
