### ISSUE TITLE
[Bug]: Limit and nested joins

### ISSUE THREAD

**Issue by gukzilla** [supabase-community/supabase-kt#474]
### General Info

- [x] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.1.3

### Target(s)

17 14

### What happened? (include your code)

When I do a limit query for nested joins, an error occurs.

> "'user_chats.chats.user_chats' is not an embedded resource in this request"

All because in PostgrestRequestBuilder class, referencedTable is wrapped in double quotes.
`"\"$referencedTable\".limit."`

And in this form the request is sent to the server.
This problem is not present in js, but it is present in kotlin library.

Sending a request in js library
`&user_chats.chats.user_chats.limit=1`

Sending a request in kotlin library
`&"user_chats.chats.user_chats".limit=1`

Replaying the request via REST, I simply removed the double quotes and the error disappeared.
Please fix the problem.
Really need to do limit for nested joins.

**Comment by jan-tennert** [comment]
Thank you for reporting this, can you try out version `2.1.4-dev` and see it this was fixed?

**Comment by gukzilla** [comment]
> Thank you for reporting this, can you try out version `2.1.4-dev` and see it this was fixed?

Thank you! Checked, the limit works. Problem solved in version 2.1.4-dev
