### ISSUE TITLE
[Bug]: Problem with loading data in the background.

### ISSUE THREAD

**Issue by gukzilla** [supabase-community/supabase-kt#489]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.1.5

### Target(s)

17 - 14

### What happened? (include your code)

I have an object that contains several attachments, pictures (and in the future, audio and video).

I am using WorkManager, CoroutineWorker starts when the application is in backgroud or unloaded from memory: all pictures are loaded into storage from an anonymous user (RLS is currently disabled) and do not contain owner_id field.

I assume that all other objects will be created from an anonymous user. 
And I would like to create them from my own user.

How can I get around this restriction?

### Steps To Reproduce (optional)

1. Start Worker
2. Hide app
3. Get this behaviour

**Comment by jan-tennert** [comment]
So the problem is that the data gets uploaded from an anonymous user, and not the user that signed in?

**Comment by gukzilla** [comment]
> So the problem is that the data gets uploaded from an anonymous user, and not the user that signed in?

Yes

**Comment by jan-tennert** [comment]
I'd assume that is the case because by default, gotrue-kt clears the session from memory when the app goes into background. You can disable this in the config (`enableLifecycleCallbacks`), however, then you'll have to start and stop the auto refresh yourself. (`Auth#startAutoRefreshForCurrentSession`, `Auth#stopAutoRefreshForCurrentSession`).

**Comment by gukzilla** [comment]
> however, then you'll have to start and stop the auto refresh yourself. (`Auth#startAutoRefreshForCurrentSession`, `Auth#stopAutoRefreshForCurrentSession`).

Thank you very much! 
I will handshake the session manually. 
I looked at the source code and I see that you use onStart and onStop lifecycle methods. 
I'll do the same)

ps: Now images are loaded in the backgroud)

**Comment by jan-tennert** [comment]
Great, let me know if you have any more questions!

**Comment by gabrielsantanaa** [comment]
hey guys, just sharing my solution here.

instead of disabling and managing lifecycles callbacks manually, i just called `auth.loadFromStorage()` and the session worked.

**Comment by fethij** [comment]
@gabrielsantanaa where are you calling ` auth.loadFromStorage()`?
