### ISSUE TITLE
Compose Auth Google signin crashes in android 14

### ISSUE THREAD

**Issue by lspradeep** [supabase-community/supabase-kt#507]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.2.1

### Target(s)

Android

### What happened? (include your code)

After successful implementation of compose auth for google sign in, it works fine in android 10 device but crashes in android 14 device. Getting the following error

<img width="1021" alt="image" src="https://github.com/supabase-community/supabase-kt/assets/25198507/5aeea825-2962-4ef5-b0a1-6e6063044aa9">

**Comment by jan-tennert** [comment]
@lspradeep I assume you found the problem, can you share your solution?

**Comment by lspradeep** [comment]
fix: add the following dependencies to your androidMain

```
[versions]
credentials = "1.2.1"
googleid = "1.1.0"

[libraries]
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
```
