### ISSUE TITLE
[Question]: Should missing Json properties be ignored by default?

### ISSUE THREAD

**Issue by hieuwu** [supabase-community/supabase-kt#509]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

I got the exception of missing Unknown Json property while I already specs which property I want to get from the response.
```kotlin
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 228: Encountered an unknown key 'created_at' at path: $[0].address
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....4f391f1aab08","address":null,"created_at":null}]
```

I fixed it by providing the defaultserializer the Json property with needed configuration for KotlinSerializer
```kotlin
    @Provides
    @Singleton
    fun provideSupabaseClient(): SupabaseClient {
        return createSupabaseClient(
            supabaseUrl = BuildConfig.SUPABASE_URL,
            supabaseKey = BuildConfig.API_KEY,
        ) {
            defaultSerializer = KotlinXSerializer(Json { ignoreUnknownKeys = true })
            install(Postgrest)
            install(Auth)
        }
    }
```

Should this configuration be default? As based on each feature, multiple DTO object would be created to query only needed properties.

**Comment by jan-tennert** [comment]
I think it's fine if we ignore unknown keys by default, I don't think there is any downside for this
