### ISSUE TITLE
[Question]: Comparing timestamptz in jsonb structure.

### ISSUE THREAD

**Issue by alialbaali** [supabase-community/supabase-kt#516]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Hey there,

I have a database table with a `jsonb` column named `meta_data` that contains the following:

```json
{
  "updated_at": "2023-01-01 00:00:00+00"
}
```

When trying to compare this timestamp on the client using `eq`, `gt`, `lt`, etc... I always receive an error:

```kotlin
invalid input syntax for type json (Token "-01" is invalid.)
/rest/v1/folders?meta_data-%3Eupdated_at=eq.2023-01-01T00%3A00%3A00Z&select=%2A
``` 

The code:

```kotlin
            client.postgrest[SupabaseConstants.Tables.Folders]
                .select {
                    filter {
                        eq("meta_data->updated_at", "2023-01-01T00:00:00Z")
                        // Or
                        eq("meta_data->updated_at", "2023-01-01 00:00:00+00")
                    }
                }
                .decodeList()
```

Could you please tell me, what am I doing wrong? Or is it a bug?

**Comment by jan-tennert** [comment]
I'm not sure, can you try this?
```kotlin
client.postgrest[SupabaseConstants.Tables.Folders] .select { 
    filter { 
        eq("meta_data->>updated_at", "2023-01-01T00:00:00Z") 
        // Or 
        eq("meta_data->>updated_at", "2023-01-01 00:00:00+00") 
    } 
}.decodeList()
```

**Comment by alialbaali** [comment]
You're the best! It worked flawlessly! 🫡

Thank you :)

**Comment by jan-tennert** [comment]
Yea, I think `->` is for numbers and `->>` for strings
