### ISSUE TITLE
[Bug]: Uncaught IndexOutOfBoundsException during createSupabaseClient()

### ISSUE THREAD

**Issue by JonathanMandel** [supabase-community/supabase-kt#517]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.0.0

### Target(s)

jsMain and commonMain

### What happened? (include your code)

I'm building a web app in Kotlin that currently uses email/password auth. I create a Supabase Client like this:

```
open class HttpSession {
    private val client = createSupabaseClient(
        supabaseUrl = [myUrl],
        supabaseKey = [myAnonKey]    
) {
        defaultSerializer = KotlinXSerializer(
            Json {
                prettyPrint = true
                isLenient = true
                ignoreUnknownKeys = true
            }
        )
        install(Postgrest)
        install(Auth)
    }

    fun getClient(): SupabaseClient {
        return client
    }
}
```
This is called like this:

```
fun main() {
    val session = HttpSession()
    router.start(session)
}

```
When my app starts, it throws an uncaught IndexOutOfBoundsException. I believe the problem is in your [AuthExtension.kt]([https://github.com/supabase-community/supabase-kt/blob/d710c6064ad586633493aad043b7e766f1708f32/GoTrue/src/commonMain/kotlin/io/github/jan/supabase/gotrue/AuthExtensions.kt#L23]). Your code does this:

```
    val sessionParts = fragment.split("&").associate {
        it.split("=").let { pair ->
            pair[0] to pair[1]
        }
    }

```
But if the URL does not contain an ampersand, pair[1] throws IndexOutOfBoundsException. 

If this is my fault because I'm not configuring createSupabaseClient() properly, I will go back to my cave with my tail between my legs.

**Comment by jan-tennert** [comment]
Hey, can you try out a newer version and see if this issue still persists? There have been some changes to this system a few versions back

**Comment by JonathanMandel** [comment]
Yes. I'll see if I can find a newer version, and let you know what happens.

**Comment by JonathanMandel** [comment]
I rebuilt with 2.2.2. This solves the problem. I'm closing this issue. Thank you.
