### ISSUE TITLE
[Bug]: Can't find "org.jetbrains.compose.annotation-internal:annotation"

### ISSUE THREAD

**Issue by planasmultimedia** [supabase-community/supabase-kt#525]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.2.2

### Target(s)

iOs

### What happened? (include your code)

Having this error by just importing the supabase-kt into the project and trying to run it :

Could not find "org.jetbrains.compose.annotation-internal:annotation" in [/Users/XXXXXX/Documents/VibeApp, /Users/XXXXX/.konan/klib, /Users/XXXXX/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/common, /Users/XXXXXX/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/platform/ios_arm64]

**Comment by jan-tennert** [comment]
Assuming you added a compose plugin, you need to add the `google()` repository in your Gradle configuration. Compose 1.6.X requires it.

**Comment by planasmultimedia** [comment]
I have both of them :(

**Comment by jan-tennert** [comment]
Are you using Compose 1.6? Can you share your Buildfile?

**Comment by planasmultimedia** [comment]
alright, seems that i wasn't using compose 1.6, BUT, i updated it and still having the same error
My gradle.properties, i don't know if you refer to this file :

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"

#Kotlin
kotlin.code.style=official

#MPP
kotlin.mpp.stability.nowarn=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2

#Android
android.useAndroidX=true
android.targetSdk=34
android.compileSdk=34
android.minSdk=24

#Versions
kotlin.version=1.9.21
agp.version=8.0.2
compose.version=1.6.0

**Comment by jan-tennert** [comment]
I mean the build files, so `build.gradle.kts` files

**Comment by planasmultimedia** [comment]
Sorry,

Project build.gradle
`plugins {
    kotlin("multiplatform").apply(false)
    id("com.android.application").apply(false)
    id("com.android.library").apply(false)
    id("org.jetbrains.compose").apply(false)
}

buildscript{
    dependencies{
        repositories {
            maven {
                url = uri("https://plugins.gradle.org/m2/")
                maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
            }
        }
    }
}
`

Shared module:

`plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("org.jetbrains.compose")
    alias(libs.plugins.kotlinSerialization)
    id("org.jetbrains.kotlin.plugin.atomicfu") version "1.8.20"
}

kotlin {
    androidTarget()


    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "shared"
            isStatic = true
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {

                implementation("dev.icerock.moko:resources:0.22.3")
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material)
                @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
                implementation(compose.components.resources)
                implementation(libs.koin.core)
                implementation(libs.koin.compose)
                implementation(libs.kermit)
                implementation(libs.androidx.datastore.preferences.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.androidx.datastore.preferences.core)
                implementation(libs.atomicfu)
                //implementation(libs.ktor.client.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.ktor.serialization)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.auth)

                //Navigation
                implementation(libs.decompose)
                implementation("com.arkivanov.decompose:decompose:2.2.1-compose-experimental")
                implementation("com.arkivanov.decompose:extensions-compose-jetbrains:2.2.1-compose-experimental")

                implementation("media.kamel:kamel-image:0.9.2")

                implementation(libs.moko.mvvv.core)
                implementation(libs.moko.mvvv.compose)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.client.logging)

                implementation(libs.multiplatform.settings)

                implementation(libs.voyager.tabNavigator)
                implementation(libs.voyager.transitions)
                implementation(libs.voyager.navigator)

                //Calculate window size
                implementation("dev.chrisbanes.material3:material3-window-size-class-multiplatform:0.3.1")

                implementation("com.russhwolf:multiplatform-settings-no-arg:1.1.1")

                //Graph library
                implementation("io.github.thechance101:chart:Beta-0.0.5")

                // Graph 2
                implementation("io.github.koalaplot:koalaplot-core:0.5.2")

                // Bottom Sheet
                // compose material
                implementation("com.github.skydoves:flexible-bottomsheet-material:0.1.2")

                implementation ("com.benasher44:uuid:0.8.2")

                //Supa base
                implementation(libs.gotrue.kt) //login
                implementation(libs.compose.auth.ui) // UI
                implementation(libs.compose.auth) // UI
            }
        }
        val androidMain by getting {
            dependencies {
                api("androidx.activity:activity-compose:1.7.2")
                api("androidx.appcompat:appcompat:1.6.1")
                api("androidx.core:core-ktx:1.12.0")

                api(libs.spotify.auth)// Maven dependency
                implementation(libs.koin.android)
                implementation(libs.koin.androidx.compose)
                implementation(libs.atomicfu)
                implementation(libs.ktor.client.okhttp)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.multiplatform.settings)
                implementation("com.russhwolf:multiplatform-settings-no-arg:1.1.1")

                implementation(libs.decompose)
                //implementation(libs.decompose.extensions)

            }
        }
        val iosX64Main by getting
        val iosArm64Main by getting
        val iosSimulatorArm64Main by getting
        val iosMain by creating {
            dependsOn(commonMain)
            iosX64Main.dependsOn(this)
            iosArm64Main.dependsOn(this)
            iosSimulatorArm64Main.dependsOn(this)

            dependencies {
                implementation(libs.ktor.client.darwin)
                //implementation(libs.decompose)
                //implementation(libs.decompose.extensions)
            }
        }
    }
}

android {
    compileSdk = (findProperty("android.compileSdk") as String).toInt()
    namespace = "com.vibe.mainapp"

    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")
    sourceSets["main"].resources.srcDirs("src/commonMain/resources")

    defaultConfig {
        minSdk = (findProperty("android.minSdk") as String).toInt()
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        jvmToolchain(17)
    }
}
dependencies {
    implementation(libs.androidx.constraintlayout)
}
`


Settings.gradle

`rootProject.name = "Vibe"

include(":androidApp")
include(":shared")

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        maven("https://jitpack.io")
    }

    plugins {
        val kotlinVersion = extra["kotlin.version"] as String
        val agpVersion = extra["agp.version"] as String
        val composeVersion = extra["compose.version"] as String

        kotlin("jvm").version(kotlinVersion)
        kotlin("multiplatform").version(kotlinVersion)
        kotlin("android").version(kotlinVersion)

        id("com.android.application").version(agpVersion)
        id("com.android.library").version(agpVersion)

        id("org.jetbrains.compose").version(composeVersion)
        id("org.jetbrains.kotlin.plugin.atomicfu") version "1.8.20"
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version("0.4.0")
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        maven("https://jitpack.io")
    }
}
`

**Comment by jan-tennert** [comment]
I think the problem lies in your `Shared module` `build.gradle.kts`. You may need to add this block:
```kotlin
repositories {
    google()
}
```

**Comment by jan-tennert** [comment]
I can only tell what is written in the Compose changelog:
![grafik](https://github.com/supabase-community/supabase-kt/assets/26686035/9f7e37d3-96b8-4fc8-965f-a526f2b896ab)

**Comment by jan-tennert** [comment]
But I saw somewhere, that if you use a dependency with a beta version of 1.6.0, this error might also occur. So you could check which Compose versions your other libraries use. Supabase-kt uses 1.6.X

**Comment by planasmultimedia** [comment]
Hey mate, i was on vacations but the second I got into the computer i look into it and found it !! you don't know how much pain you avoided hahahaha Thank you very much
