### ISSUE TITLE
[Bug]: ComposeAuth Google Login Issue

### ISSUE THREAD

**Issue by jAsOniltok** [supabase-community/supabase-kt#526]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems
- [X] I enabled [logging](https://github.com/supabase-community/supabase-kt/wiki/Logging) and checked the logs

### Version(s)

2.2.2

### Target(s)

android and jvm and ios

### What happened? (include your code)

```
   val action = supabase.composeAuth.rememberSignInWithGoogle(
        onResult = {
            Logger.d("action 1")
        },
      /*  fallback = {
            Logger.d("action 2")

        }*/
    )
```
If I uncomment the fallback here, it will not work on the desktop app and iOS app, resulting in a 100% fallback being logged.

**Comment by jan-tennert** [comment]
I'm not sure if l understand your question. If you don't specify the fallback parameter, the default OAuth flow will be used. If you do, then your block will be executed instead.
