### ISSUE TITLE
[Feature request]: Add support for new private channels

### ISSUE THREAD

**Issue by jan-tennert** [supabase-community/supabase-kt#554]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Supabase has a new feature which allows creating private channels to use the broadcast and presence features within RLS policies. See https://github.com/orgs/supabase/discussions/22484.

**Comment by grdsdev** [comment]
Implemented in: https://github.com/supabase-community/supabase-kt/pull/642
