### ISSUE TITLE
[Bug]: Auth refresh sessions is not working correctly

### ISSUE THREAD

**Issue by MohamedRejeb** [supabase-community/supabase-kt#567]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems

### Version(s)

2.3.1

### Kotlin Target(s) and their respective versions

JVM 17

### What happened? (include your code)

Hi,
Refresh sessions is not working as expected when I have two versions of the same app installed with different flavors.
So let's say I have a release version installed with a link of the remote supabase and I'm logged in there. If I install another version of the app with a different flavor, debug version for example, which is linked to my local supabase.
The first app works fine but the second app gets the saved session of the first app and I'm considered as authenticated which is not the case, and all api calls are failing since the token is for the remote supabase not the local one.
```
Info: (Supabase-Auth) Trying to load latest session from storage.
Info: (Supabase-Auth) Successfully loaded session from storage!
```

Either the library should somehow support having different versions of the same app authenticated to different accounts at the same time, or at least when I receive an Unauthenticated exception, it should clear the session and log me out.
Let me know what you think. I can help on this.

Thanks!

**Comment by jan-tennert** [comment]
I guess you could just provide a custom session manager, which saves sessions to separate keys depending on the build mode:
(this is a straight copy from the default one, see text below)
```kotlin
class CustomSessionManager @OptIn(SupabaseInternal::class) constructor(
    settings: Settings = createDefaultSettings()
) : SessionManager {

    @OptIn(ExperimentalSettingsApi::class)
    private val suspendSettings = settings.toSuspendSettings()

    @OptIn(ExperimentalSettingsApi::class, SupabaseInternal::class)
    override suspend fun saveSession(session: UserSession) {
        suspendSettings.putString(SETTINGS_KEY, supabaseJson.encodeToString(session))
    }

    @OptIn(ExperimentalSettingsApi::class, SupabaseInternal::class)
    override suspend fun loadSession(): UserSession? {
        val session = suspendSettings.getStringOrNull(SETTINGS_KEY) ?: return null
        return try {
            supabaseJson.decodeFromString(session)
        } catch(e: Exception) {
            Auth.logger.e(e) { "Failed to load session" }
            null
        }
    }

    @OptIn(ExperimentalSettingsApi::class)
    override suspend fun deleteSession() {
        suspendSettings.remove(SETTINGS_KEY)
    }

    companion object {

        private const val SETTINGS_DEBUG_KEY = "session_debug"
        private const val SETTINGS_RELEASE_KEY = "session_release"
        const val SETTINGS_KEY = if(BuildConfig.DEBUG) SETTINGS_DEBUG_KEY else SETTINGS_RELEASE_KEY

    }

}
```
```kotlin
val supabase = createSupabaseClient(
    "url",
    "key"
) {
    install(Auth) {
        sessionManager = CustomSessionManager()
    }
}
```

**To make this easier, we could also make it possible to set the `SETTINGS_KEY` in the constructor of the "default" `SettingsSessionManager()`. So you wouldn't have to create a completely new class**

**Comment by grdsdev** [comment]
Hi @jan-tennert JS and Flutter SDKs uses the project ref as namespace

- supabase-js https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L85
- supabase-flutter https://github.com/supabase/supabase-flutter/blob/main/packages/supabase_flutter/lib/src/supabase.dart#L93

I'll be applying this change to Swift too, and it would be nice if Kotlin had the same behavior.

**Comment by jan-tennert** [comment]
Right, we should probably do this, and it would solve this issue, but we could still make this configurable.

**Comment by MohamedRejeb** [comment]
I can work on this. I will make it configurable and use the project reference as well.

**Comment by jan-tennert** [comment]
Great, if you change the default key, you should probably add a check to see if there is a session on the old namespace to prevent force logging out everyone who updates the library.

**Comment by MohamedRejeb** [comment]
Btw here if I'm getting an `UnauthorizedException`, I should be logged out anyway right? Because it's not happening, maybe there's something missing there as well.

**Comment by jan-tennert** [comment]
If this exception is thrown while refreshing, the session should be getting cleared.

**Comment by MohamedRejeb** [comment]
So the flow should be like this: Make call -> if the call is failing refresh -> if the refresh is failing clear.
In that case, the call is failing so the refresh should be called and the refresh should fail as well because the token is wrong and also we keep getting failures. If refresh if successful the next call should succeed but it's not the case.

**Comment by jan-tennert** [comment]
Not sure if I understand the problem. The library doesn't handle API errors at all, they just get thrown as a RestException (which has some subclasses based on the status code). The only case where RestException get caught is in the auto refresh:
https://github.com/supabase-community/supabase-kt/blob/9ed96b2b9f7bee49cbc5fed0117c929c95f3057b/GoTrue/src/commonMain/kotlin/io/github/jan/supabase/gotrue/AuthImpl.kt#L404-L406
But other than that, exceptions are handled by the application itself
