### ISSUE TITLE
[Bug]: Could not serialize Email register response

### ISSUE THREAD

**Issue by lucat1** [supabase-community/supabase-kt#59]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

I am running a self hosted SupaBase server with email "autoconfirm", so when a user registers he is automatically verified.
Therefore I believe the goTrue server does not provide the `confirmation_sent_at` field in the JSON response. Could this field be made optional as a simple fix?

### Platform(s)

Android

### Relevant log output

```shell
W/System.err: kotlinx.serialization.MissingFieldException: Fields [id, email, confirmation_sent_at, created_at, updated_at] are required for type with serial name 'io.github.jan.supabase.gotrue.providers.builtin.Email.Result', but they were missing
```

**Comment by jan-tennert** [comment]
Yea could be, but the error says all fields are missing. Can you somehow see the payload you received? The next update shows it directly in the error message

**Comment by jan-tennert** [comment]
Published 0.8.1-dev, which should print out the actual payload

**Comment by lucat1** [comment]
I'll try it out. I tried earlier and was not able to intercept the HTTP traffic with a proxy unfortunately

**Comment by lucat1** [comment]
With this version I get the following compilation error:
```
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option
```

**Comment by jan-tennert** [comment]
Try 0.8.1-dev-2

**Comment by lucat1** [comment]
Here's the output. I believe I guessed it right in the first place:
```
W/System.err: io.github.jan.supabase.exceptions.SupabaseEncodingException: Couldn't decode sign up email result. Input: {"access_token":"redacted","token_type":"bearer","expires_in":3600,"refresh_token":"redacted","user":{"id":"bab8aa39-4f5a-441a-bb1d-95e4a11e8f79","aud":"authenticated","role":"authenticated","email":"a@test.com","email_confirmed_at":"2023-02-24T12:56:48.514995823Z","phone":"","last_sign_in_at":"2023-02-24T12:56:48.536930217Z","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"identities":[{"id":"bab8aa39-4f5a-441a-bb1d-95e4a11e8f79","user_id":"bab8aa39-4f5a-441a-bb1d-95e4a11e8f79","identity_data":{"email":"a@testests.com","sub":"bab8aa39-4f5a-441a-bb1d-95e4a11e8f79"},"provider":"email","last_sign_in_at":"2023-02-24T12:56:48.51182194Z","created_at":"2023-02-24T12:56:48.511865Z","updated_at":"2023-02-24T12:56:48.511865Z"}],"created_at":"2023-02-24T12:56:48.507148Z","updated_at":"2023-02-24T12:56:48.541193Z"}}
```

**Comment by jan-tennert** [comment]
Weird that kotlin says all fields are missing 🤔 . Well I'll push out 0.8.1 with the fix in a few minutes

**Comment by jan-tennert** [comment]
Nvm, just realized this is not the result the sign-up function expects. It's the session

**Comment by jan-tennert** [comment]
Should be fixed in 0.8.1-dev-3, the sign up function now returns null if autoconfirm is enabled (and automatically logs in)
Means sign up now has the same effect as loginWith when autoconfirm is enabled

**Comment by lucat1** [comment]
Cool! I'll try it out now

**Comment by jan-tennert** [comment]
> Cool! I'll try it out now

Does it work? Would release 0.8.1 if it's fixed

**Comment by lucat1** [comment]
Sorry, I forgot to reply. Yes it does indeed work!

**Comment by jan-tennert** [comment]
Alright, then I'll close this issue. If you need further help, feel free to reopen this issue or create another one!
