### ISSUE TITLE
[Bug]: Error: Missing one of these types: signup, email_change, sms, phone_change

### ISSUE THREAD

**Issue by RamiBadyan** [supabase-community/supabase-kt#591]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems

### Version(s)

2.4.1

### Kotlin Target(s) and their respective versions

Android 14

### What happened? (include your code)

When I execute the "resendEmail" function, it gives me an error, and this is the error message:
(Missing one of these types: signup, email_change, sms, phone_change.)

My code:
`client.auth.resendEmail(OtpType.Email.EMAIL, _state.value.email!!)`
However, when I changed this `OtpType.Email.EMAIL` to `OtpType.Email.SIGNUP` the code worked without any errors. But the problem is that `SIGNUP`shows a warning that it is deprecated!

I have attached a screenshot of the Supabase docs showing the usage of `OtpType.Email.SIGNUP` which is deprecated!

![Screenshot (58)](https://github.com/supabase-community/supabase-kt/assets/42718096/6caa4bba-f395-4820-98e5-6a6bfde82f23)

**Comment by jan-tennert** [comment]
Thanks for reporting, we might have to split these types because the SIGNUP and EMAIL_CHANGE types are deprecated for verifying.

**Comment by jan-tennert** [comment]
I'll remove the deprecation for now and add some documentation explaining this.
