### ISSUE TITLE
[Question]:  How cancel supabase request?

### ISSUE THREAD

**Issue by clwater** [supabase-community/supabase-kt#598]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems

### What is your question?

How cancel supabase request?

### Relevant log output (optional)

```shell
When i used functions.invoke(A)
I want cancel other functions.invoke(B) or same repart functions.invoke(A) or other supabse request(auth, database)
```

**Comment by jan-tennert** [comment]
That should be possible by just using a custom scope:
```kotlin
val myScope = CoroutineScope(Dispatchers.Default)
myScope.launch {
    supabase.from("countries").select()
}
//somewhere else
myScope.cancel() //This will cancel the job. You will probably need to create a new scope afterward as the old one is cancelled
```
I'm curious, why do you want to cancel these requests?

**Comment by clwater** [comment]
@jan-tennert 
Thanks, I can use the Kotlin method to cancel my request.

My app has some scheduled sync requests, but If the user logs out, I want to cancel this sync request.

**Comment by jan-tennert** [comment]
Yea, you can do that with a custom coroutine scope.
