### ISSUE TITLE
[Feature request]: Export `SupabaseExperimental` annotation in `compose-auth-ui` plugin

### ISSUE THREAD

**Issue by iruizmar** [supabase-community/supabase-kt#599]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Several things on the UI plugin are marked with `@SupabaseExperimental`.

Given that on usual architectures Supabase might be in a "data" or "domain" module and the ui module will probably be separated from there, it should be usual that the module depending on `compose-auth-ui` will not depend on any other supabase module, so it won't have access to `io.github.jan.supabase.annotations.*`.

The workaround as a user of the library is to make the ui module depend on any other supabase module, but that's not 100% correct.

My proposal: Either export `annotations` from `compose-auth-ui` plugin or create a specific experimental annotation for the plugin.

I can contribute, if desired!

Thanks!

**Comment by jan-tennert** [comment]
`compose-auth-ui` does depend on `gotrue-kt` for the Provider Icons feature (so you can just use `ProviderButtonContent(Google)` with the given supported provider). But we could change this and make a different annotation for `compose-auth-ui` like `@AuthUiExperimental`

**Comment by iruizmar** [comment]
It's weird that I can't access to `io.github.jan.supabase.annotations.*` in that case. What could be the reason?
Anyway, I could contribute the `@AuthUiExperimental` annotation, if you want. Would that be the exact naming?

**Comment by jan-tennert** [comment]
That may be because of this:
https://github.com/supabase-community/supabase-kt/blob/340968243a8468de2d29b764a5e6a7b22cb974ae/plugins/ComposeAuthUI/build.gradle.kts#L34
not sure why this is not `api`.
> Would that be the exact naming?

Probably `AuthUiExperimental`. `ComposeAuthUiExperimental` or `SupabaseAuthUIExperimental` sounds too long.
