### ISSUE TITLE
Add custom isError to AuthUI Components passwordField, EmailField

### ISSUE THREAD

**Issue by MatthiasKroiss** [supabase-community/supabase-kt#604]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

The isError of the fields should be available to set it from outside without rules to display an error.

### Usecase

E.g. When the login fails because the password was wrong I want to set it on error state

**Comment by jan-tennert** [comment]
Yea, we probably can just add a isError parameter defaulting to null (so by default its handled automatically)
