### ISSUE TITLE
[Bug]: GraphQL queries fail with 404

### ISSUE THREAD

**Issue by brezinajn** [supabase-community/supabase-kt#62]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

When trying to perform query the execution ends up with status 404.
```Failure(com.apollographql.apollo3.exception.ApolloHttpException: Http request failed with status code `404`)```

~~In addition it seems the client is trying to contact localhost:~~
~~`http://localhost?latitude=not.neq.0.0&longitude=not.neq.0.0&select=%2A`~~
Edit: My bad. Incorrect log. Disregard that please.

Further testing is currently being blocked by #61 

### Platform(s)

Android

**Comment by jan-tennert** [comment]
Published 0.8.3-dev-1 with a fix for #61, currently unable to test this issue

**Comment by jan-tennert** [comment]
Okay so just tested it with the newest version, and it should work (connecting to the real url) but something in your query might be wrong

**Comment by brezinajn** [comment]
When specifying
``` Kotlin
install(GraphQL) {
            customUrl = "https://projectIt.supabase.co/graphql/v1"
```
Everything works. The project url without this override gets resolved to `https://projectIt.supabase.co/graphql/v1/` I presume the trailing `/` messes things up.

**Comment by jan-tennert** [comment]
Published 0.8.3-dev-2, let me know if there's still an issue!

**Comment by brezinajn** [comment]
I'll test it in few hours. Thanks for quick response.

**Comment by brezinajn** [comment]
Works fine.
