### ISSUE TITLE
[Bug]: Different timestamp behavior than in Supabase console

### ISSUE THREAD

**Issue by jollygreenegiant** [supabase-community/supabase-kt#63]
### General Info

- [X] I installed the latest version of Supabase-Kt
- [X] I checked for similar bug report

### What happened? (include your code)

When attempting to compare timestamps with supabase-kt, the behavior seems to be different using the library than what I'm seeing in the Supabase console.

In the Supabase console, when I use the following query, I get a correct count of 4.
```
select count(finish_date)
from user_books
where user_id = 'some_user_id'
and reading_status = 'FINISHED'
and finish_date >= '2023-01-01T00:00:00Z'
and finish_date <= '2023-12-31T23:59:59.999999999Z'
```

But when I use the following call in the Kotlin client, I get a count of 43, which is the total number of rows with a `reading_status` of FINISHED for the given `userId`.  It seems to be ignoring the date filtering entirely.

```
supabaseClient.postgrest.from("user_books")
            .select(columns = "finish_date", count = Count.EXACT) {
                eq("user_id", "some_user_id")
                eq("reading_status", "FINISHED")
                gte("finish_date", "2023-01-01T00:00:00Z")
                lte("finish_date", "2023-12-31T23:59:59.999999999Z")
            }
```

The result I'm getting back is what I would expect from the following query:
```
supabaseClient.postgrest.from("user_books")
            .select(columns = "finish_date", count = Count.EXACT) {
                eq("user_id", "some_user_id")
                eq("reading_status", "FINISHED")
            }
```

If I'm understanding correctly, the call from the Supabase console and the first Kotlin call should be equivalent, but they're returning different values.  Not sure if this is a bug or if I'm misunderstanding the usage of the call on the Kotlin side.

When looking at the request from the kotlin side, this is the request header:

`content-location=[/user_books?finish_date=lte.2023-12-31T23%3A59%3A59.999999999Z&reading_status=eq.FINISHED&select=finish_date&user_id=eq.0d5MrCrUMLPe6fWihwLGSVG1Ww43]`

It has the `lte` filter, but not the `gte` one - is there a way to use both gte and lte to create a range?

### Platform(s)

Android

**Comment by jan-tennert** [comment]
This is not directly possible by calling both methods, as these methods overwrite each other. However, you can use a `and` or `or` statement to combine multiple filters on the same column. I just published a version `0.8.4-dev-1` containing a DSL method for both:
```kotlin
supabaseClient.postgrest.from("user_books")
            .select(columns = "finish_date", count = Count.EXACT) {
                eq("user_id", "some_user_id")
                eq("reading_status", "FINISHED")
                gte("finish_date", "2023-01-01T00:00:00Z")
                lte("finish_date", "2023-12-31T23:59:59.999999999Z")}
```

**Comment by jan-tennert** [comment]
This is not directly possible by calling both methods, as these methods overwrite each other. However, you can use a `and` or `or` statement to combine multiple filters on the same column. I'm publishing a version `0.8.4-dev-1` containing a DSL method for both:
```kotlin
supabaseClient.postgrest.from("user_books")
  .select(columns = "finish_date", count = Count.EXACT) {
        eq("user_id", "some_user_id")
        eq("reading_status", "FINISHED")
        and {
           gte("finish_date", "2023-01-01T00:00:00Z")
           lte("finish_date", "2023-12-31T23:59:59.999999999Z")
        } 
  }
```
The build should be done in around ~20-30min, let me know if it works or if I broke something!

**Comment by jollygreenegiant** [comment]
Works great, thanks so much for getting on that so quickly!
