### ISSUE TITLE
[Bug]: After deleting a user via edge function you can not logout

### ISSUE THREAD

**Issue by appcelerate** [supabase-community/supabase-kt#631]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems

### Version(s)

2.5.0

### Kotlin Target(s) and their respective versions

Android 14

### What happened? (include your code)

I have an issue with logging out a user I was deleting.

So the use case is:
A user want to delete the account and after deletion the user gets logged out.

Problem: 
If you call the edge function, user is getting deleted correctly but after this I try to logout and get this error message using the logout function "User from sub claim in JWT does not exist" 

iOS SDK had similar issue -> https://github.com/supabase/supabase-swift/issues/358

**Comment by grdsdev** [comment]
Hey @jan-tennert,

When signing out, it needs to ignore, 401, 403 and 404 status codes, check Swift implementation: https://github.com/supabase/supabase-swift/blob/083c6c3462a4a8d8eebe5712742bd426e52a1cb6/Sources/Auth/AuthClient.swift#L794-L801

**Comment by jan-tennert** [comment]
Hi,
thanks for reporting this and @grdsdev for the fix. I'll publish a version later resolving this problem.

**Comment by appcelerate** [comment]
@jan-tennert when can we expect the 2.5.1 release including this fix?

**Comment by jan-tennert** [comment]
The version should have been out already (on maven central), but it seems like sonatype causes problems again. Will look into it

**Comment by appcelerate** [comment]
yeah somehow when I try to update it with 

` // Supabase
    implementation(platform("io.github.jan-tennert.supabase:bom:2.5.0"))
    implementation("io.github.jan-tennert.supabase:postgrest-kt")
    implementation("io.github.jan-tennert.supabase:apollo-graphql")
    implementation("io.github.jan-tennert.supabase:compose-auth")
    implementation("io.github.jan-tennert.supabase:compose-auth-ui")
    implementation("io.github.jan-tennert.supabase:functions-kt")
    implementation("io.ktor:ktor-client-android:2.3.8")`

its not working

**Comment by jan-tennert** [comment]
It seems like Sonatype changed some stuff regarding authentication, which required a few changes on our end, but it should work now. Hopefully, the version will appear in ~30min on Maven Central
