### ISSUE TITLE
[Bug]: Unable to receive realtime updates on an native Android app

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/supabase-kt#634]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems

### Version(s)

2.4.1

### Kotlin Target(s) and their respective versions

Android targetSdk 34

### What happened? (include your code)

I am unable to get any realtime data using the realtime feature of this library. 

- The tables have realtime enabled, and I can observe the realtime data coming in on a Flutter app
- RLS is disabled on the table, so not a RLS issue either
- I am using okhttp for the ktor client as outlined in the [trouble shooting guide](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD)
- The library is able to call PostgREST apis, so doesn't seem like an network configuration issue either

### Steps To Reproduce (optional)

1. Create a Supabase project with some tables with no RLS enabled, but Realtime enabled
1. Create an Android app on Android Studio
1. Paste the following code and run the app
1. Press the button at the middle of the page to start listening
1. Change some values of the tables with Realtime enabled on the Supabase dashboard
```kotlin
val supabase = createSupabaseClient(
    supabaseUrl = "https://rmjwhnhfotnpbnjfnxka.supabase.co",
    supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtandobmhmb3RucGJuamZueGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTkzNzMzODYsImV4cCI6MjAzNDk0OTM4Nn0.l5C85uPdndHNWDQPXr8OPPBOjqCgnsn2bvhWtiTy328"
) {
    install(Realtime)
}

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ExampleTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    SamplePage()
                }
            }
        }
    }
}

@Composable
fun SamplePage() {
    val composableScope = rememberCoroutineScope()

    Column(
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Button(onClick = {
            composableScope.launch {
                val channel = supabase.channel("channelId") 
                val changeFlow = channel.postgresChangeFlow<PostgresAction>(schema = "public")

                changeFlow.collect {
                    when (it) {
                        is PostgresAction.Delete -> println("Deleted: ${it.oldRecord}")
                        is PostgresAction.Insert -> println("Inserted: ${it.record}")
                        is PostgresAction.Select -> println("Selected: ${it.record}")
                        is PostgresAction.Update -> println("Updated: ${it.oldRecord} with ${it.record}")
                    }
                }

                channel.subscribe()
            }
        }) {
            Text("press")
        }
    }
}
```

I am using the okhttp version of the ktor client as described in the [trouble shooting guide](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD).
```kts
    implementation(platform("io.github.jan-tennert.supabase:bom:2.4.1"))
    implementation("io.github.jan-tennert.supabase:postgrest-kt")
    implementation("io.github.jan-tennert.supabase:realtime-kt")

    implementation("io.ktor:ktor-client-okhttp:2.3.11")
```

**Comment by jan-tennert** [comment]
One problem I can observe (and I'm wondering why this isn't mentioned in the reference docs anymore) is that the `collect` method call suspends the entire coroutine until it's closed. That means the `subscribe` method never gets called. You could try to collect the flow in another coroutine:
```kotlin
                changeFlow.onEach {
                    when (it) {
                        is PostgresAction.Delete -> println("Deleted: ${it.oldRecord}")
                        is PostgresAction.Insert -> println("Inserted: ${it.record}")
                        is PostgresAction.Select -> println("Selected: ${it.record}")
                        is PostgresAction.Update -> println("Updated: ${it.oldRecord} with ${it.record}")
                    }
                }.launchIn(composableScope) //same as launching a new coroutine and collecting the flow

                channel.subscribe()
```

**Comment by dshukertjr** [comment]
Thanks, will try it out tomorrow to see if your code works. Let's definitely add this one in the reference docs.

**Comment by dshukertjr** [comment]
Does the following code then ever work? Should there always be a `launchIn()` call on the Flow?

```kotlin
val channel = supabase.channel("channelId") {
    //optional config
}
val changeFlow = channel.postgresChangeFlow<PostgresAction>(schema = "public")

//Collect the flow
changeFlow.collect {
    when(it) {
        is PostgresAction.Delete -> println("Deleted: ${it.oldRecord}")
        is PostgresAction.Insert -> println("Inserted: ${it.record}")
        is PostgresAction.Select -> println("Selected: ${it.record}")
        is PostgresAction.Update -> println("Updated: ${it.oldRecord} with ${it.record}")
    }
}

channel.subscribe()
```

**Comment by jan-tennert** [comment]
Well, as the `collect` method blocks the coroutine, it can't work. So you can either launch a new coroutine and call `collect` within, or use my shorthand method from above

**Comment by dshukertjr** [comment]
Good to know. Let's keep in mind that it's generally better if the code samples on the reference docs just work by copying and pasting. Let me fix the code on the reference docs 👍

**Comment by jan-tennert** [comment]
Alright, thanks!

**Comment by dshukertjr** [comment]
@jan-tennert 
Related to this, when working with Supabase realtime, would you ever use `.collect` on a Flow? It seems like in order to use the `.launchIn()`, you need to use `onEach`, so wondering if we should replace all the code samples on using `onEach` instead of `collect`.

**Comment by jan-tennert** [comment]
The docs also point to the Kotlin Flow docs, but I agree we should have copy-pastable snippets.

**Comment by dshukertjr** [comment]
Thanks for the clarification! I can work on the docs then!

**Comment by dshukertjr** [comment]
And will tag you for review!
