### ISSUE TITLE
[Feature request]: Use GetSignInWithGoogleOption instead of GetGoogleIdOption in ComposeAuth

### ISSUE THREAD

**Issue by Aaron246** [supabase-community/supabase-kt#643]
### General info

- [x] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

The ComposeAuth plugin uses GetGoogleIdOption for native google sign in.

As per the credential manager documentation [here](https://developer.android.com/identity/sign-in/credential-manager-siwg),

It is advised to use GetSignInWithGoogleOption while signing in with a button.

The GetGoogleIdOption shows a bottom sheet while GetSignInWithGoogleOption shows a dialog.

The GetGoogleIdOption is not meant to use with a button based UI because of a limitation.

![Screenshot_20240616-211629](https://github.com/supabase-community/supabase-kt/assets/110488580/1f602e2e-ba13-479f-9f2c-7feb7d114f9f)

If this setting is disabled on any one of the users google account on the device, the bottomsheet will not appear at all.
(Settings -> Google -> All Services -> Settings for Google apps -> Connected apps -> Third-party apps and services (the gear icon))

Hence, the GetGoogleIdOption method needs to be changed with GetSignInWithGoogleOption which will now show a dialog instead of a bottomsheet.

I am willing to fix this myself, do I need to fork the entire repository even if I want to work on the ComposeAuth directory only?

Sorry, this is my first time contributing 😅 also don't know if this was supposed to be tagged as a bug or a question.

**Comment by jan-tennert** [comment]
> I am willing to fix this myself, do I need to fork the entire repository even if I want to work on the ComposeAuth directory only?

Yes, you need to fork the entire repository. Checkout the [contribution guidelines](https://github.com/supabase-community/supabase-kt/blob/master/CONTRIBUTING.md) for more information. If you have questions regarding the code, feel free to ask.
> Sorry, this is my first time contributing 😅 also don't know if this was supposed to be tagged as a bug or a question.

This would probably be a feature request since this is neither a bug nor really a question, you are actively proposing a change in the library.
