### ISSUE TITLE
[Question]: Is it possible to update data without a DTO?

### ISSUE THREAD

**Issue by cansik** [supabase-community/supabase-kt#65]
### What is your question?

I would like to dynamically update data over postgrest by using a binding to my internal datastructure. It seems that in the [supabase-community/postgrest-kt](https://github.com/supabase-community/postgrest-kt#updating-data), this is possible, however I could not find a way to achieve the same with supabase-kt without using a DTO:

```kotlin
override suspended fun publishValue(key: String, data: Any) {
    val result = client.postgrest["mytablename"].update {
        key to data
    }
}
```

How can this be achieved without using a specific DTO?

**Comment by jan-tennert** [comment]
Do you mean [that](https://github.com/supabase-community/supabase-kt/blob/7a6c9e1ce49fa04ecb34a1cf5fa6dec0efd09597/Postgrest/src/commonMain/kotlin/io/github/jan/supabase/postgrest/query/PostgrestBuilder.kt#L91)?
```kotlin
client.postgrest["table"].update({
     set(key, data)
}) {
  //filter
}
```

**Comment by cansik** [comment]
Yes that is what I needed. Thank you.
