### ISSUE TITLE
[Question]: invalid input syntax for type timestamp with time zone: "null"

### ISSUE THREAD

**Issue by DominicGBauer** [supabase-community/supabase-kt#685]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

I am trying to update a row that has a date and change it to null. The field is nullable, however when I send this to update 
`table.update(entry.opData!!)` where `entry.opData` is `{completed=0, completed_at=null, completed_by=null}` I get `invalid input syntax for type timestamp with time zone: "null"`. 

I assume `null` is being converted to String `null` which is resulting in the issue. How can I overcome this?

### Relevant log output (optional)

```shell
Data upload error - retrying last entry: CrudEntry<3/3 PATCH todos/d6b6d112-e779-4389-a7b4-34c45808ecdc {completed=0, completed_at=null, completed_by=null}>, io.github.jan.supabase.exceptions.BadRequestRestException: invalid input syntax for type timestamp with time zone: "null"
```

**Comment by jan-tennert** [comment]
Can you share your actual Supabase code?

**Comment by DominicGBauer** [comment]
@jan-tennert 

```
                val table = supabaseClient.from(entry.table)

                    UpdateType.PATCH -> {
                        Logger.i(entry.opData!!.toString())
                        table.update(entry.opData!!) {
                            filter {
                                eq("id", entry.id)
                            }
                        }
                    }
  ```
  
<img width="658" alt="image" src="https://github.com/user-attachments/assets/619ba077-a652-4c38-bdff-e2e41d193ec8">

**Comment by DominicGBauer** [comment]
I am so sorry it's a fault on my side, the nulls are string nulls being sent from us.
