### ISSUE TITLE
[Bug]: Issue with reconnecting to realtime

### ISSUE THREAD

**Issue by JOsacky** [supabase-community/supabase-kt#698]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### Version(s)

2.6.0

### Kotlin Target(s) and their respective versions

All targets are affected

### What happened? (include your code)

I was looking into user reports around sporatic realtime connection. I think I figured out what is happening and I'm curious what the communities thoughts are on how to fix it

When we use presenceChangeFlow or broadcastFlow, `awaitClose { callbackManager.removeCallbackById(id) }` happens so when we disconnect from realtime, the callbacks are removed. Unfortunately this causes a bug when reconnecting to realtime. For example if a hearbeat fails, we will go into the reconnecting state which disconnects the realtime channel. Our callbacks are removed because we are disconnected momentarily and then upon reconnecting, the callbacks are no longer triggered. Reconnections happen all the time with realtime from my experience so my users are not happy with the reliability of realtime connections. Relevant code below: 

```
    private suspend fun sendHeartbeat() {
        if (heartbeatRef != 0) {
            heartbeatRef = 0
            ref = 0
            Realtime.logger.e { "Heartbeat timeout. Trying to reconnect in ${config.reconnectDelay}" }
            scope.launch {
                disconnect()
                connect(true)
            }
            return
        }
        Realtime.logger.d { "Sending heartbeat" }
        heartbeatRef = ++ref
        send(RealtimeMessage("phoenix", "heartbeat", buildJsonObject { }, heartbeatRef.toString()))
    }
    ```

RealtimeChannel.kt
```
fun RealtimeChannel.presenceChangeFlow(): Flow<PresenceAction> {
    return callbackFlow {
        val callback: (PresenceAction) -> Unit = { action ->
            trySend(action)
        }

        val id = callbackManager.addPresenceCallback(callback)
        awaitClose { callbackManager.removeCallbackById(id) }
    }
} 
```
        
        My code: 
        ```
                        checkNotNull(supabaseRealtimeChannel).subscribe(true)
                        
                        checkNotNull(supabaseRealtimeChannel).presenceDataFlow<FleetLocationPresence>()
                            .onEach { presenceData ->
                                Log.d("SupabaseRealtimeRepository", "Received presence data: $presenceData")
                                _presenceDataStateFlow.value =
                                    presenceData.associateBy { presence -> presence.profile_id }
                            }.launchIn(coroutineScope)
                            
                        ```
                            

### Steps To Reproduce (optional)

the best way to reproduce is to create a realtime connection and put the phone in airplane mode so that the realtime connections fails and starts reconnecting. After reconnecting, observer that the callbacks are no longer used.

**Comment by jan-tennert** [comment]
Hi, `awaitClose` shouldn't be the problem here, as this is only called if the coroutine scope/job where the flow is collected in, gets cancelled.
I just tried to simulate something like this, disabled the network connection while still collecting my postgres change flow and after automatically reconnecting, everything still works.
> I was looking into user reports around sporatic realtime connection. 

So this has to be because of some other issue 🤔

**Comment by JOsacky** [comment]
@jan-tennert thank you so much for your fast response and for trying this out. This must be some implementation issue with my code then, I'll keep trying to fix and post here with the solution

**Comment by JOsacky** [comment]
I see my issue.

Users of realtime channels should only create one channel and rely on the reconnection infra. 

My mistake was that if the status was updated to disconnected (which happens frequently) I would re-create the channel. Disconnected does not mean the channel is dead, it most likely means that it is reconnecting

Do you know how we can tell if the channel is dead and not reconnecting, should we ever create a new channel?

**Comment by jan-tennert** [comment]
The channel is "dead" if it isn't stored in `Realtime#subscriptions` anymore. That only happens if `Realtime#removeChannel` or `RealtimeChannel#unsubscribe` is called manually and even then you don't need to create a new channel, you can just reuse the old one by executing `RealtimeChannel#subscribe`.
