### ISSUE TITLE
[Question]: Does this work with KMP JVM (Ktor Server)?

### ISSUE THREAD

**Issue by basurahan** [supabase-community/supabase-kt#702]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

I am building api server using KMP Ktor. When I am calling `createSupabaseClient` i get
an exception `ExceptionInInitializerError` when I remove that call to `createSupabaseClient` it works fine so I know its `createSupabaseClient` that producing it

### Relevant log output (optional)

```shell
Info: (Supabase-Core) SupabaseClient created! Please report any bugs you find.
2024-08-31 15:02:25.313 [eventLoopGroupProxy-4-1] TRACE i.k.s.p.statuspages.StatusPages - Call /api/v1/register failed with cause java.lang.ExceptionInInitializerError
2024-08-31 15:02:25.373 [eventLoopGroupProxy-4-1] TRACE i.k.s.p.statuspages.StatusPages - Executing (io.ktor.server.application.ApplicationCall, kotlin.Throwable) -> kotlin.Unit for exception java.lang.ExceptionInInitializerError for call /api/v1/register
```

**Comment by jan-tennert** [comment]
Did you take a look at [this](https://supabase.com/docs/reference/kotlin/installing#add-ktor-client-engine-to-each-of-your-kotlin-targets-required) docs section?

**Comment by basurahan** [comment]
Yes I followed the docs
<img width="1440" alt="Screenshot 2024-08-31 at 4 33 34 PM" src="https://github.com/user-attachments/assets/5b4f6340-ee59-4082-954f-701998053a5b">

**Comment by jan-tennert** [comment]
Can you post the full exception?

**Comment by basurahan** [comment]
The full exception is posted in the Relevant log output. Here is a screenshot as a proof
<img width="956" alt="Screenshot 2024-08-31 at 4 46 55 PM" src="https://github.com/user-attachments/assets/f14bf762-d207-4147-9f47-7e56099c8cf1">

**Comment by jan-tennert** [comment]
That is not the full stacktrace. Try to try catch it.

**Comment by basurahan** [comment]
Seems like http client is missing but as we can see I already added CIO @jan-tennert

**Comment by basurahan** [comment]
Its now working I restarted fleet 🙈
