### ISSUE TITLE
[Feature request]: add support for Ktor 3

### ISSUE THREAD

**Issue by vad-zuev** [supabase-community/supabase-kt#703]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Hi there 👋  I'm trying to use `io.github.jan-tennert.supabase:postgrest-kt` (2.6.0) in a Ktor 3.0.0-beta-2 backend app and quickly realized I run into problems by just trying to create a client:

```kotlin
createSupabaseClient(url, key) { install(Postgrest) }
```

This causes a 

> java.lang.NoClassDefFoundError: io/ktor/client/plugins/contentnegotiation/ContentNegotiation
> 	at io.github.jan.supabase.network.KtorSupabaseHttpClient.applyDefaultConfiguration(KtorSupabaseHttpClient.kt:108)

A "fix" by using     

```
resolutionStrategy {
        force("io.ktor:ktor-client-content-negotiation-jvm:2.3.12")
    }
```

seems to just shift the problem down the road (_edit: and also breaks other code_): now I'm getting a 

> java.lang.NoClassDefFoundError: io/ktor/client/plugins/HttpTimeout
> 	at io.github.jan.supabase.network.KtorSupabaseHttpClient.applyDefaultConfiguration(KtorSupabaseHttpClient.kt:111)

It would be really cool if supabase-kt introduced support for Ktor 3. Thanks 🙇 

### Usecase

Building on a recent Ktor version

**Comment by jan-tennert** [comment]
You can use the [WASM build](https://github.com/supabase-community/supabase-kt/releases/tag/2.6.0-wasm0) for now, which also uses Ktor 3 aside from adding WASM support.

**Comment by vad-zuev** [comment]
thanks for clarifying the correct version, it does indeed work with Ktor 3 👍

**Comment by XanderZhu** [comment]
> You can use the [WASM build](https://github.com/supabase-community/supabase-kt/releases/tag/2.6.0-wasm0) for now, which also uses Ktor 3 aside from adding WASM support.

This solution helps me too

**Comment by jan-tennert** [comment]
Note that the newest beta 3.0.0-beta-1 supports WASM out of the box.
