### ISSUE TITLE
[Bug]: invalid JWT: unable to parse or verify signature, token signature is invalid: signing method RS256 is invalid

### ISSUE THREAD

**Issue by Shabinder** [supabase-community/supabase-kt#704]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### Version(s)

2.6.0

### Kotlin Target(s) and their respective versions

Desktop JVM 21

### What happened? (include your code)

implemented OAuth as per documentation and sample.

```
io.github.jan.supabase.gotrue.exception.AuthRestException: 
invalid JWT: unable to parse or verify signature, token signature is invalid: signing method RS256 is invalid
```

My Desktop Intent Code:
```
if (intent.startsWith(Supabase.REDIRECT_URL_SCHEME)) {
    val fragment = intent.substringAfter("#")
    authManager.importSession(fragment)
        .onRight { toaster.showSuccessToast("Logged you in: $it") }
        .onLeft { toaster.showErrorToast("Intent Error: $it") }
```

Also, I can see the user auth with google as a provider in supabase, but client gives below error.

### Relevant log output (optional)

```shell
Exception in thread "DefaultDispatcher-worker-11" io.github.jan.supabase.gotrue.exception.AuthRestException: invalid JWT: unable to parse or verify signature, token signature is invalid: signing method RS256 is invalid
	at io.github.jan.supabase.gotrue.AuthImpl.checkErrorCodes(AuthImpl.kt:523)
	at io.github.jan.supabase.gotrue.AuthImpl.parseErrorResponse(AuthImpl.kt:491)
	at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:60)
	at io.github.jan.supabase.gotrue.AuthenticatedSupabaseApiKt$authenticatedSupabaseApi$3.invoke(AuthenticatedSupabaseApi.kt:60)
	at io.github.jan.supabase.network.SupabaseApi.rawRequest$suspendImpl(SupabaseApi.kt:25)
	at io.github.jan.supabase.network.SupabaseApi$rawRequest$1.invokeSuspend(SupabaseApi.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
```

**Comment by jan-tennert** [comment]
So you are not using the built in OAuth? What does `authManager.importSession()` look like?

**Comment by Shabinder** [comment]
I am using built i OAuth.

The Client is Desktop Application, using 

googleLogin():
`supabaseClient.auth.signUpWith(Google)`

and importSession() is:
`supabaseClient.auth.parseFragmentAndImportSession(fragment)`

Using the same code as being used in sample.

**Comment by jan-tennert** [comment]
Which sample are you referring to? Did you try to print out the fragment?
Also, by default, that is the built-in OAuth for Desktop/JVM:
 ![Screenshot_20240901_192159_Chrome.jpg](https://github.com/user-attachments/assets/a7ae9446-1fe6-4a01-97de-3c02cad54a95)

So normally, you don't have to do any parsing.

**Comment by Shabinder** [comment]
https://github.com/supabase-community/supabase-kt/blob/eccacf8d8ff24bb8612bae13268eab84784cae31/demos/multiplatform-deeplinks/desktop/src/main/kotlin/Main.kt#L35

This is the sample I referred to.

Fragment looks good, I did logged it, it contains info like accessCode, bearerToken, and so.
The user did got created in supabase backend, I can see it in studio, but not logged in client, since above error happens.

Ideally the WebOauth should work, should it not ?

**Comment by Shabinder** [comment]
Also I have the code you mentioned in Documentation:
```
actual fun AuthConfig.platformGoTrueConfig() {
    httpCallbackConfig {
        this.htmlTitle = "Soundbound App"
    }
}
```

So is there like a different way to toggle the OAuth flow ?
is the sample I am referring to not the correct / updated on how it should work ?

**Comment by jan-tennert** [comment]
Well, you are mixing two approaches for implementing OAuth.
1) Would be just using the approach mentioned in the docs, where a HTTP Callback sever is used. For this, you don't really have to do anything besides adding localhost to whitelisted redirect urls in the dashboard. The library will take care of everything.
2) A custom approach like using deeplinks. I'm not sure why you get this error, does email sign in work (or whatever you are using besides this)?

**Comment by Shabinder** [comment]
> does email sign in work (or whatever you are using besides this)?

Yes Email SignIn Works.

I tried using another flow with pkce, after clicking on authorise in the web window, my supabase dashboard opens, and 
`siteURL?code=xxxxxxx-xxxxxx-xxxxxxxxx`

How does my client know about that ?

I think I am missing a step or configuring a thing wrong ? 
Any pointers ?

**Comment by Shabinder** [comment]
Also, why is the flow with custom webserver not being triggered ?, as you said that should be the approach and it should handle almost everything ?

**Comment by jan-tennert** [comment]
If you provide a custom redirect url in `signInWith` or `signUpWith`, then the default implementation will not be used

**Comment by Shabinder** [comment]
Yes I was just reading that bit, 
trying without that now...

**Comment by Shabinder** [comment]
Yes I removed the custom deep link scheme from redirectUrl,

Now after google authorization in web window, it redirects to my site with this data:

https://mysite.com/project/default#access_token=xxxx&expires_at=xxxx&expires_in=3600&provider_token=xxxxx&token_type=bearer

I remember since this was happening, I typed in redirectUrl for this to go to my app.

Now coming back, what would be my next steps here ?

**Comment by Shabinder** [comment]
aah got it, after relaunchin, its now redirecting to below.
http://localhost:52750/callback?access_token=xxxxxx&refresh_token=xxxx&expires_in=3600&token_type=bearer

Getting below, in browser after redirection

**This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500**

**Comment by Shabinder** [comment]
Update:
Callback Flow gave 500.

but with flow as PKCE, it worked!, I am glad it finally worked, but would like to keep this issue open until we can have more clarity why normal callback one didnt work and was giving 500.

**Comment by jan-tennert** [comment]
Great to hear that! Did you see any logs when using the Implicit flow?

**Comment by Shabinder** [comment]
Nope, which would point to something, while browsing code, I saw there are multiple logs everywhere, like OAuth Server Starts, ends and so on.

but in terminal they were not appearing for some reason, are they disabled, since I was running a dmg.

**Comment by Shabinder** [comment]
Refer above issue, for details.
