### ISSUE TITLE
[Feature request]: Add forgot password / otp verification flow to sample with multi-factor authentication.

### ISSUE THREAD

**Issue by Shabinder** [supabase-community/supabase-kt#705]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Add forgot password / otp verification flow to sample with multi-factor authentication.

**Comment by jan-tennert** [comment]
Do you mean adding these flows to the current sample or creating another one? The MFA sample was originally meant to just showcase the MFA flow.

**Comment by Shabinder** [comment]
Your choice, if you feel addition of this to MFA will bloat that sample up,
then having this as another sample makes sense.
