### ISSUE TITLE
[Question]: Error on createSupabaseClient(), Function not found

### ISSUE THREAD

**Issue by aarchish** [supabase-community/supabase-kt#711]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

I have scoured the internet, Supabase Docs, this GitHub repo and all the issues.

I am not able to find the import dependency for createSupabaseClient()

val supabase = createSupabaseClient(
    supabaseUrl = "https://xyzcompany.supabase.co",
    supabaseKey = "your_public_anon_key"
  ) {
    install(Postgrest)
}

If I try to do "import io.github.jan-tennert.", I get error on "github"

**Comment by aarchish** [comment]
![Screenshot 2024-09-02 210725](https://github.com/user-attachments/assets/b39733b1-34a3-4e07-a34d-908737e5cc1f)

**Comment by aarchish** [comment]
YouTube Video (Official Guide) : https://www.youtube.com/watch?v=P_jZMDmodG4&t=330s
Tyler Shukert right click and does an import on createSupabaseClient function which is not available to me,
this happens when the dependencies in the files are not imported and the required class functions are not available

**Comment by jan-tennert** [comment]
The package should be `io.github.jan.tennert.supabase`.
How did you add the Supabase dependencies?

**Comment by aarchish** [comment]
build.gradle.kts (app)
// Supabase Dependencies
    implementation(libs.bom)
    implementation(libs.postgrest.kt)
    implementation(libs.gotrue.kt)
    implementation(libs.ktor.client.android)
    
libs.version.toml

bom = "2.1.3"
ktorClientAndroid = "2.3.8"
bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "bom" }
gotrue-kt = { module = "io.github.jan-tennert.supabase:gotrue-kt" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt" }

**Comment by jan-tennert** [comment]
Two things I can see there:
1) You are using an old version of supabase-kt
2) BOMs don't work like that. If you are using a version catalog anyway, just add `version.ref = "bom"` to gotrue and postgrest and remove the bom dependency.

**Comment by aarchish** [comment]
I mean that's how it is on the YouTube guide.
Shall I use 
supabase-kt bom : 2.6.0 
ktor : 2.3.12
?

**Comment by jan-tennert** [comment]
> Shall I use

Yes

> I mean that's how it is on the YouTube guide.

The video guides didn't use a gradle version catalog, but both approaches work.

**Comment by aarchish** [comment]
Quick update

supabasebom = "2.1.3"
bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabasebom" }
gotrue-kt = { module = "io.github.jan-tennert.supabase:gotrue-kt", version.ref = "supabasebom" }
postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabasebom" }

import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.gotrue.Auth
import io.github.jan.supabase.postgrest.Postgrest

This has fixed my issue,
Thanks,
Once I have my code working as intended, I will update the dependencies to the latest versions
