### ISSUE TITLE
[Question]: How to increment a integer column without knowing the current value of the column

### ISSUE THREAD

**Issue by basurahan** [supabase-community/supabase-kt#715]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

Hi in query its easy but how do i do it with this kotlin library? For example
```
UPDATE totals 
   SET total = total + 1
WHERE name = 'bill';
```
We can increment the total without knowing the current value of the total how do i do that in this library?

**Comment by jan-tennert** [comment]
I don't think that is possible via the PostgREST API. You have two options:
- Fetch the current value 
- Create a [database function](https://supabase.com/docs/guides/database/functions) and call it via `Postgrest#rpc`

**Comment by basurahan** [comment]
Okay thanks. But wouldn't you think its a great addition if we can do that ? Thanks @jan-tennert

**Comment by jan-tennert** [comment]
It's not possible via the API
