### ISSUE TITLE
How do I update the user password?

### ISSUE THREAD

**Issue by cz9dev** [supabase-community/supabase-kt#73]
### What is your question?

How do I update the user password?.
I have tried to use client.gotrue.modifyUser(), but I don't know how, can someone show me an example?

**Comment by jan-tennert** [comment]
> ### What is your question?
> How do I update the user password?. I have tried to use client.gotrue.modifyUser(), but I don't know how, can someone show me an example?

You can edit the user's password by putting in a Provider as the first argument:
```kotlin
client.gotrue.modifyUser(Email) {
    password = "123456"
}
//or
client.gotrue.modifyUser(Phone) {
    password = "123456"
}
```

**Comment by cz9dev** [comment]
Ok thanks you
