### ISSUE TITLE
[Feature request]: need to add custom timeout

### ISSUE THREAD

**Issue by patelabhilash** [supabase-community/supabase-kt#765]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

Request to add a custom timeout option, as the database currently provides a 2-minute timeout, but the client is restricting it to only 10 seconds. There is no parameter available to adjust this.
```
private val supabaseClient: SupabaseClient by lazy {
        createSupabaseClient(
            supabaseUrl = BuildConfig.SUPABASE_URL,
            supabaseKey = BuildConfig.SUPABASE_ANON_KEY
        ) {
            install(Postgrest)
        }
    }
```

### Usecase

I believe the reason for requesting this is well understood. Please let me know if there is already a workaround. I’m asking because I could not find any documentation on this.

**Comment by jan-tennert** [comment]
There is an option:
```kotlin
private val supabaseClient: SupabaseClient by lazy {
        createSupabaseClient(
            supabaseUrl = BuildConfig.SUPABASE_URL,
            supabaseKey = BuildConfig.SUPABASE_ANON_KEY
        ) {
            requestTimeout = 2.minutes
            install(Postgrest)
        }
    }
```
