### ISSUE TITLE
[Enhancement]: Make Android Min SDK Obvious

### ISSUE THREAD

**Issue by rocxteady** [supabase-community/supabase-kt#786]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### Version(s)

3.0.1

### Kotlin Target(s) and their respective versions

Android 7

### What happened? (include your code)

You should make your min sdk support for Android a little bit obvious. I can build my app with min sdk 24 and it crashes because UserSession object has an java.time.Insant object which is min sdk 26. Supabase has some examples using a sdk even less than 24.

I am guessing your min sdk is 26. I could not find any information about your min sdk at anywhere in your documentation.

### Steps To Reproduce (optional)

Just build an app with Android API Level 24(Android 7) and make an authentication.

### Relevant log output (optional)

```shell
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
```

**Comment by jan-tennert** [comment]
Yea, the minimum SDK version is `26`. I'll find a place to mention this!

**Comment by rocxteady** [comment]
Thank you @jan-tennert 🙌

**Comment by jan-tennert** [comment]
Added a note in the README and reference docs.
