### ISSUE TITLE
[Question]: how to use SessionStatus

### ISSUE THREAD

**Issue by cz9dev** [supabase-community/supabase-kt#79]
### What is your question?

how to use SessionStatus

**Comment by jan-tennert** [comment]
Theres a [wiki page](https://github.com/supabase-community/supabase-kt/wiki/Login#listen-to-session-changes) for it. Basically its a kotlin [flow](https://kotlinlang.org/docs/flow.html#flows) firing new values whenever the session changes

**Comment by cz9dev** [comment]
ok thank
