### ISSUE TITLE
[Question]: Support for Native Google Services Authentication in Multiplatform SDK

### ISSUE THREAD

**Issue by orelvis15** [supabase-community/supabase-kt#790]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

Hello, good morning.

First of all, thank you for all the hard work on this SDK and on the project in general.

I’d like to ask if this multiplatform SDK supports authentication via Google Services by opening the native interface to select accounts configured on the device. I’ve been looking for this feature but haven't been able to find it in the SDK or its documentation.

Could you please let me know if this functionality is available and, if so, how to implement it? If it's not yet supported, are there any plans to add it in the future?

Thank you very much for your help and time!

**Comment by jan-tennert** [comment]
Hi, there is [Compose Auth](https://github.com/supabase-community/supabase-kt/tree/master/plugins/ComposeAuth) which has composables for signing in on Compose Multiplatform via Native SDKs. Note that only Android supports Native Google Auth and only iOS supports Native Apple Auth. All other combinations use `supabase.auth.signInWith(Provider)` (OAuth via the browser).

There is also a [entry](https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=platform&platform=android) about Native Google Auth in the docs, which provides samples for Android only with credentials & Multiplatform with Compose Auth (which basically uses credentials under the hood for Android).
