### ISSUE TITLE
[Question]: How to configure supabase to use okhttp with presence

### ISSUE THREAD

**Issue by arbyruns** [supabase-community/supabase-kt#798]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

I’m working on implementing Supabase Realtime Presence in a Kotlin project, but I’m running into an issue connecting to the Realtime WebSocket. The error I’m encountering is:

`Error while trying to connect to realtime websocket`

I understand that the issue is related to Ktor being used as the HTTP client, which doesn’t have WebSocket support configured by default. However, I’m unsure how to configure the Supabase client to use OkHttp as the WebSocket engine instead.

Here’s what I currently have in my gradle.toml file for OkHttp:
`okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }`

Does anyone have experience setting up Supabase Realtime Presence with OkHttp for WebSockets in Kotlin? Specifically, I’d like to understand how to configure Supabase to use OkHttp properly for this purpose.

Any example code or guidance would be much appreciated!

**Comment by jan-tennert** [comment]
You have to add the [OkHttp Ktor Engine](https://ktor.io/docs/client-engines.html#okhttp), not OkHttp itself. And you don't have to configure anything, having the dependency is enough.
The engines all follow the same pattern, as described in the [README](https://github.com/supabase-community/supabase-kt#add-a-ktor-client-engine-to-each-of-your-kotlin-targets) and docs.

**Comment by arbyruns** [comment]
Thanks Jan! This was good to know and learned something new!
