### ISSUE TITLE
[Question]: How to observe changes when performing joins

### ISSUE THREAD

**Issue by rafsanjani** [supabase-community/supabase-kt#805]
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### What is your question?

I have looked through the documentation but havent found any snippet on how to observe changes from affected tables when performing joins.

`selectAsFlow` doesn't seem to have an option for specifying nested tables referenced by a foreign key. Perhaps there is something else I am missing

**Comment by jan-tennert** [comment]
Not possible. See https://github.com/supabase/supabase-flutter/issues/642 and https://github.com/supabase/realtime/issues/303
