### ISSUE TITLE
[Bug]: Postgrest update function with bool does not work as intended

### ISSUE THREAD

**Issue by AzureStar123** [supabase-community/supabase-kt#817]
### General Info

- [X] I checked for similar bug report
- [X] I am using the latest version
- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### Version(s)

3.0.3

### Kotlin Target(s) and their respective versions

All of them

### What happened? (include your code)

When using the client to update a class for example:

```@Serializable
data class Post(
    val id: Long,
    val isFavorite: Boolean
)

client.postgrest["posts"].update(post.copy(isFavorite = false)) {
            filter {
                Post::id eq post.id
            }
        }
```
Only when isFavorite is set to true the update works. But if it is set to false it does not work. This only occurs when passing the object directly when using the other setTo syntax it works for both true and false.

**Comment by jan-tennert** [comment]
Is the specified data class the object? And did you try, just for testing to have an object with only the isFavorite parameter? (can also use a new one for testing)

**Comment by AzureStar123** [comment]
Yes the specified data class is the object, also everything else works as intended I also tried with other objects the update works normally except for bool set to false.

**Comment by AzureStar123** [comment]
After some digging, I figured out the problem, the code set the default value of isFavorite to false.

```
data class Post(
    val id: Long,
    val isFavorite: Boolean = false,
)
```

```
// Will work with isFavorite default to false
client.postgrest["posts"].update(post.copy(isFavorite = true)) {
            filter {
                Post::id eq post.id
            }
}

// Will not work with isFavorite default to false
client.postgrest["posts"].update(post.copy(isFavorite = false)) {
            filter {
                Post::id eq post.id
            }
}
```

Does using default parameters like this affect the functionality of the object?

Also the inverse of this for example:

```
data class Post(
    val id: Long,
    val isFavorite: Boolean = true,
)
```

So here using the update function the value can be changed to false but it will not work if set to true:

```
// Will work with isFavorite default to true
client.postgrest["posts"].update(post.copy(isFavorite = false)) {
            filter {
                Post::id eq post.id
            }
}

// Will not work with isFavorite default to true
client.postgrest["posts"].update(post.copy(isFavorite = true)) {
            filter {
                Post::id eq post.id
            }
}
```

**Comment by jan-tennert** [comment]
Then it is probably related to the default KotlinX Serialization config. See this thread for more information: https://slack-chats.kotlinlang.org/t/23129831/feel-like-i-m-hitting-a-bug-present-in-3-0-and-3-0-dev1-didn

**Comment by AzureStar123** [comment]
Thanks it solved the issue
