### ISSUE TITLE
[Question]: Why doesn't it return the list of files?

### ISSUE THREAD

**Issue by cz9dev** [supabase-community/supabase-kt#83]
### What is your question?

```
var bucketAds = Client.client.storage["ads"]
var listBucket = bucketAds.list("vs_")

println(listBucket.size)
```

The function returns 0 when it shouldn't be, since there are files in the storage

**Comment by jan-tennert** [comment]
If there is no error, you may not have access to this bucket. I suppose its not public?

**Comment by cz9dev** [comment]
It's public, I also have images inside, but it doesn't show me the list of images, and I need a list to fill an array with their names

**Comment by jan-tennert** [comment]
The endpoint does need a valid session for some reason. Do you handle that?

**Comment by cz9dev** [comment]
I found the problem, I had to give the correct permissions, I will close the question.
