### ISSUE TITLE
Add new storage features introduced in LW7 updates

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/supabase-kt#88]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

# Feature request

Hi there,

There has been some features added to our storage, and we made some changes to the js client library to be able to use those features. It would be great if these could be added to this client library as well!

- https://github.com/supabase/storage-js/pull/151 file size and mime type limits per bucket
- https://github.com/supabase/storage-js/pull/152 signed url for uploads
- https://github.com/supabase/storage-js/pull/145 quality option for image transformations
- https://github.com/supabase/storage-js/pull/142 format option for image transformation

### Usecase

Image quality optimization, more image transformations options, signed url for uploads.

**Comment by jan-tennert** [comment]
> ### General Info
> * [x]  I installed the latest version of Supabase Kt
> * [x]  I checked for similar feature requests
> 
> ### Feature request
> # Feature request
> Hi there,
> 
> There has been some features added to our storage, and we made some changes to the js client library to be able to use those features. It would be great if these could be added to this client library as well!
> 
> * [feat: custom file size limit and mime types at bucket level supabase/storage-js#151](https://github.com/supabase/storage-js/pull/151) file size and mime type limits per bucket
> * [feat: added methods for signed-url upload supabase/storage-js#152](https://github.com/supabase/storage-js/pull/152) signed url for uploads
> * [feat: quality option, image transformation supabase/storage-js#145](https://github.com/supabase/storage-js/pull/145) quality option for image transformations
> * [feat: format option for webp support supabase/storage-js#142](https://github.com/supabase/storage-js/pull/142) format option for image transformation
> 
> ### Usecase
> Image quality optimization, more image transformations options, signed url for uploads.

Thanks for this issue! I have made a PR supporting these new features, will merge it soon.
