### ISSUE TITLE
[Feature request]: Allow upserting into Storage bucket

### ISSUE THREAD

**Issue by jollygreenegiant** [supabase-community/supabase-kt#91]
### General Info

- [X] I installed the latest version of Supabase Kt
- [X] I checked for similar feature requests

### Feature request

The javascript API allows upserting data into a storage bucket by way of the `upload()` function, [documented here](https://supabase.com/docs/reference/javascript/storage-from-upload#:~:text=%27avatars%27)-,Upload,-a%20file)

I'd love to see similar functionality in the Kotlin API, as right now using the `upload()` function to an existing path throws an error.  If it's as simple as changing the method signature to something like `suspend fun upload(path: String, data: ByteArray, upsert: Boolean): String` and determining whether to call the POST or PUT based on the upsert parameter, that's a pull request I can submit myself, but I'm not sure if there are more considerations than just that.

### Usecase

I don't want to have to check client-side if a URL already exists before uploading a file to a storage bucket, since the upsert functionality is already built into the Supabase API

**Comment by jan-tennert** [comment]
> ### General Info
> * [x]  I installed the latest version of Supabase Kt
> * [x]  I checked for similar feature requests
> 
> ### Feature request
> The javascript API allows upserting data into a storage bucket by way of the `upload()` function, [documented here](https://supabase.com/docs/reference/javascript/storage-from-upload#:~:text=%27avatars%27)-,Upload,-a%20file)
> 
> I'd love to see similar functionality in the Kotlin API, as right now using the `upload()` function to an existing path throws an error. If it's as simple as changing the method signature to something like `suspend fun upload(path: String, data: ByteArray, upsert: Boolean): String` and determining whether to call the POST or PUT based on the upsert parameter, that's a pull request I can submit myself, but I'm not sure if there are more considerations than just that.
> 
> ### Usecase
> I don't want to have to check client-side if a URL already exists before uploading a file to a storage bucket, since the upsert functionality is already built into the Supabase API

Looking at their code, you have to add the `x-upsert` header for the corresponding request. Made a PR, will publish a new version in a few, found a stackoverflow exception too

**Comment by jollygreenegiant** [comment]
Awesome, thank you!
