### ISSUE TITLE
[Question]: Adding data to a column with array type

### ISSUE THREAD

**Issue by unovil** [supabase-community/supabase-kt#95]
### What is your question?

Hi! I'm currently working on a project involving a QR scanner that routinely adds the timestamp of when it captured a certain QR code into an array. I worked out how to send a timestamp (using a string) but now I can't figure out how to send an array of timestamps.

Is there a certain syntax for pushing a new value to an array inside the timestamp array column? Should I just `GET` the whole array, dump it into a string, remove the bracket and add the timestamp, and join the whole thing again make it look like an array? I feel like I'm not getting something, like there *should* be an easier way to go about this.

Thanks!

**Comment by jan-tennert** [comment]
> 

I don't think the API supports inserting a value in an array. There are two options:
- You get the whole array, add your value and then update it via postgrest. Also why would you need to convert the array into a string?
- Make database function which you can call via `client.postgrest.rpc()` which makes this possible

**Comment by unovil** [comment]
I don't know what type I'm getting when I get the array from the set, I figured that since timestamp has a `string` type in the serializable data class, maybe the array should also have a `string` type, hence asking to parse all that. 

What type in the data class would I use to insert/update an array (column doesn't allow null) when adding/modifying a record?

**Comment by jan-tennert** [comment]
> I don't know what type I'm getting when I get the array from the set, I figured that since timestamp has a `string` type in the serializable data class, maybe the array should also have a `string` type, hence asking to parse all that.
> 
> What type in the data class would I use to insert/update an array (column doesn't allow null) when adding/modifying a record?

There is [kotlinx datetime](https://github.com/Kotlin/kotlinx-datetime) with classes automatically supporting serialization. So you could have your data class like this:
```kotlin
@Serializable
data class YourType(
   val id: Int, //assuming you have an id
    val timestamps: List<Instant> //instant is from the datetime library
)
```
Then you can update the table using postgrest:
```kotlin
client.postgrest["table"].update({
    YourType::timestamps setTo oldTimestamps + newTimestamp
}) {
    YourType::id eq id
}
```

**Comment by jan-tennert** [comment]
> I don't know what type I'm getting when I get the array from the set, I figured that since timestamp has a `string` type in the serializable data class, maybe the array should also have a `string` type, hence asking to parse all that.
> 
> What type in the data class would I use to insert/update an array (column doesn't allow null) when adding/modifying a record?

Did that work?

**Comment by unovil** [comment]
Sorry for the late reply. Yes, it worked. It led to some problems involving the timestamp, but I only figured it out now since `Instant` records the time zone but the type `timestamp` on the database doesn't. Thankfully though, i fixed it. Thanks for the help!
